// Code generated by protoc-gen-godefaults. DO NOT EDIT.
// versions:
// 		protoc-gen-godefaults 0.0.1
// source: tests/proto/cases/boundary/circular_reference.proto

package pbcr

import (
	_ "github.com/yu31/protoc-plugin-defaults/xgo/pb/pbdefaults"
)

// Set default value for message CRMessageA that in file tests/proto/cases/boundary/circular_reference.proto
func (x *CRMessageA) SetDefaults() {
	if x == nil {
		return
	}
	if x.T1 == "" {
		x.T1 = "123"
	}
	if x.MsgB == nil {
		x.MsgB = &CRMessageB{}
	}
	if x.MsgB != nil {
		x.MsgB.SetDefaults()
	}
}

// Set default value for message CRMessageB that in file tests/proto/cases/boundary/circular_reference.proto
func (x *CRMessageB) SetDefaults() {
	if x == nil {
		return
	}
	if x.T1 == "" {
		x.T1 = "456"
	}
	if x.MsgC == nil {
		x.MsgC = &CRMessageC{}
	}
	if x.MsgC != nil {
		x.MsgC.SetDefaults()
	}
}

// Set default value for message CRMessageC that in file tests/proto/cases/boundary/circular_reference.proto
func (x *CRMessageC) SetDefaults() {
	if x == nil {
		return
	}
	if x.T1 == "" {
		x.T1 = "789"
	}
	if x.MsgA == nil {
		x.MsgA = &CRMessageA{}
	}
	if x.MsgA != nil {
		x.MsgA.SetDefaults()
	}
}
