// Code generated by protoc-gen-godefault. DO NOT EDIT.
// versions:
// 		protoc-gen-godefault 0.0.1
// source: tests/proto/cases/empty/empty_repeated.proto

package pbempty

import (
	_ "github.com/yu31/protoc-plugin-default/xgo/pb/pbdefault"
	_ "github.com/yu31/protoc-plugin-default/xgo/tests/pb/pbexternal"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

// Set default value for message MessageRepeated1 that in file tests/proto/cases/empty/empty_repeated.proto
func (x *MessageRepeated1) SetDefault() {
	if x == nil {
		return
	}
}

// Set default value for message Embed1 that in file tests/proto/cases/empty/empty_repeated.proto
func (x *MessageRepeated1_Embed1) SetDefault() {
	if x == nil {
		return
	}
}

// Set default value for message Embed2 that in file tests/proto/cases/empty/empty_repeated.proto
func (x *MessageRepeated1_Embed1_Embed2) SetDefault() {
	if x == nil {
		return
	}
}

// Set default value for message TypeRepeated1 that in file tests/proto/cases/empty/empty_repeated.proto
func (x *TypeRepeated1) SetDefault() {
	if x == nil {
		return
	}
	for _, ri := range x.FEnum1 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, ri := range x.FEnum2 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, ri := range x.FMessage11 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, ri := range x.FMessage12 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, ri := range x.FMessage13 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, ri := range x.FMessage14 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, ri := range x.FMessage15 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, ri := range x.FMessage16 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, ri := range x.FMessage17 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, ri := range x.FMessage18 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, ri := range x.FMessage21 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, ri := range x.FMessage22 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, ri := range x.FMessage23 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, ri := range x.FMessage24 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, ri := range x.FMessage25 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, ri := range x.FMessage26 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, ri := range x.FMessage27 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, ri := range x.FMessage28 {
		if ri != nil {
			ri.SetDefault()
		}
	}
}
