// Code generated by protoc-gen-godefaults. DO NOT EDIT.
// versions:
// 		protoc-gen-godefaults 0.0.1
// source: tests/proto/cases/empty/empty_optional.proto

package pbempty

import (
	_ "github.com/yu31/protoc-plugin-defaults/xgo/pb/pbdefaults"
	_ "github.com/yu31/protoc-plugin-defaults/xgo/tests/pb/pbexternal"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

// Set default value for message MessageOptional1 that in file tests/proto/cases/empty/empty_optional.proto
func (x *MessageOptional1) SetDefaults() {
	if x == nil {
		return
	}
}

// Set default value for message Embed1 that in file tests/proto/cases/empty/empty_optional.proto
func (x *MessageOptional1_Embed1) SetDefaults() {
	if x == nil {
		return
	}
}

// Set default value for message Embed2 that in file tests/proto/cases/empty/empty_optional.proto
func (x *MessageOptional1_Embed1_Embed2) SetDefaults() {
	if x == nil {
		return
	}
}

// Set default value for message TypeOptional1 that in file tests/proto/cases/empty/empty_optional.proto
func (x *TypeOptional1) SetDefaults() {
	if x == nil {
		return
	}
	if x.FEnum1 != nil {
		x.FEnum1.SetDefaults()
	}
	if x.FEnum2 != nil {
		x.FEnum2.SetDefaults()
	}
	if x.FMessage11 != nil {
		x.FMessage11.SetDefaults()
	}
	if x.FMessage12 != nil {
		x.FMessage12.SetDefaults()
	}
	if x.FMessage13 != nil {
		x.FMessage13.SetDefaults()
	}
	if x.FMessage14 != nil {
		x.FMessage14.SetDefaults()
	}
	if x.FMessage15 != nil {
		x.FMessage15.SetDefaults()
	}
	if x.FMessage16 != nil {
		x.FMessage16.SetDefaults()
	}
	if x.FMessage17 != nil {
		x.FMessage17.SetDefaults()
	}
	if x.FMessage18 != nil {
		x.FMessage18.SetDefaults()
	}
	if x.FMessage21 != nil {
		x.FMessage21.SetDefaults()
	}
	if x.FMessage22 != nil {
		x.FMessage22.SetDefaults()
	}
	if x.FMessage23 != nil {
		x.FMessage23.SetDefaults()
	}
	if x.FMessage24 != nil {
		x.FMessage24.SetDefaults()
	}
	if x.FMessage25 != nil {
		x.FMessage25.SetDefaults()
	}
	if x.FMessage26 != nil {
		x.FMessage26.SetDefaults()
	}
	if x.FMessage27 != nil {
		x.FMessage27.SetDefaults()
	}
	if x.FMessage28 != nil {
		x.FMessage28.SetDefaults()
	}
}
