// Code generated by protoc-gen-godefault. DO NOT EDIT.
// versions:
// 		protoc-gen-godefault 0.0.1
// source: tests/proto/module/external.proto

package pbexternal

import (
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

// Set default value for message EnumWeek1 that in file tests/proto/module/external.proto
func (x *EnumWeek1) SetDefault() {
	if x == nil {
		return
	}
}

// Set default value for message EnumWeek2 that in file tests/proto/module/external.proto
func (x *EnumWeek2) SetDefault() {
	if x == nil {
		return
	}
}

// Set default value for message Embed1 that in file tests/proto/module/external.proto
func (x *EnumWeek2_Embed1) SetDefault() {
	if x == nil {
		return
	}
}

// Set default value for message External1 that in file tests/proto/module/external.proto
func (x *External1) SetDefault() {
	if x == nil {
		return
	}
	switch o := x.OneOfType1.(type) {
	case *External1_OFloat:
	case *External1_ODouble:
	case *External1_OInt32:
	case *External1_OSint32:
	case *External1_OSfixed32:
	case *External1_OInt64:
	case *External1_OSint64:
	case *External1_OSfixed64:
	case *External1_OUint32:
	case *External1_OUint64:
	case *External1_OFixed32:
	case *External1_OFixed64:
	case *External1_OBool:
	case *External1_OString:
	case *External1_OBytes:
	case *External1_OEnum1:
	case *External1_OEnum2:
	case *External1_OAny:
	case *External1_OTimestamp:
	case *External1_ODuration:
	default:
		_ = o // to avoid unused panic
	}
}

// Set default value for message External2 that in file tests/proto/module/external.proto
func (x *External2) SetDefault() {
	if x == nil {
		return
	}
	if x.P1 != nil {
		x.P1.SetDefault()
	}
	if x.P2 != nil {
		x.P2.SetDefault()
	}
	for _, ri := range x.R1 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, ri := range x.R2 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	for _, mv := range x.M1 {
		if mv != nil {
			mv.SetDefault()
		}
	}
	for _, mv := range x.M2 {
		if mv != nil {
			mv.SetDefault()
		}
	}
}

// Set default value for message Embed1 that in file tests/proto/module/external.proto
func (x *External2_Embed1) SetDefault() {
	if x == nil {
		return
	}
}

// Set default value for message External3 that in file tests/proto/module/external.proto
func (x *External3) SetDefault() {
	if x == nil {
		return
	}
}
