// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: defaults.proto

package pbdefaults

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OneOfOptions is the options for the oneof field.
type OneOfOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of filed in `oneof` part.
	Field *string `protobuf:"bytes,1,opt,name=field,proto3,oneof" json:"field,omitempty"`
}

func (x *OneOfOptions) Reset() {
	*x = OneOfOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_defaults_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneOfOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfOptions) ProtoMessage() {}

func (x *OneOfOptions) ProtoReflect() protoreflect.Message {
	mi := &file_defaults_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfOptions.ProtoReflect.Descriptor instead.
func (*OneOfOptions) Descriptor() ([]byte, []int) {
	return file_defaults_proto_rawDescGZIP(), []int{0}
}

func (x *OneOfOptions) GetField() string {
	if x != nil && x.Field != nil {
		return *x.Field
	}
	return ""
}

// FieldOptions is the options for the `field` level.
type FieldOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Kind:
	//	*FieldOptions_Plain
	//	*FieldOptions_Repeated
	//	*FieldOptions_Map
	Kind isFieldOptions_Kind `protobuf_oneof:"Kind"`
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_defaults_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_defaults_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_defaults_proto_rawDescGZIP(), []int{1}
}

func (m *FieldOptions) GetKind() isFieldOptions_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *FieldOptions) GetPlain() *PlainOptions {
	if x, ok := x.GetKind().(*FieldOptions_Plain); ok {
		return x.Plain
	}
	return nil
}

func (x *FieldOptions) GetRepeated() *RepeatedOptions {
	if x, ok := x.GetKind().(*FieldOptions_Repeated); ok {
		return x.Repeated
	}
	return nil
}

func (x *FieldOptions) GetMap() *MapOptions {
	if x, ok := x.GetKind().(*FieldOptions_Map); ok {
		return x.Map
	}
	return nil
}

type isFieldOptions_Kind interface {
	isFieldOptions_Kind()
}

type FieldOptions_Plain struct {
	// PlainOptions declares the tags applied to the plain field.
	Plain *PlainOptions `protobuf:"bytes,1,opt,name=plain,proto3,oneof"`
}

type FieldOptions_Repeated struct {
	// RepeatedOptions declares the tags applied to the repeated filed.
	Repeated *RepeatedOptions `protobuf:"bytes,2,opt,name=repeated,proto3,oneof"`
}

type FieldOptions_Map struct {
	// MapTags declares the tags applied to the map filed.
	Map *MapOptions `protobuf:"bytes,3,opt,name=map,proto3,oneof"`
}

func (*FieldOptions_Plain) isFieldOptions_Kind() {}

func (*FieldOptions_Repeated) isFieldOptions_Kind() {}

func (*FieldOptions_Map) isFieldOptions_Kind() {}

// PlainOptions declares the options applied to the plain filed.
type PlainOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// value declares the default value for field.
	Value *FieldType `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// By default, For optional field and field type are bytes, the default value will be applied if field value are nil or empty.
	// If the `apply_emtpy` is true, Only apply the default value if the field is a nil pointer.
	IgnoreEmpty *bool `protobuf:"varint,2,opt,name=ignore_empty,json=ignoreEmpty,proto3,oneof" json:"ignore_empty,omitempty"`
	// By default, We will try to eval call the method of defaults for type of field are message and any.
	// If `skip_eval` is true, the method of defaults will not be called.
	// Only effective for language Go.
	SkipEval *bool `protobuf:"varint,11,opt,name=skip_eval,json=skipEval,proto3,oneof" json:"skip_eval,omitempty"`
}

func (x *PlainOptions) Reset() {
	*x = PlainOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_defaults_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlainOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlainOptions) ProtoMessage() {}

func (x *PlainOptions) ProtoReflect() protoreflect.Message {
	mi := &file_defaults_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlainOptions.ProtoReflect.Descriptor instead.
func (*PlainOptions) Descriptor() ([]byte, []int) {
	return file_defaults_proto_rawDescGZIP(), []int{2}
}

func (x *PlainOptions) GetValue() *FieldType {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PlainOptions) GetIgnoreEmpty() bool {
	if x != nil && x.IgnoreEmpty != nil {
		return *x.IgnoreEmpty
	}
	return false
}

func (x *PlainOptions) GetSkipEval() bool {
	if x != nil && x.SkipEval != nil {
		return *x.SkipEval
	}
	return false
}

// RepeatedOptions declares the options applied to the repeated filed.
type RepeatedOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// items declares the default value for field.
	Items []*FieldType `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// By default, The default value will be applied if the length of field is zero.
	// If `ignore_empty` is true, Only apply the default value if the field is a nil pointer.
	// Only effective for language Go.
	IgnoreEmpty *bool `protobuf:"varint,2,opt,name=ignore_empty,json=ignoreEmpty,proto3,oneof" json:"ignore_empty,omitempty"`
	// By default, We will try to eval call the method of defaults for type of repeated items are message and any.
	// If `skip_eval` is true, the method of defaults will not be called.
	// Only effective for language Go.
	SkipEval *bool `protobuf:"varint,11,opt,name=skip_eval,json=skipEval,proto3,oneof" json:"skip_eval,omitempty"`
}

func (x *RepeatedOptions) Reset() {
	*x = RepeatedOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_defaults_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedOptions) ProtoMessage() {}

func (x *RepeatedOptions) ProtoReflect() protoreflect.Message {
	mi := &file_defaults_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedOptions.ProtoReflect.Descriptor instead.
func (*RepeatedOptions) Descriptor() ([]byte, []int) {
	return file_defaults_proto_rawDescGZIP(), []int{3}
}

func (x *RepeatedOptions) GetItems() []*FieldType {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RepeatedOptions) GetIgnoreEmpty() bool {
	if x != nil && x.IgnoreEmpty != nil {
		return *x.IgnoreEmpty
	}
	return false
}

func (x *RepeatedOptions) GetSkipEval() bool {
	if x != nil && x.SkipEval != nil {
		return *x.SkipEval
	}
	return false
}

// MapOptions declares the options applied to the map filed.
type MapOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// kvs declares the the default value for field.
	Kvs []*MapOptions_KV `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty"`
	// By default, The default value will be applied if the length of field is zero.
	// If `ignore_empty` is true, Only apply the default value if the field is a nil pointer.
	// Only effective for language Go.
	IgnoreEmpty *bool `protobuf:"varint,2,opt,name=ignore_empty,json=ignoreEmpty,proto3,oneof" json:"ignore_empty,omitempty"`
	// By default, We will try to eval call the method of defaults for type of map value are message and any.
	// If `skip_eval` is true, the method of defaults will not be called.
	// Only effective for language Go.
	SkipEval *bool `protobuf:"varint,11,opt,name=skip_eval,json=skipEval,proto3,oneof" json:"skip_eval,omitempty"`
}

func (x *MapOptions) Reset() {
	*x = MapOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_defaults_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapOptions) ProtoMessage() {}

func (x *MapOptions) ProtoReflect() protoreflect.Message {
	mi := &file_defaults_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapOptions.ProtoReflect.Descriptor instead.
func (*MapOptions) Descriptor() ([]byte, []int) {
	return file_defaults_proto_rawDescGZIP(), []int{4}
}

func (x *MapOptions) GetKvs() []*MapOptions_KV {
	if x != nil {
		return x.Kvs
	}
	return nil
}

func (x *MapOptions) GetIgnoreEmpty() bool {
	if x != nil && x.IgnoreEmpty != nil {
		return *x.IgnoreEmpty
	}
	return false
}

func (x *MapOptions) GetSkipEval() bool {
	if x != nil && x.SkipEval != nil {
		return *x.SkipEval
	}
	return false
}

type FieldType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Kind:
	//	*FieldType_Int32
	//	*FieldType_Int64
	//	*FieldType_Sint32
	//	*FieldType_Sint64
	//	*FieldType_Sfixed32
	//	*FieldType_Sfixed64
	//	*FieldType_Uint32
	//	*FieldType_Uint64
	//	*FieldType_Fixed32
	//	*FieldType_Fixed64
	//	*FieldType_Float
	//	*FieldType_Double
	//	*FieldType_Bool
	//	*FieldType_Enum
	//	*FieldType_String_
	//	*FieldType_Bytes
	//	*FieldType_Message
	//	*FieldType_Any
	//	*FieldType_Duration
	//	*FieldType_Timestamp
	Kind isFieldType_Kind `protobuf_oneof:"Kind"`
}

func (x *FieldType) Reset() {
	*x = FieldType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_defaults_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldType) ProtoMessage() {}

func (x *FieldType) ProtoReflect() protoreflect.Message {
	mi := &file_defaults_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldType.ProtoReflect.Descriptor instead.
func (*FieldType) Descriptor() ([]byte, []int) {
	return file_defaults_proto_rawDescGZIP(), []int{5}
}

func (m *FieldType) GetKind() isFieldType_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *FieldType) GetInt32() int32 {
	if x, ok := x.GetKind().(*FieldType_Int32); ok {
		return x.Int32
	}
	return 0
}

func (x *FieldType) GetInt64() int64 {
	if x, ok := x.GetKind().(*FieldType_Int64); ok {
		return x.Int64
	}
	return 0
}

func (x *FieldType) GetSint32() int32 {
	if x, ok := x.GetKind().(*FieldType_Sint32); ok {
		return x.Sint32
	}
	return 0
}

func (x *FieldType) GetSint64() int64 {
	if x, ok := x.GetKind().(*FieldType_Sint64); ok {
		return x.Sint64
	}
	return 0
}

func (x *FieldType) GetSfixed32() int32 {
	if x, ok := x.GetKind().(*FieldType_Sfixed32); ok {
		return x.Sfixed32
	}
	return 0
}

func (x *FieldType) GetSfixed64() int64 {
	if x, ok := x.GetKind().(*FieldType_Sfixed64); ok {
		return x.Sfixed64
	}
	return 0
}

func (x *FieldType) GetUint32() uint32 {
	if x, ok := x.GetKind().(*FieldType_Uint32); ok {
		return x.Uint32
	}
	return 0
}

func (x *FieldType) GetUint64() uint64 {
	if x, ok := x.GetKind().(*FieldType_Uint64); ok {
		return x.Uint64
	}
	return 0
}

func (x *FieldType) GetFixed32() uint32 {
	if x, ok := x.GetKind().(*FieldType_Fixed32); ok {
		return x.Fixed32
	}
	return 0
}

func (x *FieldType) GetFixed64() uint64 {
	if x, ok := x.GetKind().(*FieldType_Fixed64); ok {
		return x.Fixed64
	}
	return 0
}

func (x *FieldType) GetFloat() float32 {
	if x, ok := x.GetKind().(*FieldType_Float); ok {
		return x.Float
	}
	return 0
}

func (x *FieldType) GetDouble() float64 {
	if x, ok := x.GetKind().(*FieldType_Double); ok {
		return x.Double
	}
	return 0
}

func (x *FieldType) GetBool() bool {
	if x, ok := x.GetKind().(*FieldType_Bool); ok {
		return x.Bool
	}
	return false
}

func (x *FieldType) GetEnum() int32 {
	if x, ok := x.GetKind().(*FieldType_Enum); ok {
		return x.Enum
	}
	return 0
}

func (x *FieldType) GetString_() string {
	if x, ok := x.GetKind().(*FieldType_String_); ok {
		return x.String_
	}
	return ""
}

func (x *FieldType) GetBytes() []byte {
	if x, ok := x.GetKind().(*FieldType_Bytes); ok {
		return x.Bytes
	}
	return nil
}

func (x *FieldType) GetMessage() *TypeMessage {
	if x, ok := x.GetKind().(*FieldType_Message); ok {
		return x.Message
	}
	return nil
}

func (x *FieldType) GetAny() *TypeAny {
	if x, ok := x.GetKind().(*FieldType_Any); ok {
		return x.Any
	}
	return nil
}

func (x *FieldType) GetDuration() *durationpb.Duration {
	if x, ok := x.GetKind().(*FieldType_Duration); ok {
		return x.Duration
	}
	return nil
}

func (x *FieldType) GetTimestamp() *timestamppb.Timestamp {
	if x, ok := x.GetKind().(*FieldType_Timestamp); ok {
		return x.Timestamp
	}
	return nil
}

type isFieldType_Kind interface {
	isFieldType_Kind()
}

type FieldType_Int32 struct {
	// int32 declares the default value for field type of `int32`.
	Int32 int32 `protobuf:"varint,1,opt,name=int32,proto3,oneof"`
}

type FieldType_Int64 struct {
	// int64 declares the default value for field type of `int64`.
	Int64 int64 `protobuf:"varint,2,opt,name=int64,proto3,oneof"`
}

type FieldType_Sint32 struct {
	// sint32 declares the default value for field type of `sint32`.
	Sint32 int32 `protobuf:"zigzag32,3,opt,name=sint32,proto3,oneof"`
}

type FieldType_Sint64 struct {
	// sint64 declares the default value for field type of `sint64`.
	Sint64 int64 `protobuf:"zigzag64,4,opt,name=sint64,proto3,oneof"`
}

type FieldType_Sfixed32 struct {
	// sfixed32 declares the default value for field type of `sfixed32`.
	Sfixed32 int32 `protobuf:"fixed32,5,opt,name=sfixed32,proto3,oneof"`
}

type FieldType_Sfixed64 struct {
	// sfixed64 declares the default value for field type of `sfixed64`.
	Sfixed64 int64 `protobuf:"fixed64,6,opt,name=sfixed64,proto3,oneof"`
}

type FieldType_Uint32 struct {
	// uint32 declares the default value for field type of `uint32`.
	Uint32 uint32 `protobuf:"varint,7,opt,name=uint32,proto3,oneof"`
}

type FieldType_Uint64 struct {
	// uint64 declares the default value for field type of `uint64`.
	Uint64 uint64 `protobuf:"varint,8,opt,name=uint64,proto3,oneof"`
}

type FieldType_Fixed32 struct {
	// fixed32 declares the default value for field type of `fixed32`.
	Fixed32 uint32 `protobuf:"fixed32,9,opt,name=fixed32,proto3,oneof"`
}

type FieldType_Fixed64 struct {
	// fixed64 declares the default value for field type of `fixed64`.
	Fixed64 uint64 `protobuf:"fixed64,10,opt,name=fixed64,proto3,oneof"`
}

type FieldType_Float struct {
	// float declares the default value for field type of `float`.
	Float float32 `protobuf:"fixed32,11,opt,name=float,proto3,oneof"`
}

type FieldType_Double struct {
	// double declares the default value for field type of `dobule`.
	Double float64 `protobuf:"fixed64,12,opt,name=double,proto3,oneof"`
}

type FieldType_Bool struct {
	// bool declares the default value for field type of `bool`.
	Bool bool `protobuf:"varint,13,opt,name=bool,proto3,oneof"`
}

type FieldType_Enum struct {
	// enum declares the default value for field type of `enum`.
	Enum int32 `protobuf:"varint,14,opt,name=enum,proto3,oneof"`
}

type FieldType_String_ struct {
	// string declares the default value for field type of `string`.
	String_ string `protobuf:"bytes,15,opt,name=string,proto3,oneof"`
}

type FieldType_Bytes struct {
	// bytes declares the default value for field type of `bytes`.
	Bytes []byte `protobuf:"bytes,16,opt,name=bytes,proto3,oneof"`
}

type FieldType_Message struct {
	// message declares the default value for field type of `message`.
	Message *TypeMessage `protobuf:"bytes,17,opt,name=message,proto3,oneof"`
}

type FieldType_Any struct {
	// any declares the default value for field type of `google.protobuf.Any`.
	Any *TypeAny `protobuf:"bytes,21,opt,name=any,proto3,oneof"`
}

type FieldType_Duration struct {
	// duration declares the default value for field type of `google.protobuf.Duration`.
	Duration *durationpb.Duration `protobuf:"bytes,22,opt,name=duration,proto3,oneof"`
}

type FieldType_Timestamp struct {
	// timestamp declares the default value for field type of `google.protobuf.Timestamp`.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=timestamp,proto3,oneof"`
}

func (*FieldType_Int32) isFieldType_Kind() {}

func (*FieldType_Int64) isFieldType_Kind() {}

func (*FieldType_Sint32) isFieldType_Kind() {}

func (*FieldType_Sint64) isFieldType_Kind() {}

func (*FieldType_Sfixed32) isFieldType_Kind() {}

func (*FieldType_Sfixed64) isFieldType_Kind() {}

func (*FieldType_Uint32) isFieldType_Kind() {}

func (*FieldType_Uint64) isFieldType_Kind() {}

func (*FieldType_Fixed32) isFieldType_Kind() {}

func (*FieldType_Fixed64) isFieldType_Kind() {}

func (*FieldType_Float) isFieldType_Kind() {}

func (*FieldType_Double) isFieldType_Kind() {}

func (*FieldType_Bool) isFieldType_Kind() {}

func (*FieldType_Enum) isFieldType_Kind() {}

func (*FieldType_String_) isFieldType_Kind() {}

func (*FieldType_Bytes) isFieldType_Kind() {}

func (*FieldType_Message) isFieldType_Kind() {}

func (*FieldType_Any) isFieldType_Kind() {}

func (*FieldType_Duration) isFieldType_Kind() {}

func (*FieldType_Timestamp) isFieldType_Kind() {}

type TypeMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Init indicates the `message` to empty value if it is nil pointer.
	// Only effective for language Go.
	Init *bool `protobuf:"varint,1,opt,name=init,proto3,oneof" json:"init,omitempty"`
}

func (x *TypeMessage) Reset() {
	*x = TypeMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_defaults_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeMessage) ProtoMessage() {}

func (x *TypeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_defaults_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeMessage.ProtoReflect.Descriptor instead.
func (*TypeMessage) Descriptor() ([]byte, []int) {
	return file_defaults_proto_rawDescGZIP(), []int{6}
}

func (x *TypeMessage) GetInit() bool {
	if x != nil && x.Init != nil {
		return *x.Init
	}
	return false
}

type TypeAny struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The type_url are combines with the import path(excludes suffix .proto) of proto file and the message name.
	// And the entry format like `github.com/yu31/protoc-plugin-defaults/proto/defaults.MapOptions`.
	//
	// You should use the point number connection to the parent message for embedded message.
	// And the entry format like `github.com/yu31/protoc-plugin-defaults/proto/defaults.MapOptions.KV`.
	//
	// You can use `.` represents the import path if the message is location in the current proto file.
	// And the entry format like `.MapOptions.KV`.
	TypeUrl *string `protobuf:"bytes,11,opt,name=type_url,json=typeUrl,proto3,oneof" json:"type_url,omitempty"`
}

func (x *TypeAny) Reset() {
	*x = TypeAny{}
	if protoimpl.UnsafeEnabled {
		mi := &file_defaults_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypeAny) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeAny) ProtoMessage() {}

func (x *TypeAny) ProtoReflect() protoreflect.Message {
	mi := &file_defaults_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeAny.ProtoReflect.Descriptor instead.
func (*TypeAny) Descriptor() ([]byte, []int) {
	return file_defaults_proto_rawDescGZIP(), []int{7}
}

func (x *TypeAny) GetTypeUrl() string {
	if x != nil && x.TypeUrl != nil {
		return *x.TypeUrl
	}
	return ""
}

type MapOptions_KV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *FieldType `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *FieldType `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MapOptions_KV) Reset() {
	*x = MapOptions_KV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_defaults_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapOptions_KV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapOptions_KV) ProtoMessage() {}

func (x *MapOptions_KV) ProtoReflect() protoreflect.Message {
	mi := &file_defaults_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapOptions_KV.ProtoReflect.Descriptor instead.
func (*MapOptions_KV) Descriptor() ([]byte, []int) {
	return file_defaults_proto_rawDescGZIP(), []int{4, 0}
}

func (x *MapOptions_KV) GetKey() *FieldType {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MapOptions_KV) GetValue() *FieldType {
	if x != nil {
		return x.Value
	}
	return nil
}

var file_defaults_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         64020,
		Name:          "defaults.field",
		Tag:           "bytes,64020,opt,name=field",
		Filename:      "defaults.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*OneOfOptions)(nil),
		Field:         64021,
		Name:          "defaults.oneof",
		Tag:           "bytes,64021,opt,name=oneof",
		Filename:      "defaults.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional defaults.FieldOptions field = 64020;
	E_Field = &file_defaults_proto_extTypes[0]
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// optional defaults.OneOfOptions oneof = 64021;
	E_Oneof = &file_defaults_proto_extTypes[1]
)

var File_defaults_proto protoreflect.FileDescriptor

var file_defaults_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a,
	0x0c, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x19, 0x0a,
	0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x22, 0xa9, 0x01, 0x0a, 0x0c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x2e, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x2e, 0x50, 0x6c,
	0x61, 0x69, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x05, 0x70, 0x6c,
	0x61, 0x69, 0x6e, 0x12, 0x37, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73,
	0x2e, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x28, 0x0a, 0x03,
	0x6d, 0x61, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x70, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x48,
	0x00, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x42, 0x06, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x22, 0xa2,
	0x01, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x26, 0x0a, 0x0c, 0x69, 0x67,
	0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x00, 0x52, 0x0b, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x88,
	0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x65, 0x76, 0x61, 0x6c, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x08, 0x73, 0x6b, 0x69, 0x70, 0x45, 0x76, 0x61,
	0x6c, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x65,
	0x76, 0x61, 0x6c, 0x22, 0xa5, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x29, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x73, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x12, 0x26, 0x0a, 0x0c, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0b, 0x69, 0x67, 0x6e, 0x6f,
	0x72, 0x65, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x73, 0x6b,
	0x69, 0x70, 0x5f, 0x65, 0x76, 0x61, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52,
	0x08, 0x73, 0x6b, 0x69, 0x70, 0x45, 0x76, 0x61, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d,
	0x5f, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x0c, 0x0a,
	0x0a, 0x5f, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x65, 0x76, 0x61, 0x6c, 0x22, 0xf8, 0x01, 0x0a, 0x0a,
	0x4d, 0x61, 0x70, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x29, 0x0a, 0x03, 0x6b, 0x76,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x73, 0x2e, 0x4d, 0x61, 0x70, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4b, 0x56,
	0x52, 0x03, 0x6b, 0x76, 0x73, 0x12, 0x26, 0x0a, 0x0c, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0b, 0x69,
	0x67, 0x6e, 0x6f, 0x72, 0x65, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a,
	0x09, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x65, 0x76, 0x61, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x01, 0x52, 0x08, 0x73, 0x6b, 0x69, 0x70, 0x45, 0x76, 0x61, 0x6c, 0x88, 0x01, 0x01, 0x1a,
	0x56, 0x0a, 0x02, 0x4b, 0x56, 0x12, 0x25, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x69, 0x67, 0x6e, 0x6f,
	0x72, 0x65, 0x5f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x73, 0x6b, 0x69,
	0x70, 0x5f, 0x65, 0x76, 0x61, 0x6c, 0x22, 0xfe, 0x04, 0x0a, 0x09, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x16, 0x0a, 0x05,
	0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x05, 0x69,
	0x6e, 0x74, 0x36, 0x34, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x11, 0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x18,
	0x0a, 0x06, 0x73, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x12, 0x48, 0x00,
	0x52, 0x06, 0x73, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x1c, 0x0a, 0x08, 0x73, 0x66, 0x69, 0x78,
	0x65, 0x64, 0x33, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0f, 0x48, 0x00, 0x52, 0x08, 0x73, 0x66,
	0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x12, 0x1c, 0x0a, 0x08, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64,
	0x36, 0x34, 0x18, 0x06, 0x20, 0x01, 0x28, 0x10, 0x48, 0x00, 0x52, 0x08, 0x73, 0x66, 0x69, 0x78,
	0x65, 0x64, 0x36, 0x34, 0x12, 0x18, 0x0a, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x18,
	0x0a, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00,
	0x52, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x1a, 0x0a, 0x07, 0x66, 0x69, 0x78, 0x65,
	0x64, 0x33, 0x32, 0x18, 0x09, 0x20, 0x01, 0x28, 0x07, 0x48, 0x00, 0x52, 0x07, 0x66, 0x69, 0x78,
	0x65, 0x64, 0x33, 0x32, 0x12, 0x1a, 0x0a, 0x07, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x06, 0x48, 0x00, 0x52, 0x07, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34,
	0x12, 0x16, 0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x02, 0x48,
	0x00, 0x52, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x18, 0x0a, 0x06, 0x64, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x06, 0x64, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x00, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x04, 0x65, 0x6e, 0x75, 0x6d,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x12, 0x18,
	0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x12, 0x31, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x2e, 0x54, 0x79, 0x70,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x03, 0x61, 0x6e, 0x79, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x41, 0x6e, 0x79, 0x48, 0x00, 0x52, 0x03, 0x61, 0x6e, 0x79, 0x12, 0x37, 0x0a, 0x08, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x16, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x17, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x48, 0x00, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42,
	0x06, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x22, 0x2f, 0x0a, 0x0b, 0x54, 0x79, 0x70, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x88, 0x01, 0x01, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x69, 0x6e, 0x69, 0x74, 0x22, 0x36, 0x0a, 0x07, 0x54, 0x79, 0x70, 0x65,
	0x41, 0x6e, 0x79, 0x12, 0x1e, 0x0a, 0x08, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x74, 0x79, 0x70, 0x65, 0x55, 0x72, 0x6c,
	0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x75, 0x72, 0x6c,
	0x3a, 0x4d, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x94, 0xf4, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x2e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x3a,
	0x4d, 0x0a, 0x05, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4f, 0x6e, 0x65, 0x6f, 0x66,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x95, 0xf4, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x2e, 0x4f, 0x6e, 0x65, 0x4f, 0x66,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x6d,
	0x0a, 0x23, 0x69, 0x6f, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x79, 0x75, 0x33, 0x31,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x70, 0x62, 0x2e, 0x70, 0x62, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x73, 0x42, 0x0a, 0x50, 0x42, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x73, 0x50, 0x01, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x79, 0x75, 0x33, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x2f, 0x78, 0x67, 0x6f, 0x2f,
	0x70, 0x62, 0x2f, 0x70, 0x62, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_defaults_proto_rawDescOnce sync.Once
	file_defaults_proto_rawDescData = file_defaults_proto_rawDesc
)

func file_defaults_proto_rawDescGZIP() []byte {
	file_defaults_proto_rawDescOnce.Do(func() {
		file_defaults_proto_rawDescData = protoimpl.X.CompressGZIP(file_defaults_proto_rawDescData)
	})
	return file_defaults_proto_rawDescData
}

var file_defaults_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_defaults_proto_goTypes = []interface{}{
	(*OneOfOptions)(nil),              // 0: defaults.OneOfOptions
	(*FieldOptions)(nil),              // 1: defaults.FieldOptions
	(*PlainOptions)(nil),              // 2: defaults.PlainOptions
	(*RepeatedOptions)(nil),           // 3: defaults.RepeatedOptions
	(*MapOptions)(nil),                // 4: defaults.MapOptions
	(*FieldType)(nil),                 // 5: defaults.FieldType
	(*TypeMessage)(nil),               // 6: defaults.TypeMessage
	(*TypeAny)(nil),                   // 7: defaults.TypeAny
	(*MapOptions_KV)(nil),             // 8: defaults.MapOptions.KV
	(*durationpb.Duration)(nil),       // 9: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),     // 10: google.protobuf.Timestamp
	(*descriptorpb.FieldOptions)(nil), // 11: google.protobuf.FieldOptions
	(*descriptorpb.OneofOptions)(nil), // 12: google.protobuf.OneofOptions
}
var file_defaults_proto_depIdxs = []int32{
	2,  // 0: defaults.FieldOptions.plain:type_name -> defaults.PlainOptions
	3,  // 1: defaults.FieldOptions.repeated:type_name -> defaults.RepeatedOptions
	4,  // 2: defaults.FieldOptions.map:type_name -> defaults.MapOptions
	5,  // 3: defaults.PlainOptions.value:type_name -> defaults.FieldType
	5,  // 4: defaults.RepeatedOptions.items:type_name -> defaults.FieldType
	8,  // 5: defaults.MapOptions.kvs:type_name -> defaults.MapOptions.KV
	6,  // 6: defaults.FieldType.message:type_name -> defaults.TypeMessage
	7,  // 7: defaults.FieldType.any:type_name -> defaults.TypeAny
	9,  // 8: defaults.FieldType.duration:type_name -> google.protobuf.Duration
	10, // 9: defaults.FieldType.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 10: defaults.MapOptions.KV.key:type_name -> defaults.FieldType
	5,  // 11: defaults.MapOptions.KV.value:type_name -> defaults.FieldType
	11, // 12: defaults.field:extendee -> google.protobuf.FieldOptions
	12, // 13: defaults.oneof:extendee -> google.protobuf.OneofOptions
	1,  // 14: defaults.field:type_name -> defaults.FieldOptions
	0,  // 15: defaults.oneof:type_name -> defaults.OneOfOptions
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	14, // [14:16] is the sub-list for extension type_name
	12, // [12:14] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_defaults_proto_init() }
func file_defaults_proto_init() {
	if File_defaults_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_defaults_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneOfOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_defaults_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_defaults_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlainOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_defaults_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_defaults_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_defaults_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_defaults_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypeMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_defaults_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypeAny); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_defaults_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapOptions_KV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_defaults_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_defaults_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*FieldOptions_Plain)(nil),
		(*FieldOptions_Repeated)(nil),
		(*FieldOptions_Map)(nil),
	}
	file_defaults_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_defaults_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_defaults_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_defaults_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*FieldType_Int32)(nil),
		(*FieldType_Int64)(nil),
		(*FieldType_Sint32)(nil),
		(*FieldType_Sint64)(nil),
		(*FieldType_Sfixed32)(nil),
		(*FieldType_Sfixed64)(nil),
		(*FieldType_Uint32)(nil),
		(*FieldType_Uint64)(nil),
		(*FieldType_Fixed32)(nil),
		(*FieldType_Fixed64)(nil),
		(*FieldType_Float)(nil),
		(*FieldType_Double)(nil),
		(*FieldType_Bool)(nil),
		(*FieldType_Enum)(nil),
		(*FieldType_String_)(nil),
		(*FieldType_Bytes)(nil),
		(*FieldType_Message)(nil),
		(*FieldType_Any)(nil),
		(*FieldType_Duration)(nil),
		(*FieldType_Timestamp)(nil),
	}
	file_defaults_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_defaults_proto_msgTypes[7].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_defaults_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_defaults_proto_goTypes,
		DependencyIndexes: file_defaults_proto_depIdxs,
		MessageInfos:      file_defaults_proto_msgTypes,
		ExtensionInfos:    file_defaults_proto_extTypes,
	}.Build()
	File_defaults_proto = out.File
	file_defaults_proto_rawDesc = nil
	file_defaults_proto_goTypes = nil
	file_defaults_proto_depIdxs = nil
}
