// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: default.proto

package io.github.yu31.protoc.pb.pbdefault;

public interface FieldOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:default.FieldOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * PlainOptions declares the tags applied to the plain field.
   * </pre>
   *
   * <code>.default.PlainOptions plain = 1;</code>
   * @return Whether the plain field is set.
   */
  boolean hasPlain();
  /**
   * <pre>
   * PlainOptions declares the tags applied to the plain field.
   * </pre>
   *
   * <code>.default.PlainOptions plain = 1;</code>
   * @return The plain.
   */
  io.github.yu31.protoc.pb.pbdefault.PlainOptions getPlain();
  /**
   * <pre>
   * PlainOptions declares the tags applied to the plain field.
   * </pre>
   *
   * <code>.default.PlainOptions plain = 1;</code>
   */
  io.github.yu31.protoc.pb.pbdefault.PlainOptionsOrBuilder getPlainOrBuilder();

  /**
   * <pre>
   * RepeatedOptions declares the tags applied to the repeated filed.
   * </pre>
   *
   * <code>.default.RepeatedOptions repeated = 2;</code>
   * @return Whether the repeated field is set.
   */
  boolean hasRepeated();
  /**
   * <pre>
   * RepeatedOptions declares the tags applied to the repeated filed.
   * </pre>
   *
   * <code>.default.RepeatedOptions repeated = 2;</code>
   * @return The repeated.
   */
  io.github.yu31.protoc.pb.pbdefault.RepeatedOptions getRepeated();
  /**
   * <pre>
   * RepeatedOptions declares the tags applied to the repeated filed.
   * </pre>
   *
   * <code>.default.RepeatedOptions repeated = 2;</code>
   */
  io.github.yu31.protoc.pb.pbdefault.RepeatedOptionsOrBuilder getRepeatedOrBuilder();

  /**
   * <pre>
   * MapTags declares the tags applied to the map filed.
   * </pre>
   *
   * <code>.default.MapOptions map = 3;</code>
   * @return Whether the map field is set.
   */
  boolean hasMap();
  /**
   * <pre>
   * MapTags declares the tags applied to the map filed.
   * </pre>
   *
   * <code>.default.MapOptions map = 3;</code>
   * @return The map.
   */
  io.github.yu31.protoc.pb.pbdefault.MapOptions getMap();
  /**
   * <pre>
   * MapTags declares the tags applied to the map filed.
   * </pre>
   *
   * <code>.default.MapOptions map = 3;</code>
   */
  io.github.yu31.protoc.pb.pbdefault.MapOptionsOrBuilder getMapOrBuilder();

  public io.github.yu31.protoc.pb.pbdefault.FieldOptions.KindCase getKindCase();
}
