// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: default.proto

package io.github.yu31.protoc.pb.pbdefault;

/**
 * Protobuf type {@code default.FieldType}
 */
public final class FieldType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:default.FieldType)
    FieldTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FieldType.newBuilder() to construct.
  private FieldType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FieldType() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FieldType();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FieldType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            kind_ = input.readInt32();
            kindCase_ = 1;
            break;
          }
          case 16: {
            kind_ = input.readInt64();
            kindCase_ = 2;
            break;
          }
          case 24: {
            kind_ = input.readSInt32();
            kindCase_ = 3;
            break;
          }
          case 32: {
            kind_ = input.readSInt64();
            kindCase_ = 4;
            break;
          }
          case 45: {
            kind_ = input.readSFixed32();
            kindCase_ = 5;
            break;
          }
          case 49: {
            kind_ = input.readSFixed64();
            kindCase_ = 6;
            break;
          }
          case 56: {
            kind_ = input.readUInt32();
            kindCase_ = 7;
            break;
          }
          case 64: {
            kind_ = input.readUInt64();
            kindCase_ = 8;
            break;
          }
          case 77: {
            kind_ = input.readFixed32();
            kindCase_ = 9;
            break;
          }
          case 81: {
            kind_ = input.readFixed64();
            kindCase_ = 10;
            break;
          }
          case 93: {
            kind_ = input.readFloat();
            kindCase_ = 11;
            break;
          }
          case 97: {
            kind_ = input.readDouble();
            kindCase_ = 12;
            break;
          }
          case 104: {
            kind_ = input.readBool();
            kindCase_ = 13;
            break;
          }
          case 112: {
            kind_ = input.readInt32();
            kindCase_ = 14;
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();
            kindCase_ = 15;
            kind_ = s;
            break;
          }
          case 130: {
            kind_ = input.readBytes();
            kindCase_ = 16;
            break;
          }
          case 138: {
            io.github.yu31.protoc.pb.pbdefault.TypeMessage.Builder subBuilder = null;
            if (kindCase_ == 17) {
              subBuilder = ((io.github.yu31.protoc.pb.pbdefault.TypeMessage) kind_).toBuilder();
            }
            kind_ =
                input.readMessage(io.github.yu31.protoc.pb.pbdefault.TypeMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.github.yu31.protoc.pb.pbdefault.TypeMessage) kind_);
              kind_ = subBuilder.buildPartial();
            }
            kindCase_ = 17;
            break;
          }
          case 170: {
            io.github.yu31.protoc.pb.pbdefault.TypeAny.Builder subBuilder = null;
            if (kindCase_ == 21) {
              subBuilder = ((io.github.yu31.protoc.pb.pbdefault.TypeAny) kind_).toBuilder();
            }
            kind_ =
                input.readMessage(io.github.yu31.protoc.pb.pbdefault.TypeAny.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.github.yu31.protoc.pb.pbdefault.TypeAny) kind_);
              kind_ = subBuilder.buildPartial();
            }
            kindCase_ = 21;
            break;
          }
          case 178: {
            com.google.protobuf.Duration.Builder subBuilder = null;
            if (kindCase_ == 22) {
              subBuilder = ((com.google.protobuf.Duration) kind_).toBuilder();
            }
            kind_ =
                input.readMessage(com.google.protobuf.Duration.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.google.protobuf.Duration) kind_);
              kind_ = subBuilder.buildPartial();
            }
            kindCase_ = 22;
            break;
          }
          case 186: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (kindCase_ == 23) {
              subBuilder = ((com.google.protobuf.Timestamp) kind_).toBuilder();
            }
            kind_ =
                input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.google.protobuf.Timestamp) kind_);
              kind_ = subBuilder.buildPartial();
            }
            kindCase_ = 23;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.yu31.protoc.pb.pbdefault.PBDefault.internal_static_default_FieldType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.yu31.protoc.pb.pbdefault.PBDefault.internal_static_default_FieldType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.yu31.protoc.pb.pbdefault.FieldType.class, io.github.yu31.protoc.pb.pbdefault.FieldType.Builder.class);
  }

  private int kindCase_ = 0;
  private java.lang.Object kind_;
  public enum KindCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    INT32(1),
    INT64(2),
    SINT32(3),
    SINT64(4),
    SFIXED32(5),
    SFIXED64(6),
    UINT32(7),
    UINT64(8),
    FIXED32(9),
    FIXED64(10),
    FLOAT(11),
    DOUBLE(12),
    BOOL(13),
    ENUM(14),
    STRING(15),
    BYTES(16),
    MESSAGE(17),
    ANY(21),
    DURATION(22),
    TIMESTAMP(23),
    KIND_NOT_SET(0);
    private final int value;
    private KindCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static KindCase valueOf(int value) {
      return forNumber(value);
    }

    public static KindCase forNumber(int value) {
      switch (value) {
        case 1: return INT32;
        case 2: return INT64;
        case 3: return SINT32;
        case 4: return SINT64;
        case 5: return SFIXED32;
        case 6: return SFIXED64;
        case 7: return UINT32;
        case 8: return UINT64;
        case 9: return FIXED32;
        case 10: return FIXED64;
        case 11: return FLOAT;
        case 12: return DOUBLE;
        case 13: return BOOL;
        case 14: return ENUM;
        case 15: return STRING;
        case 16: return BYTES;
        case 17: return MESSAGE;
        case 21: return ANY;
        case 22: return DURATION;
        case 23: return TIMESTAMP;
        case 0: return KIND_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public KindCase
  getKindCase() {
    return KindCase.forNumber(
        kindCase_);
  }

  public static final int INT32_FIELD_NUMBER = 1;
  /**
   * <pre>
   * int32 declares the default value for field type of `int32`.
   * </pre>
   *
   * <code>int32 int32 = 1;</code>
   * @return Whether the int32 field is set.
   */
  @java.lang.Override
  public boolean hasInt32() {
    return kindCase_ == 1;
  }
  /**
   * <pre>
   * int32 declares the default value for field type of `int32`.
   * </pre>
   *
   * <code>int32 int32 = 1;</code>
   * @return The int32.
   */
  @java.lang.Override
  public int getInt32() {
    if (kindCase_ == 1) {
      return (java.lang.Integer) kind_;
    }
    return 0;
  }

  public static final int INT64_FIELD_NUMBER = 2;
  /**
   * <pre>
   * int64 declares the default value for field type of `int64`.
   * </pre>
   *
   * <code>int64 int64 = 2;</code>
   * @return Whether the int64 field is set.
   */
  @java.lang.Override
  public boolean hasInt64() {
    return kindCase_ == 2;
  }
  /**
   * <pre>
   * int64 declares the default value for field type of `int64`.
   * </pre>
   *
   * <code>int64 int64 = 2;</code>
   * @return The int64.
   */
  @java.lang.Override
  public long getInt64() {
    if (kindCase_ == 2) {
      return (java.lang.Long) kind_;
    }
    return 0L;
  }

  public static final int SINT32_FIELD_NUMBER = 3;
  /**
   * <pre>
   * sint32 declares the default value for field type of `sint32`.
   * </pre>
   *
   * <code>sint32 sint32 = 3;</code>
   * @return Whether the sint32 field is set.
   */
  @java.lang.Override
  public boolean hasSint32() {
    return kindCase_ == 3;
  }
  /**
   * <pre>
   * sint32 declares the default value for field type of `sint32`.
   * </pre>
   *
   * <code>sint32 sint32 = 3;</code>
   * @return The sint32.
   */
  @java.lang.Override
  public int getSint32() {
    if (kindCase_ == 3) {
      return (java.lang.Integer) kind_;
    }
    return 0;
  }

  public static final int SINT64_FIELD_NUMBER = 4;
  /**
   * <pre>
   * sint64 declares the default value for field type of `sint64`.
   * </pre>
   *
   * <code>sint64 sint64 = 4;</code>
   * @return Whether the sint64 field is set.
   */
  @java.lang.Override
  public boolean hasSint64() {
    return kindCase_ == 4;
  }
  /**
   * <pre>
   * sint64 declares the default value for field type of `sint64`.
   * </pre>
   *
   * <code>sint64 sint64 = 4;</code>
   * @return The sint64.
   */
  @java.lang.Override
  public long getSint64() {
    if (kindCase_ == 4) {
      return (java.lang.Long) kind_;
    }
    return 0L;
  }

  public static final int SFIXED32_FIELD_NUMBER = 5;
  /**
   * <pre>
   * sfixed32 declares the default value for field type of `sfixed32`.
   * </pre>
   *
   * <code>sfixed32 sfixed32 = 5;</code>
   * @return Whether the sfixed32 field is set.
   */
  @java.lang.Override
  public boolean hasSfixed32() {
    return kindCase_ == 5;
  }
  /**
   * <pre>
   * sfixed32 declares the default value for field type of `sfixed32`.
   * </pre>
   *
   * <code>sfixed32 sfixed32 = 5;</code>
   * @return The sfixed32.
   */
  @java.lang.Override
  public int getSfixed32() {
    if (kindCase_ == 5) {
      return (java.lang.Integer) kind_;
    }
    return 0;
  }

  public static final int SFIXED64_FIELD_NUMBER = 6;
  /**
   * <pre>
   * sfixed64 declares the default value for field type of `sfixed64`.
   * </pre>
   *
   * <code>sfixed64 sfixed64 = 6;</code>
   * @return Whether the sfixed64 field is set.
   */
  @java.lang.Override
  public boolean hasSfixed64() {
    return kindCase_ == 6;
  }
  /**
   * <pre>
   * sfixed64 declares the default value for field type of `sfixed64`.
   * </pre>
   *
   * <code>sfixed64 sfixed64 = 6;</code>
   * @return The sfixed64.
   */
  @java.lang.Override
  public long getSfixed64() {
    if (kindCase_ == 6) {
      return (java.lang.Long) kind_;
    }
    return 0L;
  }

  public static final int UINT32_FIELD_NUMBER = 7;
  /**
   * <pre>
   * uint32 declares the default value for field type of `uint32`.
   * </pre>
   *
   * <code>uint32 uint32 = 7;</code>
   * @return Whether the uint32 field is set.
   */
  @java.lang.Override
  public boolean hasUint32() {
    return kindCase_ == 7;
  }
  /**
   * <pre>
   * uint32 declares the default value for field type of `uint32`.
   * </pre>
   *
   * <code>uint32 uint32 = 7;</code>
   * @return The uint32.
   */
  @java.lang.Override
  public int getUint32() {
    if (kindCase_ == 7) {
      return (java.lang.Integer) kind_;
    }
    return 0;
  }

  public static final int UINT64_FIELD_NUMBER = 8;
  /**
   * <pre>
   * uint64 declares the default value for field type of `uint64`.
   * </pre>
   *
   * <code>uint64 uint64 = 8;</code>
   * @return Whether the uint64 field is set.
   */
  @java.lang.Override
  public boolean hasUint64() {
    return kindCase_ == 8;
  }
  /**
   * <pre>
   * uint64 declares the default value for field type of `uint64`.
   * </pre>
   *
   * <code>uint64 uint64 = 8;</code>
   * @return The uint64.
   */
  @java.lang.Override
  public long getUint64() {
    if (kindCase_ == 8) {
      return (java.lang.Long) kind_;
    }
    return 0L;
  }

  public static final int FIXED32_FIELD_NUMBER = 9;
  /**
   * <pre>
   * fixed32 declares the default value for field type of `fixed32`.
   * </pre>
   *
   * <code>fixed32 fixed32 = 9;</code>
   * @return Whether the fixed32 field is set.
   */
  @java.lang.Override
  public boolean hasFixed32() {
    return kindCase_ == 9;
  }
  /**
   * <pre>
   * fixed32 declares the default value for field type of `fixed32`.
   * </pre>
   *
   * <code>fixed32 fixed32 = 9;</code>
   * @return The fixed32.
   */
  @java.lang.Override
  public int getFixed32() {
    if (kindCase_ == 9) {
      return (java.lang.Integer) kind_;
    }
    return 0;
  }

  public static final int FIXED64_FIELD_NUMBER = 10;
  /**
   * <pre>
   * fixed64 declares the default value for field type of `fixed64`.
   * </pre>
   *
   * <code>fixed64 fixed64 = 10;</code>
   * @return Whether the fixed64 field is set.
   */
  @java.lang.Override
  public boolean hasFixed64() {
    return kindCase_ == 10;
  }
  /**
   * <pre>
   * fixed64 declares the default value for field type of `fixed64`.
   * </pre>
   *
   * <code>fixed64 fixed64 = 10;</code>
   * @return The fixed64.
   */
  @java.lang.Override
  public long getFixed64() {
    if (kindCase_ == 10) {
      return (java.lang.Long) kind_;
    }
    return 0L;
  }

  public static final int FLOAT_FIELD_NUMBER = 11;
  /**
   * <pre>
   * float declares the default value for field type of `float`.
   * </pre>
   *
   * <code>float float = 11;</code>
   * @return Whether the float field is set.
   */
  @java.lang.Override
  public boolean hasFloat() {
    return kindCase_ == 11;
  }
  /**
   * <pre>
   * float declares the default value for field type of `float`.
   * </pre>
   *
   * <code>float float = 11;</code>
   * @return The float.
   */
  @java.lang.Override
  public float getFloat() {
    if (kindCase_ == 11) {
      return (java.lang.Float) kind_;
    }
    return 0F;
  }

  public static final int DOUBLE_FIELD_NUMBER = 12;
  /**
   * <pre>
   * double declares the default value for field type of `dobule`.
   * </pre>
   *
   * <code>double double = 12;</code>
   * @return Whether the double field is set.
   */
  @java.lang.Override
  public boolean hasDouble() {
    return kindCase_ == 12;
  }
  /**
   * <pre>
   * double declares the default value for field type of `dobule`.
   * </pre>
   *
   * <code>double double = 12;</code>
   * @return The double.
   */
  @java.lang.Override
  public double getDouble() {
    if (kindCase_ == 12) {
      return (java.lang.Double) kind_;
    }
    return 0D;
  }

  public static final int BOOL_FIELD_NUMBER = 13;
  /**
   * <pre>
   * bool declares the default value for field type of `bool`.
   * </pre>
   *
   * <code>bool bool = 13;</code>
   * @return Whether the bool field is set.
   */
  @java.lang.Override
  public boolean hasBool() {
    return kindCase_ == 13;
  }
  /**
   * <pre>
   * bool declares the default value for field type of `bool`.
   * </pre>
   *
   * <code>bool bool = 13;</code>
   * @return The bool.
   */
  @java.lang.Override
  public boolean getBool() {
    if (kindCase_ == 13) {
      return (java.lang.Boolean) kind_;
    }
    return false;
  }

  public static final int ENUM_FIELD_NUMBER = 14;
  /**
   * <pre>
   * enum declares the default value for field type of `enum`.
   * </pre>
   *
   * <code>int32 enum = 14;</code>
   * @return Whether the enum field is set.
   */
  @java.lang.Override
  public boolean hasEnum() {
    return kindCase_ == 14;
  }
  /**
   * <pre>
   * enum declares the default value for field type of `enum`.
   * </pre>
   *
   * <code>int32 enum = 14;</code>
   * @return The enum.
   */
  @java.lang.Override
  public int getEnum() {
    if (kindCase_ == 14) {
      return (java.lang.Integer) kind_;
    }
    return 0;
  }

  public static final int STRING_FIELD_NUMBER = 15;
  /**
   * <pre>
   * string declares the default value for field type of `string`.
   * </pre>
   *
   * <code>string string = 15;</code>
   * @return Whether the string field is set.
   */
  public boolean hasString() {
    return kindCase_ == 15;
  }
  /**
   * <pre>
   * string declares the default value for field type of `string`.
   * </pre>
   *
   * <code>string string = 15;</code>
   * @return The string.
   */
  public java.lang.String getString() {
    java.lang.Object ref = "";
    if (kindCase_ == 15) {
      ref = kind_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (kindCase_ == 15) {
        kind_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * string declares the default value for field type of `string`.
   * </pre>
   *
   * <code>string string = 15;</code>
   * @return The bytes for string.
   */
  public com.google.protobuf.ByteString
      getStringBytes() {
    java.lang.Object ref = "";
    if (kindCase_ == 15) {
      ref = kind_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (kindCase_ == 15) {
        kind_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BYTES_FIELD_NUMBER = 16;
  /**
   * <pre>
   * bytes declares the default value for field type of `bytes`.
   * </pre>
   *
   * <code>bytes bytes = 16;</code>
   * @return Whether the bytes field is set.
   */
  @java.lang.Override
  public boolean hasBytes() {
    return kindCase_ == 16;
  }
  /**
   * <pre>
   * bytes declares the default value for field type of `bytes`.
   * </pre>
   *
   * <code>bytes bytes = 16;</code>
   * @return The bytes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBytes() {
    if (kindCase_ == 16) {
      return (com.google.protobuf.ByteString) kind_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  public static final int MESSAGE_FIELD_NUMBER = 17;
  /**
   * <pre>
   * message declares the default value for field type of `message`.
   * </pre>
   *
   * <code>.default.TypeMessage message = 17;</code>
   * @return Whether the message field is set.
   */
  @java.lang.Override
  public boolean hasMessage() {
    return kindCase_ == 17;
  }
  /**
   * <pre>
   * message declares the default value for field type of `message`.
   * </pre>
   *
   * <code>.default.TypeMessage message = 17;</code>
   * @return The message.
   */
  @java.lang.Override
  public io.github.yu31.protoc.pb.pbdefault.TypeMessage getMessage() {
    if (kindCase_ == 17) {
       return (io.github.yu31.protoc.pb.pbdefault.TypeMessage) kind_;
    }
    return io.github.yu31.protoc.pb.pbdefault.TypeMessage.getDefaultInstance();
  }
  /**
   * <pre>
   * message declares the default value for field type of `message`.
   * </pre>
   *
   * <code>.default.TypeMessage message = 17;</code>
   */
  @java.lang.Override
  public io.github.yu31.protoc.pb.pbdefault.TypeMessageOrBuilder getMessageOrBuilder() {
    if (kindCase_ == 17) {
       return (io.github.yu31.protoc.pb.pbdefault.TypeMessage) kind_;
    }
    return io.github.yu31.protoc.pb.pbdefault.TypeMessage.getDefaultInstance();
  }

  public static final int ANY_FIELD_NUMBER = 21;
  /**
   * <pre>
   * any declares the default value for field type of `google.protobuf.Any`.
   * </pre>
   *
   * <code>.default.TypeAny any = 21;</code>
   * @return Whether the any field is set.
   */
  @java.lang.Override
  public boolean hasAny() {
    return kindCase_ == 21;
  }
  /**
   * <pre>
   * any declares the default value for field type of `google.protobuf.Any`.
   * </pre>
   *
   * <code>.default.TypeAny any = 21;</code>
   * @return The any.
   */
  @java.lang.Override
  public io.github.yu31.protoc.pb.pbdefault.TypeAny getAny() {
    if (kindCase_ == 21) {
       return (io.github.yu31.protoc.pb.pbdefault.TypeAny) kind_;
    }
    return io.github.yu31.protoc.pb.pbdefault.TypeAny.getDefaultInstance();
  }
  /**
   * <pre>
   * any declares the default value for field type of `google.protobuf.Any`.
   * </pre>
   *
   * <code>.default.TypeAny any = 21;</code>
   */
  @java.lang.Override
  public io.github.yu31.protoc.pb.pbdefault.TypeAnyOrBuilder getAnyOrBuilder() {
    if (kindCase_ == 21) {
       return (io.github.yu31.protoc.pb.pbdefault.TypeAny) kind_;
    }
    return io.github.yu31.protoc.pb.pbdefault.TypeAny.getDefaultInstance();
  }

  public static final int DURATION_FIELD_NUMBER = 22;
  /**
   * <pre>
   * duration declares the default value for field type of `google.protobuf.Duration`.
   * </pre>
   *
   * <code>.google.protobuf.Duration duration = 22;</code>
   * @return Whether the duration field is set.
   */
  @java.lang.Override
  public boolean hasDuration() {
    return kindCase_ == 22;
  }
  /**
   * <pre>
   * duration declares the default value for field type of `google.protobuf.Duration`.
   * </pre>
   *
   * <code>.google.protobuf.Duration duration = 22;</code>
   * @return The duration.
   */
  @java.lang.Override
  public com.google.protobuf.Duration getDuration() {
    if (kindCase_ == 22) {
       return (com.google.protobuf.Duration) kind_;
    }
    return com.google.protobuf.Duration.getDefaultInstance();
  }
  /**
   * <pre>
   * duration declares the default value for field type of `google.protobuf.Duration`.
   * </pre>
   *
   * <code>.google.protobuf.Duration duration = 22;</code>
   */
  @java.lang.Override
  public com.google.protobuf.DurationOrBuilder getDurationOrBuilder() {
    if (kindCase_ == 22) {
       return (com.google.protobuf.Duration) kind_;
    }
    return com.google.protobuf.Duration.getDefaultInstance();
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 23;
  /**
   * <pre>
   * timestamp declares the default value for field type of `google.protobuf.Timestamp`.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 23;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return kindCase_ == 23;
  }
  /**
   * <pre>
   * timestamp declares the default value for field type of `google.protobuf.Timestamp`.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 23;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestamp() {
    if (kindCase_ == 23) {
       return (com.google.protobuf.Timestamp) kind_;
    }
    return com.google.protobuf.Timestamp.getDefaultInstance();
  }
  /**
   * <pre>
   * timestamp declares the default value for field type of `google.protobuf.Timestamp`.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 23;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    if (kindCase_ == 23) {
       return (com.google.protobuf.Timestamp) kind_;
    }
    return com.google.protobuf.Timestamp.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (kindCase_ == 1) {
      output.writeInt32(
          1, (int)((java.lang.Integer) kind_));
    }
    if (kindCase_ == 2) {
      output.writeInt64(
          2, (long)((java.lang.Long) kind_));
    }
    if (kindCase_ == 3) {
      output.writeSInt32(
          3, (int)((java.lang.Integer) kind_));
    }
    if (kindCase_ == 4) {
      output.writeSInt64(
          4, (long)((java.lang.Long) kind_));
    }
    if (kindCase_ == 5) {
      output.writeSFixed32(
          5, (int)((java.lang.Integer) kind_));
    }
    if (kindCase_ == 6) {
      output.writeSFixed64(
          6, (long)((java.lang.Long) kind_));
    }
    if (kindCase_ == 7) {
      output.writeUInt32(
          7, (int)((java.lang.Integer) kind_));
    }
    if (kindCase_ == 8) {
      output.writeUInt64(
          8, (long)((java.lang.Long) kind_));
    }
    if (kindCase_ == 9) {
      output.writeFixed32(
          9, (int)((java.lang.Integer) kind_));
    }
    if (kindCase_ == 10) {
      output.writeFixed64(
          10, (long)((java.lang.Long) kind_));
    }
    if (kindCase_ == 11) {
      output.writeFloat(
          11, (float)((java.lang.Float) kind_));
    }
    if (kindCase_ == 12) {
      output.writeDouble(
          12, (double)((java.lang.Double) kind_));
    }
    if (kindCase_ == 13) {
      output.writeBool(
          13, (boolean)((java.lang.Boolean) kind_));
    }
    if (kindCase_ == 14) {
      output.writeInt32(
          14, (int)((java.lang.Integer) kind_));
    }
    if (kindCase_ == 15) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, kind_);
    }
    if (kindCase_ == 16) {
      output.writeBytes(
          16, (com.google.protobuf.ByteString) kind_);
    }
    if (kindCase_ == 17) {
      output.writeMessage(17, (io.github.yu31.protoc.pb.pbdefault.TypeMessage) kind_);
    }
    if (kindCase_ == 21) {
      output.writeMessage(21, (io.github.yu31.protoc.pb.pbdefault.TypeAny) kind_);
    }
    if (kindCase_ == 22) {
      output.writeMessage(22, (com.google.protobuf.Duration) kind_);
    }
    if (kindCase_ == 23) {
      output.writeMessage(23, (com.google.protobuf.Timestamp) kind_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (kindCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            1, (int)((java.lang.Integer) kind_));
    }
    if (kindCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(
            2, (long)((java.lang.Long) kind_));
    }
    if (kindCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(
            3, (int)((java.lang.Integer) kind_));
    }
    if (kindCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt64Size(
            4, (long)((java.lang.Long) kind_));
    }
    if (kindCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeSFixed32Size(
            5, (int)((java.lang.Integer) kind_));
    }
    if (kindCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeSFixed64Size(
            6, (long)((java.lang.Long) kind_));
    }
    if (kindCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(
            7, (int)((java.lang.Integer) kind_));
    }
    if (kindCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(
            8, (long)((java.lang.Long) kind_));
    }
    if (kindCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed32Size(
            9, (int)((java.lang.Integer) kind_));
    }
    if (kindCase_ == 10) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(
            10, (long)((java.lang.Long) kind_));
    }
    if (kindCase_ == 11) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(
            11, (float)((java.lang.Float) kind_));
    }
    if (kindCase_ == 12) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(
            12, (double)((java.lang.Double) kind_));
    }
    if (kindCase_ == 13) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            13, (boolean)((java.lang.Boolean) kind_));
    }
    if (kindCase_ == 14) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            14, (int)((java.lang.Integer) kind_));
    }
    if (kindCase_ == 15) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, kind_);
    }
    if (kindCase_ == 16) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            16, (com.google.protobuf.ByteString) kind_);
    }
    if (kindCase_ == 17) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(17, (io.github.yu31.protoc.pb.pbdefault.TypeMessage) kind_);
    }
    if (kindCase_ == 21) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(21, (io.github.yu31.protoc.pb.pbdefault.TypeAny) kind_);
    }
    if (kindCase_ == 22) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(22, (com.google.protobuf.Duration) kind_);
    }
    if (kindCase_ == 23) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(23, (com.google.protobuf.Timestamp) kind_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.yu31.protoc.pb.pbdefault.FieldType)) {
      return super.equals(obj);
    }
    io.github.yu31.protoc.pb.pbdefault.FieldType other = (io.github.yu31.protoc.pb.pbdefault.FieldType) obj;

    if (!getKindCase().equals(other.getKindCase())) return false;
    switch (kindCase_) {
      case 1:
        if (getInt32()
            != other.getInt32()) return false;
        break;
      case 2:
        if (getInt64()
            != other.getInt64()) return false;
        break;
      case 3:
        if (getSint32()
            != other.getSint32()) return false;
        break;
      case 4:
        if (getSint64()
            != other.getSint64()) return false;
        break;
      case 5:
        if (getSfixed32()
            != other.getSfixed32()) return false;
        break;
      case 6:
        if (getSfixed64()
            != other.getSfixed64()) return false;
        break;
      case 7:
        if (getUint32()
            != other.getUint32()) return false;
        break;
      case 8:
        if (getUint64()
            != other.getUint64()) return false;
        break;
      case 9:
        if (getFixed32()
            != other.getFixed32()) return false;
        break;
      case 10:
        if (getFixed64()
            != other.getFixed64()) return false;
        break;
      case 11:
        if (java.lang.Float.floatToIntBits(getFloat())
            != java.lang.Float.floatToIntBits(
                other.getFloat())) return false;
        break;
      case 12:
        if (java.lang.Double.doubleToLongBits(getDouble())
            != java.lang.Double.doubleToLongBits(
                other.getDouble())) return false;
        break;
      case 13:
        if (getBool()
            != other.getBool()) return false;
        break;
      case 14:
        if (getEnum()
            != other.getEnum()) return false;
        break;
      case 15:
        if (!getString()
            .equals(other.getString())) return false;
        break;
      case 16:
        if (!getBytes()
            .equals(other.getBytes())) return false;
        break;
      case 17:
        if (!getMessage()
            .equals(other.getMessage())) return false;
        break;
      case 21:
        if (!getAny()
            .equals(other.getAny())) return false;
        break;
      case 22:
        if (!getDuration()
            .equals(other.getDuration())) return false;
        break;
      case 23:
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (kindCase_) {
      case 1:
        hash = (37 * hash) + INT32_FIELD_NUMBER;
        hash = (53 * hash) + getInt32();
        break;
      case 2:
        hash = (37 * hash) + INT64_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getInt64());
        break;
      case 3:
        hash = (37 * hash) + SINT32_FIELD_NUMBER;
        hash = (53 * hash) + getSint32();
        break;
      case 4:
        hash = (37 * hash) + SINT64_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSint64());
        break;
      case 5:
        hash = (37 * hash) + SFIXED32_FIELD_NUMBER;
        hash = (53 * hash) + getSfixed32();
        break;
      case 6:
        hash = (37 * hash) + SFIXED64_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSfixed64());
        break;
      case 7:
        hash = (37 * hash) + UINT32_FIELD_NUMBER;
        hash = (53 * hash) + getUint32();
        break;
      case 8:
        hash = (37 * hash) + UINT64_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUint64());
        break;
      case 9:
        hash = (37 * hash) + FIXED32_FIELD_NUMBER;
        hash = (53 * hash) + getFixed32();
        break;
      case 10:
        hash = (37 * hash) + FIXED64_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFixed64());
        break;
      case 11:
        hash = (37 * hash) + FLOAT_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getFloat());
        break;
      case 12:
        hash = (37 * hash) + DOUBLE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getDouble()));
        break;
      case 13:
        hash = (37 * hash) + BOOL_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getBool());
        break;
      case 14:
        hash = (37 * hash) + ENUM_FIELD_NUMBER;
        hash = (53 * hash) + getEnum();
        break;
      case 15:
        hash = (37 * hash) + STRING_FIELD_NUMBER;
        hash = (53 * hash) + getString().hashCode();
        break;
      case 16:
        hash = (37 * hash) + BYTES_FIELD_NUMBER;
        hash = (53 * hash) + getBytes().hashCode();
        break;
      case 17:
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
        break;
      case 21:
        hash = (37 * hash) + ANY_FIELD_NUMBER;
        hash = (53 * hash) + getAny().hashCode();
        break;
      case 22:
        hash = (37 * hash) + DURATION_FIELD_NUMBER;
        hash = (53 * hash) + getDuration().hashCode();
        break;
      case 23:
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.yu31.protoc.pb.pbdefault.FieldType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbdefault.FieldType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefault.FieldType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbdefault.FieldType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefault.FieldType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbdefault.FieldType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefault.FieldType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbdefault.FieldType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefault.FieldType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbdefault.FieldType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefault.FieldType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbdefault.FieldType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.yu31.protoc.pb.pbdefault.FieldType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code default.FieldType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:default.FieldType)
      io.github.yu31.protoc.pb.pbdefault.FieldTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.yu31.protoc.pb.pbdefault.PBDefault.internal_static_default_FieldType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.yu31.protoc.pb.pbdefault.PBDefault.internal_static_default_FieldType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.yu31.protoc.pb.pbdefault.FieldType.class, io.github.yu31.protoc.pb.pbdefault.FieldType.Builder.class);
    }

    // Construct using io.github.yu31.protoc.pb.pbdefault.FieldType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      kindCase_ = 0;
      kind_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.yu31.protoc.pb.pbdefault.PBDefault.internal_static_default_FieldType_descriptor;
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefault.FieldType getDefaultInstanceForType() {
      return io.github.yu31.protoc.pb.pbdefault.FieldType.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefault.FieldType build() {
      io.github.yu31.protoc.pb.pbdefault.FieldType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefault.FieldType buildPartial() {
      io.github.yu31.protoc.pb.pbdefault.FieldType result = new io.github.yu31.protoc.pb.pbdefault.FieldType(this);
      if (kindCase_ == 1) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 2) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 3) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 4) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 5) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 6) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 7) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 8) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 9) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 10) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 11) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 12) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 13) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 14) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 15) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 16) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 17) {
        if (messageBuilder_ == null) {
          result.kind_ = kind_;
        } else {
          result.kind_ = messageBuilder_.build();
        }
      }
      if (kindCase_ == 21) {
        if (anyBuilder_ == null) {
          result.kind_ = kind_;
        } else {
          result.kind_ = anyBuilder_.build();
        }
      }
      if (kindCase_ == 22) {
        if (durationBuilder_ == null) {
          result.kind_ = kind_;
        } else {
          result.kind_ = durationBuilder_.build();
        }
      }
      if (kindCase_ == 23) {
        if (timestampBuilder_ == null) {
          result.kind_ = kind_;
        } else {
          result.kind_ = timestampBuilder_.build();
        }
      }
      result.kindCase_ = kindCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.yu31.protoc.pb.pbdefault.FieldType) {
        return mergeFrom((io.github.yu31.protoc.pb.pbdefault.FieldType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.yu31.protoc.pb.pbdefault.FieldType other) {
      if (other == io.github.yu31.protoc.pb.pbdefault.FieldType.getDefaultInstance()) return this;
      switch (other.getKindCase()) {
        case INT32: {
          setInt32(other.getInt32());
          break;
        }
        case INT64: {
          setInt64(other.getInt64());
          break;
        }
        case SINT32: {
          setSint32(other.getSint32());
          break;
        }
        case SINT64: {
          setSint64(other.getSint64());
          break;
        }
        case SFIXED32: {
          setSfixed32(other.getSfixed32());
          break;
        }
        case SFIXED64: {
          setSfixed64(other.getSfixed64());
          break;
        }
        case UINT32: {
          setUint32(other.getUint32());
          break;
        }
        case UINT64: {
          setUint64(other.getUint64());
          break;
        }
        case FIXED32: {
          setFixed32(other.getFixed32());
          break;
        }
        case FIXED64: {
          setFixed64(other.getFixed64());
          break;
        }
        case FLOAT: {
          setFloat(other.getFloat());
          break;
        }
        case DOUBLE: {
          setDouble(other.getDouble());
          break;
        }
        case BOOL: {
          setBool(other.getBool());
          break;
        }
        case ENUM: {
          setEnum(other.getEnum());
          break;
        }
        case STRING: {
          kindCase_ = 15;
          kind_ = other.kind_;
          onChanged();
          break;
        }
        case BYTES: {
          setBytes(other.getBytes());
          break;
        }
        case MESSAGE: {
          mergeMessage(other.getMessage());
          break;
        }
        case ANY: {
          mergeAny(other.getAny());
          break;
        }
        case DURATION: {
          mergeDuration(other.getDuration());
          break;
        }
        case TIMESTAMP: {
          mergeTimestamp(other.getTimestamp());
          break;
        }
        case KIND_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.github.yu31.protoc.pb.pbdefault.FieldType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.github.yu31.protoc.pb.pbdefault.FieldType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int kindCase_ = 0;
    private java.lang.Object kind_;
    public KindCase
        getKindCase() {
      return KindCase.forNumber(
          kindCase_);
    }

    public Builder clearKind() {
      kindCase_ = 0;
      kind_ = null;
      onChanged();
      return this;
    }


    /**
     * <pre>
     * int32 declares the default value for field type of `int32`.
     * </pre>
     *
     * <code>int32 int32 = 1;</code>
     * @return Whether the int32 field is set.
     */
    public boolean hasInt32() {
      return kindCase_ == 1;
    }
    /**
     * <pre>
     * int32 declares the default value for field type of `int32`.
     * </pre>
     *
     * <code>int32 int32 = 1;</code>
     * @return The int32.
     */
    public int getInt32() {
      if (kindCase_ == 1) {
        return (java.lang.Integer) kind_;
      }
      return 0;
    }
    /**
     * <pre>
     * int32 declares the default value for field type of `int32`.
     * </pre>
     *
     * <code>int32 int32 = 1;</code>
     * @param value The int32 to set.
     * @return This builder for chaining.
     */
    public Builder setInt32(int value) {
      kindCase_ = 1;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * int32 declares the default value for field type of `int32`.
     * </pre>
     *
     * <code>int32 int32 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearInt32() {
      if (kindCase_ == 1) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * int64 declares the default value for field type of `int64`.
     * </pre>
     *
     * <code>int64 int64 = 2;</code>
     * @return Whether the int64 field is set.
     */
    public boolean hasInt64() {
      return kindCase_ == 2;
    }
    /**
     * <pre>
     * int64 declares the default value for field type of `int64`.
     * </pre>
     *
     * <code>int64 int64 = 2;</code>
     * @return The int64.
     */
    public long getInt64() {
      if (kindCase_ == 2) {
        return (java.lang.Long) kind_;
      }
      return 0L;
    }
    /**
     * <pre>
     * int64 declares the default value for field type of `int64`.
     * </pre>
     *
     * <code>int64 int64 = 2;</code>
     * @param value The int64 to set.
     * @return This builder for chaining.
     */
    public Builder setInt64(long value) {
      kindCase_ = 2;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * int64 declares the default value for field type of `int64`.
     * </pre>
     *
     * <code>int64 int64 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInt64() {
      if (kindCase_ == 2) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * sint32 declares the default value for field type of `sint32`.
     * </pre>
     *
     * <code>sint32 sint32 = 3;</code>
     * @return Whether the sint32 field is set.
     */
    public boolean hasSint32() {
      return kindCase_ == 3;
    }
    /**
     * <pre>
     * sint32 declares the default value for field type of `sint32`.
     * </pre>
     *
     * <code>sint32 sint32 = 3;</code>
     * @return The sint32.
     */
    public int getSint32() {
      if (kindCase_ == 3) {
        return (java.lang.Integer) kind_;
      }
      return 0;
    }
    /**
     * <pre>
     * sint32 declares the default value for field type of `sint32`.
     * </pre>
     *
     * <code>sint32 sint32 = 3;</code>
     * @param value The sint32 to set.
     * @return This builder for chaining.
     */
    public Builder setSint32(int value) {
      kindCase_ = 3;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * sint32 declares the default value for field type of `sint32`.
     * </pre>
     *
     * <code>sint32 sint32 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSint32() {
      if (kindCase_ == 3) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * sint64 declares the default value for field type of `sint64`.
     * </pre>
     *
     * <code>sint64 sint64 = 4;</code>
     * @return Whether the sint64 field is set.
     */
    public boolean hasSint64() {
      return kindCase_ == 4;
    }
    /**
     * <pre>
     * sint64 declares the default value for field type of `sint64`.
     * </pre>
     *
     * <code>sint64 sint64 = 4;</code>
     * @return The sint64.
     */
    public long getSint64() {
      if (kindCase_ == 4) {
        return (java.lang.Long) kind_;
      }
      return 0L;
    }
    /**
     * <pre>
     * sint64 declares the default value for field type of `sint64`.
     * </pre>
     *
     * <code>sint64 sint64 = 4;</code>
     * @param value The sint64 to set.
     * @return This builder for chaining.
     */
    public Builder setSint64(long value) {
      kindCase_ = 4;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * sint64 declares the default value for field type of `sint64`.
     * </pre>
     *
     * <code>sint64 sint64 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSint64() {
      if (kindCase_ == 4) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * sfixed32 declares the default value for field type of `sfixed32`.
     * </pre>
     *
     * <code>sfixed32 sfixed32 = 5;</code>
     * @return Whether the sfixed32 field is set.
     */
    public boolean hasSfixed32() {
      return kindCase_ == 5;
    }
    /**
     * <pre>
     * sfixed32 declares the default value for field type of `sfixed32`.
     * </pre>
     *
     * <code>sfixed32 sfixed32 = 5;</code>
     * @return The sfixed32.
     */
    public int getSfixed32() {
      if (kindCase_ == 5) {
        return (java.lang.Integer) kind_;
      }
      return 0;
    }
    /**
     * <pre>
     * sfixed32 declares the default value for field type of `sfixed32`.
     * </pre>
     *
     * <code>sfixed32 sfixed32 = 5;</code>
     * @param value The sfixed32 to set.
     * @return This builder for chaining.
     */
    public Builder setSfixed32(int value) {
      kindCase_ = 5;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * sfixed32 declares the default value for field type of `sfixed32`.
     * </pre>
     *
     * <code>sfixed32 sfixed32 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSfixed32() {
      if (kindCase_ == 5) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * sfixed64 declares the default value for field type of `sfixed64`.
     * </pre>
     *
     * <code>sfixed64 sfixed64 = 6;</code>
     * @return Whether the sfixed64 field is set.
     */
    public boolean hasSfixed64() {
      return kindCase_ == 6;
    }
    /**
     * <pre>
     * sfixed64 declares the default value for field type of `sfixed64`.
     * </pre>
     *
     * <code>sfixed64 sfixed64 = 6;</code>
     * @return The sfixed64.
     */
    public long getSfixed64() {
      if (kindCase_ == 6) {
        return (java.lang.Long) kind_;
      }
      return 0L;
    }
    /**
     * <pre>
     * sfixed64 declares the default value for field type of `sfixed64`.
     * </pre>
     *
     * <code>sfixed64 sfixed64 = 6;</code>
     * @param value The sfixed64 to set.
     * @return This builder for chaining.
     */
    public Builder setSfixed64(long value) {
      kindCase_ = 6;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * sfixed64 declares the default value for field type of `sfixed64`.
     * </pre>
     *
     * <code>sfixed64 sfixed64 = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSfixed64() {
      if (kindCase_ == 6) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * uint32 declares the default value for field type of `uint32`.
     * </pre>
     *
     * <code>uint32 uint32 = 7;</code>
     * @return Whether the uint32 field is set.
     */
    public boolean hasUint32() {
      return kindCase_ == 7;
    }
    /**
     * <pre>
     * uint32 declares the default value for field type of `uint32`.
     * </pre>
     *
     * <code>uint32 uint32 = 7;</code>
     * @return The uint32.
     */
    public int getUint32() {
      if (kindCase_ == 7) {
        return (java.lang.Integer) kind_;
      }
      return 0;
    }
    /**
     * <pre>
     * uint32 declares the default value for field type of `uint32`.
     * </pre>
     *
     * <code>uint32 uint32 = 7;</code>
     * @param value The uint32 to set.
     * @return This builder for chaining.
     */
    public Builder setUint32(int value) {
      kindCase_ = 7;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * uint32 declares the default value for field type of `uint32`.
     * </pre>
     *
     * <code>uint32 uint32 = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearUint32() {
      if (kindCase_ == 7) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * uint64 declares the default value for field type of `uint64`.
     * </pre>
     *
     * <code>uint64 uint64 = 8;</code>
     * @return Whether the uint64 field is set.
     */
    public boolean hasUint64() {
      return kindCase_ == 8;
    }
    /**
     * <pre>
     * uint64 declares the default value for field type of `uint64`.
     * </pre>
     *
     * <code>uint64 uint64 = 8;</code>
     * @return The uint64.
     */
    public long getUint64() {
      if (kindCase_ == 8) {
        return (java.lang.Long) kind_;
      }
      return 0L;
    }
    /**
     * <pre>
     * uint64 declares the default value for field type of `uint64`.
     * </pre>
     *
     * <code>uint64 uint64 = 8;</code>
     * @param value The uint64 to set.
     * @return This builder for chaining.
     */
    public Builder setUint64(long value) {
      kindCase_ = 8;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * uint64 declares the default value for field type of `uint64`.
     * </pre>
     *
     * <code>uint64 uint64 = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearUint64() {
      if (kindCase_ == 8) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * fixed32 declares the default value for field type of `fixed32`.
     * </pre>
     *
     * <code>fixed32 fixed32 = 9;</code>
     * @return Whether the fixed32 field is set.
     */
    public boolean hasFixed32() {
      return kindCase_ == 9;
    }
    /**
     * <pre>
     * fixed32 declares the default value for field type of `fixed32`.
     * </pre>
     *
     * <code>fixed32 fixed32 = 9;</code>
     * @return The fixed32.
     */
    public int getFixed32() {
      if (kindCase_ == 9) {
        return (java.lang.Integer) kind_;
      }
      return 0;
    }
    /**
     * <pre>
     * fixed32 declares the default value for field type of `fixed32`.
     * </pre>
     *
     * <code>fixed32 fixed32 = 9;</code>
     * @param value The fixed32 to set.
     * @return This builder for chaining.
     */
    public Builder setFixed32(int value) {
      kindCase_ = 9;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * fixed32 declares the default value for field type of `fixed32`.
     * </pre>
     *
     * <code>fixed32 fixed32 = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearFixed32() {
      if (kindCase_ == 9) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * fixed64 declares the default value for field type of `fixed64`.
     * </pre>
     *
     * <code>fixed64 fixed64 = 10;</code>
     * @return Whether the fixed64 field is set.
     */
    public boolean hasFixed64() {
      return kindCase_ == 10;
    }
    /**
     * <pre>
     * fixed64 declares the default value for field type of `fixed64`.
     * </pre>
     *
     * <code>fixed64 fixed64 = 10;</code>
     * @return The fixed64.
     */
    public long getFixed64() {
      if (kindCase_ == 10) {
        return (java.lang.Long) kind_;
      }
      return 0L;
    }
    /**
     * <pre>
     * fixed64 declares the default value for field type of `fixed64`.
     * </pre>
     *
     * <code>fixed64 fixed64 = 10;</code>
     * @param value The fixed64 to set.
     * @return This builder for chaining.
     */
    public Builder setFixed64(long value) {
      kindCase_ = 10;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * fixed64 declares the default value for field type of `fixed64`.
     * </pre>
     *
     * <code>fixed64 fixed64 = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearFixed64() {
      if (kindCase_ == 10) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * float declares the default value for field type of `float`.
     * </pre>
     *
     * <code>float float = 11;</code>
     * @return Whether the float field is set.
     */
    public boolean hasFloat() {
      return kindCase_ == 11;
    }
    /**
     * <pre>
     * float declares the default value for field type of `float`.
     * </pre>
     *
     * <code>float float = 11;</code>
     * @return The float.
     */
    public float getFloat() {
      if (kindCase_ == 11) {
        return (java.lang.Float) kind_;
      }
      return 0F;
    }
    /**
     * <pre>
     * float declares the default value for field type of `float`.
     * </pre>
     *
     * <code>float float = 11;</code>
     * @param value The float to set.
     * @return This builder for chaining.
     */
    public Builder setFloat(float value) {
      kindCase_ = 11;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * float declares the default value for field type of `float`.
     * </pre>
     *
     * <code>float float = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearFloat() {
      if (kindCase_ == 11) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * double declares the default value for field type of `dobule`.
     * </pre>
     *
     * <code>double double = 12;</code>
     * @return Whether the double field is set.
     */
    public boolean hasDouble() {
      return kindCase_ == 12;
    }
    /**
     * <pre>
     * double declares the default value for field type of `dobule`.
     * </pre>
     *
     * <code>double double = 12;</code>
     * @return The double.
     */
    public double getDouble() {
      if (kindCase_ == 12) {
        return (java.lang.Double) kind_;
      }
      return 0D;
    }
    /**
     * <pre>
     * double declares the default value for field type of `dobule`.
     * </pre>
     *
     * <code>double double = 12;</code>
     * @param value The double to set.
     * @return This builder for chaining.
     */
    public Builder setDouble(double value) {
      kindCase_ = 12;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * double declares the default value for field type of `dobule`.
     * </pre>
     *
     * <code>double double = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearDouble() {
      if (kindCase_ == 12) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * bool declares the default value for field type of `bool`.
     * </pre>
     *
     * <code>bool bool = 13;</code>
     * @return Whether the bool field is set.
     */
    public boolean hasBool() {
      return kindCase_ == 13;
    }
    /**
     * <pre>
     * bool declares the default value for field type of `bool`.
     * </pre>
     *
     * <code>bool bool = 13;</code>
     * @return The bool.
     */
    public boolean getBool() {
      if (kindCase_ == 13) {
        return (java.lang.Boolean) kind_;
      }
      return false;
    }
    /**
     * <pre>
     * bool declares the default value for field type of `bool`.
     * </pre>
     *
     * <code>bool bool = 13;</code>
     * @param value The bool to set.
     * @return This builder for chaining.
     */
    public Builder setBool(boolean value) {
      kindCase_ = 13;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * bool declares the default value for field type of `bool`.
     * </pre>
     *
     * <code>bool bool = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearBool() {
      if (kindCase_ == 13) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * enum declares the default value for field type of `enum`.
     * </pre>
     *
     * <code>int32 enum = 14;</code>
     * @return Whether the enum field is set.
     */
    public boolean hasEnum() {
      return kindCase_ == 14;
    }
    /**
     * <pre>
     * enum declares the default value for field type of `enum`.
     * </pre>
     *
     * <code>int32 enum = 14;</code>
     * @return The enum.
     */
    public int getEnum() {
      if (kindCase_ == 14) {
        return (java.lang.Integer) kind_;
      }
      return 0;
    }
    /**
     * <pre>
     * enum declares the default value for field type of `enum`.
     * </pre>
     *
     * <code>int32 enum = 14;</code>
     * @param value The enum to set.
     * @return This builder for chaining.
     */
    public Builder setEnum(int value) {
      kindCase_ = 14;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * enum declares the default value for field type of `enum`.
     * </pre>
     *
     * <code>int32 enum = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnum() {
      if (kindCase_ == 14) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * string declares the default value for field type of `string`.
     * </pre>
     *
     * <code>string string = 15;</code>
     * @return Whether the string field is set.
     */
    @java.lang.Override
    public boolean hasString() {
      return kindCase_ == 15;
    }
    /**
     * <pre>
     * string declares the default value for field type of `string`.
     * </pre>
     *
     * <code>string string = 15;</code>
     * @return The string.
     */
    @java.lang.Override
    public java.lang.String getString() {
      java.lang.Object ref = "";
      if (kindCase_ == 15) {
        ref = kind_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (kindCase_ == 15) {
          kind_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * string declares the default value for field type of `string`.
     * </pre>
     *
     * <code>string string = 15;</code>
     * @return The bytes for string.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringBytes() {
      java.lang.Object ref = "";
      if (kindCase_ == 15) {
        ref = kind_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (kindCase_ == 15) {
          kind_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * string declares the default value for field type of `string`.
     * </pre>
     *
     * <code>string string = 15;</code>
     * @param value The string to set.
     * @return This builder for chaining.
     */
    public Builder setString(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  kindCase_ = 15;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * string declares the default value for field type of `string`.
     * </pre>
     *
     * <code>string string = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearString() {
      if (kindCase_ == 15) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * string declares the default value for field type of `string`.
     * </pre>
     *
     * <code>string string = 15;</code>
     * @param value The bytes for string to set.
     * @return This builder for chaining.
     */
    public Builder setStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      kindCase_ = 15;
      kind_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * bytes declares the default value for field type of `bytes`.
     * </pre>
     *
     * <code>bytes bytes = 16;</code>
     * @return Whether the bytes field is set.
     */
    public boolean hasBytes() {
      return kindCase_ == 16;
    }
    /**
     * <pre>
     * bytes declares the default value for field type of `bytes`.
     * </pre>
     *
     * <code>bytes bytes = 16;</code>
     * @return The bytes.
     */
    public com.google.protobuf.ByteString getBytes() {
      if (kindCase_ == 16) {
        return (com.google.protobuf.ByteString) kind_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     * bytes declares the default value for field type of `bytes`.
     * </pre>
     *
     * <code>bytes bytes = 16;</code>
     * @param value The bytes to set.
     * @return This builder for chaining.
     */
    public Builder setBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  kindCase_ = 16;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * bytes declares the default value for field type of `bytes`.
     * </pre>
     *
     * <code>bytes bytes = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearBytes() {
      if (kindCase_ == 16) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.github.yu31.protoc.pb.pbdefault.TypeMessage, io.github.yu31.protoc.pb.pbdefault.TypeMessage.Builder, io.github.yu31.protoc.pb.pbdefault.TypeMessageOrBuilder> messageBuilder_;
    /**
     * <pre>
     * message declares the default value for field type of `message`.
     * </pre>
     *
     * <code>.default.TypeMessage message = 17;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return kindCase_ == 17;
    }
    /**
     * <pre>
     * message declares the default value for field type of `message`.
     * </pre>
     *
     * <code>.default.TypeMessage message = 17;</code>
     * @return The message.
     */
    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefault.TypeMessage getMessage() {
      if (messageBuilder_ == null) {
        if (kindCase_ == 17) {
          return (io.github.yu31.protoc.pb.pbdefault.TypeMessage) kind_;
        }
        return io.github.yu31.protoc.pb.pbdefault.TypeMessage.getDefaultInstance();
      } else {
        if (kindCase_ == 17) {
          return messageBuilder_.getMessage();
        }
        return io.github.yu31.protoc.pb.pbdefault.TypeMessage.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * message declares the default value for field type of `message`.
     * </pre>
     *
     * <code>.default.TypeMessage message = 17;</code>
     */
    public Builder setMessage(io.github.yu31.protoc.pb.pbdefault.TypeMessage value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        messageBuilder_.setMessage(value);
      }
      kindCase_ = 17;
      return this;
    }
    /**
     * <pre>
     * message declares the default value for field type of `message`.
     * </pre>
     *
     * <code>.default.TypeMessage message = 17;</code>
     */
    public Builder setMessage(
        io.github.yu31.protoc.pb.pbdefault.TypeMessage.Builder builderForValue) {
      if (messageBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        messageBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 17;
      return this;
    }
    /**
     * <pre>
     * message declares the default value for field type of `message`.
     * </pre>
     *
     * <code>.default.TypeMessage message = 17;</code>
     */
    public Builder mergeMessage(io.github.yu31.protoc.pb.pbdefault.TypeMessage value) {
      if (messageBuilder_ == null) {
        if (kindCase_ == 17 &&
            kind_ != io.github.yu31.protoc.pb.pbdefault.TypeMessage.getDefaultInstance()) {
          kind_ = io.github.yu31.protoc.pb.pbdefault.TypeMessage.newBuilder((io.github.yu31.protoc.pb.pbdefault.TypeMessage) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 17) {
          messageBuilder_.mergeFrom(value);
        }
        messageBuilder_.setMessage(value);
      }
      kindCase_ = 17;
      return this;
    }
    /**
     * <pre>
     * message declares the default value for field type of `message`.
     * </pre>
     *
     * <code>.default.TypeMessage message = 17;</code>
     */
    public Builder clearMessage() {
      if (messageBuilder_ == null) {
        if (kindCase_ == 17) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 17) {
          kindCase_ = 0;
          kind_ = null;
        }
        messageBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * message declares the default value for field type of `message`.
     * </pre>
     *
     * <code>.default.TypeMessage message = 17;</code>
     */
    public io.github.yu31.protoc.pb.pbdefault.TypeMessage.Builder getMessageBuilder() {
      return getMessageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * message declares the default value for field type of `message`.
     * </pre>
     *
     * <code>.default.TypeMessage message = 17;</code>
     */
    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefault.TypeMessageOrBuilder getMessageOrBuilder() {
      if ((kindCase_ == 17) && (messageBuilder_ != null)) {
        return messageBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 17) {
          return (io.github.yu31.protoc.pb.pbdefault.TypeMessage) kind_;
        }
        return io.github.yu31.protoc.pb.pbdefault.TypeMessage.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * message declares the default value for field type of `message`.
     * </pre>
     *
     * <code>.default.TypeMessage message = 17;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.github.yu31.protoc.pb.pbdefault.TypeMessage, io.github.yu31.protoc.pb.pbdefault.TypeMessage.Builder, io.github.yu31.protoc.pb.pbdefault.TypeMessageOrBuilder> 
        getMessageFieldBuilder() {
      if (messageBuilder_ == null) {
        if (!(kindCase_ == 17)) {
          kind_ = io.github.yu31.protoc.pb.pbdefault.TypeMessage.getDefaultInstance();
        }
        messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.github.yu31.protoc.pb.pbdefault.TypeMessage, io.github.yu31.protoc.pb.pbdefault.TypeMessage.Builder, io.github.yu31.protoc.pb.pbdefault.TypeMessageOrBuilder>(
                (io.github.yu31.protoc.pb.pbdefault.TypeMessage) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 17;
      onChanged();;
      return messageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.github.yu31.protoc.pb.pbdefault.TypeAny, io.github.yu31.protoc.pb.pbdefault.TypeAny.Builder, io.github.yu31.protoc.pb.pbdefault.TypeAnyOrBuilder> anyBuilder_;
    /**
     * <pre>
     * any declares the default value for field type of `google.protobuf.Any`.
     * </pre>
     *
     * <code>.default.TypeAny any = 21;</code>
     * @return Whether the any field is set.
     */
    @java.lang.Override
    public boolean hasAny() {
      return kindCase_ == 21;
    }
    /**
     * <pre>
     * any declares the default value for field type of `google.protobuf.Any`.
     * </pre>
     *
     * <code>.default.TypeAny any = 21;</code>
     * @return The any.
     */
    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefault.TypeAny getAny() {
      if (anyBuilder_ == null) {
        if (kindCase_ == 21) {
          return (io.github.yu31.protoc.pb.pbdefault.TypeAny) kind_;
        }
        return io.github.yu31.protoc.pb.pbdefault.TypeAny.getDefaultInstance();
      } else {
        if (kindCase_ == 21) {
          return anyBuilder_.getMessage();
        }
        return io.github.yu31.protoc.pb.pbdefault.TypeAny.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * any declares the default value for field type of `google.protobuf.Any`.
     * </pre>
     *
     * <code>.default.TypeAny any = 21;</code>
     */
    public Builder setAny(io.github.yu31.protoc.pb.pbdefault.TypeAny value) {
      if (anyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        anyBuilder_.setMessage(value);
      }
      kindCase_ = 21;
      return this;
    }
    /**
     * <pre>
     * any declares the default value for field type of `google.protobuf.Any`.
     * </pre>
     *
     * <code>.default.TypeAny any = 21;</code>
     */
    public Builder setAny(
        io.github.yu31.protoc.pb.pbdefault.TypeAny.Builder builderForValue) {
      if (anyBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        anyBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 21;
      return this;
    }
    /**
     * <pre>
     * any declares the default value for field type of `google.protobuf.Any`.
     * </pre>
     *
     * <code>.default.TypeAny any = 21;</code>
     */
    public Builder mergeAny(io.github.yu31.protoc.pb.pbdefault.TypeAny value) {
      if (anyBuilder_ == null) {
        if (kindCase_ == 21 &&
            kind_ != io.github.yu31.protoc.pb.pbdefault.TypeAny.getDefaultInstance()) {
          kind_ = io.github.yu31.protoc.pb.pbdefault.TypeAny.newBuilder((io.github.yu31.protoc.pb.pbdefault.TypeAny) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 21) {
          anyBuilder_.mergeFrom(value);
        }
        anyBuilder_.setMessage(value);
      }
      kindCase_ = 21;
      return this;
    }
    /**
     * <pre>
     * any declares the default value for field type of `google.protobuf.Any`.
     * </pre>
     *
     * <code>.default.TypeAny any = 21;</code>
     */
    public Builder clearAny() {
      if (anyBuilder_ == null) {
        if (kindCase_ == 21) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 21) {
          kindCase_ = 0;
          kind_ = null;
        }
        anyBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * any declares the default value for field type of `google.protobuf.Any`.
     * </pre>
     *
     * <code>.default.TypeAny any = 21;</code>
     */
    public io.github.yu31.protoc.pb.pbdefault.TypeAny.Builder getAnyBuilder() {
      return getAnyFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * any declares the default value for field type of `google.protobuf.Any`.
     * </pre>
     *
     * <code>.default.TypeAny any = 21;</code>
     */
    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefault.TypeAnyOrBuilder getAnyOrBuilder() {
      if ((kindCase_ == 21) && (anyBuilder_ != null)) {
        return anyBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 21) {
          return (io.github.yu31.protoc.pb.pbdefault.TypeAny) kind_;
        }
        return io.github.yu31.protoc.pb.pbdefault.TypeAny.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * any declares the default value for field type of `google.protobuf.Any`.
     * </pre>
     *
     * <code>.default.TypeAny any = 21;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.github.yu31.protoc.pb.pbdefault.TypeAny, io.github.yu31.protoc.pb.pbdefault.TypeAny.Builder, io.github.yu31.protoc.pb.pbdefault.TypeAnyOrBuilder> 
        getAnyFieldBuilder() {
      if (anyBuilder_ == null) {
        if (!(kindCase_ == 21)) {
          kind_ = io.github.yu31.protoc.pb.pbdefault.TypeAny.getDefaultInstance();
        }
        anyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.github.yu31.protoc.pb.pbdefault.TypeAny, io.github.yu31.protoc.pb.pbdefault.TypeAny.Builder, io.github.yu31.protoc.pb.pbdefault.TypeAnyOrBuilder>(
                (io.github.yu31.protoc.pb.pbdefault.TypeAny) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 21;
      onChanged();;
      return anyBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> durationBuilder_;
    /**
     * <pre>
     * duration declares the default value for field type of `google.protobuf.Duration`.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 22;</code>
     * @return Whether the duration field is set.
     */
    @java.lang.Override
    public boolean hasDuration() {
      return kindCase_ == 22;
    }
    /**
     * <pre>
     * duration declares the default value for field type of `google.protobuf.Duration`.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 22;</code>
     * @return The duration.
     */
    @java.lang.Override
    public com.google.protobuf.Duration getDuration() {
      if (durationBuilder_ == null) {
        if (kindCase_ == 22) {
          return (com.google.protobuf.Duration) kind_;
        }
        return com.google.protobuf.Duration.getDefaultInstance();
      } else {
        if (kindCase_ == 22) {
          return durationBuilder_.getMessage();
        }
        return com.google.protobuf.Duration.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * duration declares the default value for field type of `google.protobuf.Duration`.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 22;</code>
     */
    public Builder setDuration(com.google.protobuf.Duration value) {
      if (durationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        durationBuilder_.setMessage(value);
      }
      kindCase_ = 22;
      return this;
    }
    /**
     * <pre>
     * duration declares the default value for field type of `google.protobuf.Duration`.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 22;</code>
     */
    public Builder setDuration(
        com.google.protobuf.Duration.Builder builderForValue) {
      if (durationBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        durationBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 22;
      return this;
    }
    /**
     * <pre>
     * duration declares the default value for field type of `google.protobuf.Duration`.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 22;</code>
     */
    public Builder mergeDuration(com.google.protobuf.Duration value) {
      if (durationBuilder_ == null) {
        if (kindCase_ == 22 &&
            kind_ != com.google.protobuf.Duration.getDefaultInstance()) {
          kind_ = com.google.protobuf.Duration.newBuilder((com.google.protobuf.Duration) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 22) {
          durationBuilder_.mergeFrom(value);
        }
        durationBuilder_.setMessage(value);
      }
      kindCase_ = 22;
      return this;
    }
    /**
     * <pre>
     * duration declares the default value for field type of `google.protobuf.Duration`.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 22;</code>
     */
    public Builder clearDuration() {
      if (durationBuilder_ == null) {
        if (kindCase_ == 22) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 22) {
          kindCase_ = 0;
          kind_ = null;
        }
        durationBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * duration declares the default value for field type of `google.protobuf.Duration`.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 22;</code>
     */
    public com.google.protobuf.Duration.Builder getDurationBuilder() {
      return getDurationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * duration declares the default value for field type of `google.protobuf.Duration`.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 22;</code>
     */
    @java.lang.Override
    public com.google.protobuf.DurationOrBuilder getDurationOrBuilder() {
      if ((kindCase_ == 22) && (durationBuilder_ != null)) {
        return durationBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 22) {
          return (com.google.protobuf.Duration) kind_;
        }
        return com.google.protobuf.Duration.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * duration declares the default value for field type of `google.protobuf.Duration`.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 22;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> 
        getDurationFieldBuilder() {
      if (durationBuilder_ == null) {
        if (!(kindCase_ == 22)) {
          kind_ = com.google.protobuf.Duration.getDefaultInstance();
        }
        durationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder>(
                (com.google.protobuf.Duration) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 22;
      onChanged();;
      return durationBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <pre>
     * timestamp declares the default value for field type of `google.protobuf.Timestamp`.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 23;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return kindCase_ == 23;
    }
    /**
     * <pre>
     * timestamp declares the default value for field type of `google.protobuf.Timestamp`.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 23;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        if (kindCase_ == 23) {
          return (com.google.protobuf.Timestamp) kind_;
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      } else {
        if (kindCase_ == 23) {
          return timestampBuilder_.getMessage();
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * timestamp declares the default value for field type of `google.protobuf.Timestamp`.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 23;</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }
      kindCase_ = 23;
      return this;
    }
    /**
     * <pre>
     * timestamp declares the default value for field type of `google.protobuf.Timestamp`.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 23;</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 23;
      return this;
    }
    /**
     * <pre>
     * timestamp declares the default value for field type of `google.protobuf.Timestamp`.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 23;</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (kindCase_ == 23 &&
            kind_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          kind_ = com.google.protobuf.Timestamp.newBuilder((com.google.protobuf.Timestamp) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 23) {
          timestampBuilder_.mergeFrom(value);
        }
        timestampBuilder_.setMessage(value);
      }
      kindCase_ = 23;
      return this;
    }
    /**
     * <pre>
     * timestamp declares the default value for field type of `google.protobuf.Timestamp`.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 23;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        if (kindCase_ == 23) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 23) {
          kindCase_ = 0;
          kind_ = null;
        }
        timestampBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * timestamp declares the default value for field type of `google.protobuf.Timestamp`.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 23;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * timestamp declares the default value for field type of `google.protobuf.Timestamp`.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 23;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if ((kindCase_ == 23) && (timestampBuilder_ != null)) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 23) {
          return (com.google.protobuf.Timestamp) kind_;
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * timestamp declares the default value for field type of `google.protobuf.Timestamp`.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 23;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        if (!(kindCase_ == 23)) {
          kind_ = com.google.protobuf.Timestamp.getDefaultInstance();
        }
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                (com.google.protobuf.Timestamp) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 23;
      onChanged();;
      return timestampBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:default.FieldType)
  }

  // @@protoc_insertion_point(class_scope:default.FieldType)
  private static final io.github.yu31.protoc.pb.pbdefault.FieldType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.yu31.protoc.pb.pbdefault.FieldType();
  }

  public static io.github.yu31.protoc.pb.pbdefault.FieldType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FieldType>
      PARSER = new com.google.protobuf.AbstractParser<FieldType>() {
    @java.lang.Override
    public FieldType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FieldType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FieldType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FieldType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.yu31.protoc.pb.pbdefault.FieldType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

