// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: default.proto

package io.github.yu31.protoc.pb.pbdefault;

public interface FieldTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:default.FieldType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * int32 declares the default value for field type of `int32`.
   * </pre>
   *
   * <code>int32 int32 = 1;</code>
   * @return Whether the int32 field is set.
   */
  boolean hasInt32();
  /**
   * <pre>
   * int32 declares the default value for field type of `int32`.
   * </pre>
   *
   * <code>int32 int32 = 1;</code>
   * @return The int32.
   */
  int getInt32();

  /**
   * <pre>
   * int64 declares the default value for field type of `int64`.
   * </pre>
   *
   * <code>int64 int64 = 2;</code>
   * @return Whether the int64 field is set.
   */
  boolean hasInt64();
  /**
   * <pre>
   * int64 declares the default value for field type of `int64`.
   * </pre>
   *
   * <code>int64 int64 = 2;</code>
   * @return The int64.
   */
  long getInt64();

  /**
   * <pre>
   * sint32 declares the default value for field type of `sint32`.
   * </pre>
   *
   * <code>sint32 sint32 = 3;</code>
   * @return Whether the sint32 field is set.
   */
  boolean hasSint32();
  /**
   * <pre>
   * sint32 declares the default value for field type of `sint32`.
   * </pre>
   *
   * <code>sint32 sint32 = 3;</code>
   * @return The sint32.
   */
  int getSint32();

  /**
   * <pre>
   * sint64 declares the default value for field type of `sint64`.
   * </pre>
   *
   * <code>sint64 sint64 = 4;</code>
   * @return Whether the sint64 field is set.
   */
  boolean hasSint64();
  /**
   * <pre>
   * sint64 declares the default value for field type of `sint64`.
   * </pre>
   *
   * <code>sint64 sint64 = 4;</code>
   * @return The sint64.
   */
  long getSint64();

  /**
   * <pre>
   * sfixed32 declares the default value for field type of `sfixed32`.
   * </pre>
   *
   * <code>sfixed32 sfixed32 = 5;</code>
   * @return Whether the sfixed32 field is set.
   */
  boolean hasSfixed32();
  /**
   * <pre>
   * sfixed32 declares the default value for field type of `sfixed32`.
   * </pre>
   *
   * <code>sfixed32 sfixed32 = 5;</code>
   * @return The sfixed32.
   */
  int getSfixed32();

  /**
   * <pre>
   * sfixed64 declares the default value for field type of `sfixed64`.
   * </pre>
   *
   * <code>sfixed64 sfixed64 = 6;</code>
   * @return Whether the sfixed64 field is set.
   */
  boolean hasSfixed64();
  /**
   * <pre>
   * sfixed64 declares the default value for field type of `sfixed64`.
   * </pre>
   *
   * <code>sfixed64 sfixed64 = 6;</code>
   * @return The sfixed64.
   */
  long getSfixed64();

  /**
   * <pre>
   * uint32 declares the default value for field type of `uint32`.
   * </pre>
   *
   * <code>uint32 uint32 = 7;</code>
   * @return Whether the uint32 field is set.
   */
  boolean hasUint32();
  /**
   * <pre>
   * uint32 declares the default value for field type of `uint32`.
   * </pre>
   *
   * <code>uint32 uint32 = 7;</code>
   * @return The uint32.
   */
  int getUint32();

  /**
   * <pre>
   * uint64 declares the default value for field type of `uint64`.
   * </pre>
   *
   * <code>uint64 uint64 = 8;</code>
   * @return Whether the uint64 field is set.
   */
  boolean hasUint64();
  /**
   * <pre>
   * uint64 declares the default value for field type of `uint64`.
   * </pre>
   *
   * <code>uint64 uint64 = 8;</code>
   * @return The uint64.
   */
  long getUint64();

  /**
   * <pre>
   * fixed32 declares the default value for field type of `fixed32`.
   * </pre>
   *
   * <code>fixed32 fixed32 = 9;</code>
   * @return Whether the fixed32 field is set.
   */
  boolean hasFixed32();
  /**
   * <pre>
   * fixed32 declares the default value for field type of `fixed32`.
   * </pre>
   *
   * <code>fixed32 fixed32 = 9;</code>
   * @return The fixed32.
   */
  int getFixed32();

  /**
   * <pre>
   * fixed64 declares the default value for field type of `fixed64`.
   * </pre>
   *
   * <code>fixed64 fixed64 = 10;</code>
   * @return Whether the fixed64 field is set.
   */
  boolean hasFixed64();
  /**
   * <pre>
   * fixed64 declares the default value for field type of `fixed64`.
   * </pre>
   *
   * <code>fixed64 fixed64 = 10;</code>
   * @return The fixed64.
   */
  long getFixed64();

  /**
   * <pre>
   * float declares the default value for field type of `float`.
   * </pre>
   *
   * <code>float float = 11;</code>
   * @return Whether the float field is set.
   */
  boolean hasFloat();
  /**
   * <pre>
   * float declares the default value for field type of `float`.
   * </pre>
   *
   * <code>float float = 11;</code>
   * @return The float.
   */
  float getFloat();

  /**
   * <pre>
   * double declares the default value for field type of `dobule`.
   * </pre>
   *
   * <code>double double = 12;</code>
   * @return Whether the double field is set.
   */
  boolean hasDouble();
  /**
   * <pre>
   * double declares the default value for field type of `dobule`.
   * </pre>
   *
   * <code>double double = 12;</code>
   * @return The double.
   */
  double getDouble();

  /**
   * <pre>
   * bool declares the default value for field type of `bool`.
   * </pre>
   *
   * <code>bool bool = 13;</code>
   * @return Whether the bool field is set.
   */
  boolean hasBool();
  /**
   * <pre>
   * bool declares the default value for field type of `bool`.
   * </pre>
   *
   * <code>bool bool = 13;</code>
   * @return The bool.
   */
  boolean getBool();

  /**
   * <pre>
   * enum declares the default value for field type of `enum`.
   * </pre>
   *
   * <code>int32 enum = 14;</code>
   * @return Whether the enum field is set.
   */
  boolean hasEnum();
  /**
   * <pre>
   * enum declares the default value for field type of `enum`.
   * </pre>
   *
   * <code>int32 enum = 14;</code>
   * @return The enum.
   */
  int getEnum();

  /**
   * <pre>
   * string declares the default value for field type of `string`.
   * </pre>
   *
   * <code>string string = 15;</code>
   * @return Whether the string field is set.
   */
  boolean hasString();
  /**
   * <pre>
   * string declares the default value for field type of `string`.
   * </pre>
   *
   * <code>string string = 15;</code>
   * @return The string.
   */
  java.lang.String getString();
  /**
   * <pre>
   * string declares the default value for field type of `string`.
   * </pre>
   *
   * <code>string string = 15;</code>
   * @return The bytes for string.
   */
  com.google.protobuf.ByteString
      getStringBytes();

  /**
   * <pre>
   * bytes declares the default value for field type of `bytes`.
   * </pre>
   *
   * <code>bytes bytes = 16;</code>
   * @return Whether the bytes field is set.
   */
  boolean hasBytes();
  /**
   * <pre>
   * bytes declares the default value for field type of `bytes`.
   * </pre>
   *
   * <code>bytes bytes = 16;</code>
   * @return The bytes.
   */
  com.google.protobuf.ByteString getBytes();

  /**
   * <pre>
   * message declares the default value for field type of `message`.
   * </pre>
   *
   * <code>.default.TypeMessage message = 17;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <pre>
   * message declares the default value for field type of `message`.
   * </pre>
   *
   * <code>.default.TypeMessage message = 17;</code>
   * @return The message.
   */
  io.github.yu31.protoc.pb.pbdefault.TypeMessage getMessage();
  /**
   * <pre>
   * message declares the default value for field type of `message`.
   * </pre>
   *
   * <code>.default.TypeMessage message = 17;</code>
   */
  io.github.yu31.protoc.pb.pbdefault.TypeMessageOrBuilder getMessageOrBuilder();

  /**
   * <pre>
   * any declares the default value for field type of `google.protobuf.Any`.
   * </pre>
   *
   * <code>.default.TypeAny any = 21;</code>
   * @return Whether the any field is set.
   */
  boolean hasAny();
  /**
   * <pre>
   * any declares the default value for field type of `google.protobuf.Any`.
   * </pre>
   *
   * <code>.default.TypeAny any = 21;</code>
   * @return The any.
   */
  io.github.yu31.protoc.pb.pbdefault.TypeAny getAny();
  /**
   * <pre>
   * any declares the default value for field type of `google.protobuf.Any`.
   * </pre>
   *
   * <code>.default.TypeAny any = 21;</code>
   */
  io.github.yu31.protoc.pb.pbdefault.TypeAnyOrBuilder getAnyOrBuilder();

  /**
   * <pre>
   * duration declares the default value for field type of `google.protobuf.Duration`.
   * </pre>
   *
   * <code>.google.protobuf.Duration duration = 22;</code>
   * @return Whether the duration field is set.
   */
  boolean hasDuration();
  /**
   * <pre>
   * duration declares the default value for field type of `google.protobuf.Duration`.
   * </pre>
   *
   * <code>.google.protobuf.Duration duration = 22;</code>
   * @return The duration.
   */
  com.google.protobuf.Duration getDuration();
  /**
   * <pre>
   * duration declares the default value for field type of `google.protobuf.Duration`.
   * </pre>
   *
   * <code>.google.protobuf.Duration duration = 22;</code>
   */
  com.google.protobuf.DurationOrBuilder getDurationOrBuilder();

  /**
   * <pre>
   * timestamp declares the default value for field type of `google.protobuf.Timestamp`.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 23;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <pre>
   * timestamp declares the default value for field type of `google.protobuf.Timestamp`.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 23;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <pre>
   * timestamp declares the default value for field type of `google.protobuf.Timestamp`.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 23;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  public io.github.yu31.protoc.pb.pbdefault.FieldType.KindCase getKindCase();
}
