// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: default.proto

package io.github.yu31.protoc.pb.pbdefault;

public interface TypeAnyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:default.TypeAny)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The type_url are combines with the import path(excludes suffix .proto) of proto file and the message name.
   * And the entry format like `github.com/yu31/protoc-plugin-default/proto/default.MapOptions`.
   * You should use the point number connection to the parent message for embedded message.
   * And the entry format like `github.com/yu31/protoc-plugin-default/proto/default.MapOptions.KV`.
   * You can use `.` represents the import path if the message is location in the current proto file.
   * And the entry format like `.MapOptions.KV`.
   * </pre>
   *
   * <code>optional string type_url = 11;</code>
   * @return Whether the typeUrl field is set.
   */
  boolean hasTypeUrl();
  /**
   * <pre>
   * The type_url are combines with the import path(excludes suffix .proto) of proto file and the message name.
   * And the entry format like `github.com/yu31/protoc-plugin-default/proto/default.MapOptions`.
   * You should use the point number connection to the parent message for embedded message.
   * And the entry format like `github.com/yu31/protoc-plugin-default/proto/default.MapOptions.KV`.
   * You can use `.` represents the import path if the message is location in the current proto file.
   * And the entry format like `.MapOptions.KV`.
   * </pre>
   *
   * <code>optional string type_url = 11;</code>
   * @return The typeUrl.
   */
  java.lang.String getTypeUrl();
  /**
   * <pre>
   * The type_url are combines with the import path(excludes suffix .proto) of proto file and the message name.
   * And the entry format like `github.com/yu31/protoc-plugin-default/proto/default.MapOptions`.
   * You should use the point number connection to the parent message for embedded message.
   * And the entry format like `github.com/yu31/protoc-plugin-default/proto/default.MapOptions.KV`.
   * You can use `.` represents the import path if the message is location in the current proto file.
   * And the entry format like `.MapOptions.KV`.
   * </pre>
   *
   * <code>optional string type_url = 11;</code>
   * @return The bytes for typeUrl.
   */
  com.google.protobuf.ByteString
      getTypeUrlBytes();
}
