// Code generated by protoc-gen-godefaults. DO NOT EDIT.
// versions:
// 		protoc-gen-godefaults 0.0.1
// source: tests/proto/cases/types/type_plain.proto

package pbtypes

import (
	_ "github.com/yu31/protoc-plugin-defaults/xgo/pb/pbdefaults"
	pbexternal "github.com/yu31/protoc-plugin-defaults/xgo/tests/pb/pbexternal"
	proto "google.golang.org/protobuf/proto"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// Set default value for message MessagePlain1 that in file tests/proto/cases/types/type_plain.proto
func (x *MessagePlain1) SetDefaults() {
	if x == nil {
		return
	}
	if x.FString1 == "" {
		x.FString1 = "a"
	}
	if x.FString2 == "" {
		x.FString2 = "b"
	}
	if x.FString3 == "" {
		x.FString3 = "c"
	}
}

// Set default value for message Embed1 that in file tests/proto/cases/types/type_plain.proto
func (x *MessagePlain1_Embed1) SetDefaults() {
	if x == nil {
		return
	}
	if x.FString1 == "" {
		x.FString1 = "x"
	}
	if x.FString2 == "" {
		x.FString2 = "y"
	}
	if x.FString3 == "" {
		x.FString3 = "z"
	}
}

// Set default value for message Embed2 that in file tests/proto/cases/types/type_plain.proto
func (x *MessagePlain1_Embed1_Embed2) SetDefaults() {
	if x == nil {
		return
	}
	if x.FString1 == "" {
		x.FString1 = "1"
	}
	if x.FString2 == "" {
		x.FString2 = "2"
	}
	if x.FString3 == "" {
		x.FString3 = "3"
	}
}

// Set default value for message TypePlain1 that in file tests/proto/cases/types/type_plain.proto
func (x *TypePlain1) SetDefaults() {
	if x == nil {
		return
	}
	if x.FString1 == "" {
		x.FString1 = "ts1"
	}
	if x.FString2 == "" {
		x.FString2 = ""
	}
	if x.FString3 == "" {
		x.FString3 = "\"\""
	}
	if x.FString4 == "" {
		x.FString4 = "\"ts4\""
	}
	if x.FString5 == "" {
		x.FString5 = "\"ts5\""
	}
	if x.FString6 == "" {
		x.FString6 = "\"ts\"6\""
	}
	if x.FString7 == "" {
		x.FString7 = "\"ts\"7\""
	}
	if x.FString8 == "" {
		x.FString8 = "[ts8]"
	}
	if x.FString9 == "" {
		x.FString9 = "{ts9}"
	}
	if x.FInt32 == 0 {
		x.FInt32 = 1
	}
	if x.FInt64 == 0 {
		x.FInt64 = 2
	}
	if x.FUint32 == 0 {
		x.FUint32 = 3
	}
	if x.FUint64 == 0 {
		x.FUint64 = 4
	}
	if x.FSint32 == 0 {
		x.FSint32 = 5
	}
	if x.FSint64 == 0 {
		x.FSint64 = 6
	}
	if x.FSfixed32 == 0 {
		x.FSfixed32 = 7
	}
	if x.FSfixed64 == 0 {
		x.FSfixed64 = 8
	}
	if x.FFixed32 == 0 {
		x.FFixed32 = 9
	}
	if x.FFixed64 == 0 {
		x.FFixed64 = 10
	}
	if x.FFloat == 0 {
		x.FFloat = 11.109999656677246
	}
	if x.FDouble == 0 {
		x.FDouble = 12.12
	}
	if x.FBool1 == false {
		x.FBool1 = true
	}
	if x.FBool2 == false {
		x.FBool2 = false
	}
	if len(x.FBytes1) == 0 {
		x.FBytes1 = []byte{}
	}
	if len(x.FBytes2) == 0 {
		x.FBytes2 = []byte{97, 98, 99}
	}
	if x.FEnum1 == 0 {
		x.FEnum1 = 2
	}
	if x.FEnum2 == 0 {
		x.FEnum2 = 10
	}
	if x.FEnum3 == 0 {
		x.FEnum3 = 1
	}
	if x.FEnum4 == 0 {
		x.FEnum4 = 7
	}
	if x.FEnum5 == 0 {
		x.FEnum5 = 3
	}
	if x.FEnum6 == 0 {
		x.FEnum6 = 13
	}
	if x.FEnum7 == 0 {
		x.FEnum7 = 9
	}
	if x.FDuration1.AsDuration() == 0 {
		x.FDuration1 = &durationpb.Duration{Seconds: 100, Nanos: 200}
	}
	if x.FDuration2.AsDuration() == 0 {
		x.FDuration2 = &durationpb.Duration{Seconds: 0, Nanos: 0}
	}
	if x.FTimestamp1.AsTime().UnixNano() == 0 {
		x.FTimestamp1 = &timestamppb.Timestamp{Seconds: 200, Nanos: 300}
	}
	if x.FTimestamp2.AsTime().UnixNano() == 0 {
		x.FTimestamp2 = &timestamppb.Timestamp{Seconds: 0, Nanos: 0}
	}
	if x.FMessage11 == nil {
		x.FMessage11 = &MessagePlain1{}
	}
	if x.FMessage11 != nil {
		x.FMessage11.SetDefaults()
	}
	if x.FMessage12 == nil {
		x.FMessage12 = &MessagePlain1_Embed1{}
	}
	if x.FMessage13 == nil {
		x.FMessage13 = &MessagePlain1_Embed1_Embed2{}
	}
	if x.FMessage13 != nil {
		x.FMessage13.SetDefaults()
	}
	if x.FMessage14 == nil {
		x.FMessage14 = &pbexternal.External1{}
	}
	if x.FMessage15 == nil {
		x.FMessage15 = &pbexternal.External2_Embed1{}
	}
	if x.FMessage15 != nil {
		x.FMessage15.SetDefaults()
	}
	if x.FMessage16 == nil {
		x.FMessage16 = &MessageCommon1{}
	}
	if x.FMessage17 == nil {
		x.FMessage17 = &MessageCommon1_Embed1{}
	}
	if x.FMessage17 != nil {
		x.FMessage17.SetDefaults()
	}
	if x.FMessage18 == nil {
		x.FMessage18 = &MessageCommon1_Embed1_Embed2{}
	}
	if x.FMessage21 != nil {
		x.FMessage21.SetDefaults()
	}
	if x.FMessage23 != nil {
		x.FMessage23.SetDefaults()
	}
	if x.FMessage25 != nil {
		x.FMessage25.SetDefaults()
	}
	if x.FMessage27 != nil {
		x.FMessage27.SetDefaults()
	}
	if x.FAny1.GetTypeUrl() == "" {
		x.FAny1 = x.xxxPGD_mustNewAny(&MessagePlain1{}, false)
	}
	if x.FAny2.GetTypeUrl() == "" {
		x.FAny2 = x.xxxPGD_mustNewAny(&MessagePlain1{}, true)
	}
	if x.FAny3.GetTypeUrl() == "" {
		x.FAny3 = x.xxxPGD_mustNewAny(&MessagePlain1_Embed1{}, true)
	}
	if x.FAny4.GetTypeUrl() == "" {
		x.FAny4 = x.xxxPGD_mustNewAny(&MessagePlain1_Embed1_Embed2{}, false)
	}
	if x.FAny5.GetTypeUrl() == "" {
		x.FAny5 = x.xxxPGD_mustNewAny(&pbexternal.External1{}, true)
	}
	if x.FAny6.GetTypeUrl() == "" {
		x.FAny6 = x.xxxPGD_mustNewAny(&pbexternal.External2_Embed1{}, false)
	}
	if x.FAny7.GetTypeUrl() == "" {
		x.FAny7 = x.xxxPGD_mustNewAny(&timestamppb.Timestamp{}, false)
	}
	if x.FAny8.GetTypeUrl() == "" {
		x.FAny8 = x.xxxPGD_mustNewAny(&anypb.Any{}, false)
	}
	if x.FAny9.GetTypeUrl() == "" {
		x.FAny9 = x.xxxPGD_mustNewAny(&MessageCommon1{}, false)
	}
}

// xxxPGD_mustNewAny used to create instance of type any
func (*TypePlain1) xxxPGD_mustNewAny(src proto.Message, skipEval bool) *anypb.Any {
	if !skipEval {
		if dt, ok := interface{}(src).(interface{ SetDefaults() }); ok {
			dt.SetDefaults()
		}
	}
	v, err := anypb.New(src)
	if err != nil {
		panic(err)
	}
	return v
}
