// Code generated by protoc-gen-godefault. DO NOT EDIT.
// versions:
// 		protoc-gen-godefault 0.0.1
// source: tests/proto/cases/types/type_optional.proto

package pbtypes

import (
	_ "github.com/yu31/protoc-plugin-default/xgo/pb/pbdefault"
	pbexternal "github.com/yu31/protoc-plugin-default/xgo/tests/pb/pbexternal"
	proto "google.golang.org/protobuf/proto"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// Set default value for message MessageOptional1 that in file tests/proto/cases/types/type_optional.proto
func (x *MessageOptional1) SetDefault() {
	if x == nil {
		return
	}
	if x.FString1 == "" {
		x.FString1 = "a"
	}
	if x.FString2 == "" {
		x.FString2 = "b"
	}
	if x.FString3 == "" {
		x.FString3 = "c"
	}
}

// Set default value for message Embed1 that in file tests/proto/cases/types/type_optional.proto
func (x *MessageOptional1_Embed1) SetDefault() {
	if x == nil {
		return
	}
	if x.FString1 == "" {
		x.FString1 = "x"
	}
	if x.FString2 == "" {
		x.FString2 = "y"
	}
	if x.FString3 == "" {
		x.FString3 = "z"
	}
}

// Set default value for message Embed2 that in file tests/proto/cases/types/type_optional.proto
func (x *MessageOptional1_Embed1_Embed2) SetDefault() {
	if x == nil {
		return
	}
	if x.FString1 == "" {
		x.FString1 = "1"
	}
	if x.FString2 == "" {
		x.FString2 = "2"
	}
	if x.FString3 == "" {
		x.FString3 = "3"
	}
}

// Set default value for message TypeOptional1 that in file tests/proto/cases/types/type_optional.proto
func (x *TypeOptional1) SetDefault() {
	if x == nil {
		return
	}
	if x.FString1 == nil || *x.FString1 == "" {
		v := string("ts1")
		x.FString1 = &v
	}
	if x.FString2 == nil || *x.FString2 == "" {
		v := string("")
		x.FString2 = &v
	}
	if x.FString3 == nil || *x.FString3 == "" {
		v := string("\"\"")
		x.FString3 = &v
	}
	if x.FString4 == nil || *x.FString4 == "" {
		v := string("\"ts4\"")
		x.FString4 = &v
	}
	if x.FString5 == nil || *x.FString5 == "" {
		v := string("\"ts5\"")
		x.FString5 = &v
	}
	if x.FString6 == nil || *x.FString6 == "" {
		v := string("\"ts\"6\"")
		x.FString6 = &v
	}
	if x.FString7 == nil || *x.FString7 == "" {
		v := string("\"ts\"7\"")
		x.FString7 = &v
	}
	if x.FString8 == nil || *x.FString8 == "" {
		v := string("[ts8]")
		x.FString8 = &v
	}
	if x.FString9 == nil || *x.FString9 == "" {
		v := string("{ts9}")
		x.FString9 = &v
	}
	if x.FInt32 == nil || *x.FInt32 == 0 {
		v := int32(1)
		x.FInt32 = &v
	}
	if x.FInt64 == nil || *x.FInt64 == 0 {
		v := int64(2)
		x.FInt64 = &v
	}
	if x.FUint32 == nil || *x.FUint32 == 0 {
		v := uint32(3)
		x.FUint32 = &v
	}
	if x.FUint64 == nil || *x.FUint64 == 0 {
		v := uint64(4)
		x.FUint64 = &v
	}
	if x.FSint32 == nil || *x.FSint32 == 0 {
		v := int32(5)
		x.FSint32 = &v
	}
	if x.FSint64 == nil || *x.FSint64 == 0 {
		v := int64(6)
		x.FSint64 = &v
	}
	if x.FSfixed32 == nil || *x.FSfixed32 == 0 {
		v := int32(7)
		x.FSfixed32 = &v
	}
	if x.FSfixed64 == nil || *x.FSfixed64 == 0 {
		v := int64(8)
		x.FSfixed64 = &v
	}
	if x.FFixed32 == nil || *x.FFixed32 == 0 {
		v := uint32(9)
		x.FFixed32 = &v
	}
	if x.FFixed64 == nil || *x.FFixed64 == 0 {
		v := uint64(10)
		x.FFixed64 = &v
	}
	if x.FFloat == nil || *x.FFloat == 0 {
		v := float32(11.109999656677246)
		x.FFloat = &v
	}
	if x.FDouble == nil || *x.FDouble == 0 {
		v := float64(12.12)
		x.FDouble = &v
	}
	if x.FBool1 == nil || *x.FBool1 == false {
		v := bool(true)
		x.FBool1 = &v
	}
	if x.FBool2 == nil || *x.FBool2 == false {
		v := bool(false)
		x.FBool2 = &v
	}
	if len(x.FBytes1) == 0 {
		x.FBytes1 = []byte{}
	}
	if len(x.FBytes2) == 0 {
		x.FBytes2 = []byte{97, 98, 99}
	}
	if x.FEnum1 == nil || *x.FEnum1 == 0 {
		v := EnumOptional1(2)
		x.FEnum1 = &v
	}
	if x.FEnum2 == nil || *x.FEnum2 == 0 {
		v := EnumOptional1(10)
		x.FEnum2 = &v
	}
	if x.FEnum3 == nil || *x.FEnum3 == 0 {
		v := pbexternal.Month1(1)
		x.FEnum3 = &v
	}
	if x.FEnum4 == nil || *x.FEnum4 == 0 {
		v := pbexternal.Month2(7)
		x.FEnum4 = &v
	}
	if x.FEnum5 == nil || *x.FEnum5 == 0 {
		v := pbexternal.EnumWeek1_Week(3)
		x.FEnum5 = &v
	}
	if x.FEnum6 == nil || *x.FEnum6 == 0 {
		v := pbexternal.EnumWeek2_Embed1_Week(13)
		x.FEnum6 = &v
	}
	if x.FEnum7 == nil || *x.FEnum7 == 0 {
		v := EnumCommon1(9)
		x.FEnum7 = &v
	}
	if x.FDuration1.AsDuration() == 0 {
		x.FDuration1 = &durationpb.Duration{Seconds: 100, Nanos: 200}
	}
	if x.FDuration2.AsDuration() == 0 {
		x.FDuration2 = &durationpb.Duration{Seconds: 0, Nanos: 0}
	}
	if x.FTimestamp1.AsTime().UnixNano() == 0 {
		x.FTimestamp1 = &timestamppb.Timestamp{Seconds: 200, Nanos: 300}
	}
	if x.FTimestamp2.AsTime().UnixNano() == 0 {
		x.FTimestamp2 = &timestamppb.Timestamp{Seconds: 0, Nanos: 0}
	}
	if x.FMessage11 == nil {
		x.FMessage11 = &MessageOptional1{}
	}
	if x.FMessage11 != nil {
		x.FMessage11.SetDefault()
	}
	if x.FMessage12 == nil {
		x.FMessage12 = &MessageOptional1_Embed1{}
	}
	if x.FMessage13 == nil {
		x.FMessage13 = &MessageOptional1_Embed1_Embed2{}
	}
	if x.FMessage13 != nil {
		x.FMessage13.SetDefault()
	}
	if x.FMessage14 == nil {
		x.FMessage14 = &pbexternal.External1{}
	}
	if x.FMessage15 == nil {
		x.FMessage15 = &pbexternal.External2_Embed1{}
	}
	if x.FMessage15 != nil {
		x.FMessage15.SetDefault()
	}
	if x.FMessage16 == nil {
		x.FMessage16 = &MessageCommon1{}
	}
	if x.FMessage17 == nil {
		x.FMessage17 = &MessageCommon1_Embed1{}
	}
	if x.FMessage17 != nil {
		x.FMessage17.SetDefault()
	}
	if x.FMessage18 == nil {
		x.FMessage18 = &MessageCommon1_Embed1_Embed2{}
	}
	if x.FMessage21 != nil {
		x.FMessage21.SetDefault()
	}
	if x.FMessage23 != nil {
		x.FMessage23.SetDefault()
	}
	if x.FMessage25 != nil {
		x.FMessage25.SetDefault()
	}
	if x.FMessage27 != nil {
		x.FMessage27.SetDefault()
	}
	if x.FAny1.GetTypeUrl() == "" {
		x.FAny1 = x.xxx_protoc_plugin_default_mustNewAny(&MessageOptional1{}, false)
	}
	if x.FAny2.GetTypeUrl() == "" {
		x.FAny2 = x.xxx_protoc_plugin_default_mustNewAny(&MessageOptional1{}, true)
	}
	if x.FAny3.GetTypeUrl() == "" {
		x.FAny3 = x.xxx_protoc_plugin_default_mustNewAny(&MessageOptional1_Embed1{}, true)
	}
	if x.FAny4.GetTypeUrl() == "" {
		x.FAny4 = x.xxx_protoc_plugin_default_mustNewAny(&MessageOptional1_Embed1_Embed2{}, false)
	}
	if x.FAny5.GetTypeUrl() == "" {
		x.FAny5 = x.xxx_protoc_plugin_default_mustNewAny(&pbexternal.External1{}, true)
	}
	if x.FAny6.GetTypeUrl() == "" {
		x.FAny6 = x.xxx_protoc_plugin_default_mustNewAny(&pbexternal.External2_Embed1{}, false)
	}
	if x.FAny7.GetTypeUrl() == "" {
		x.FAny7 = x.xxx_protoc_plugin_default_mustNewAny(&timestamppb.Timestamp{}, false)
	}
	if x.FAny8.GetTypeUrl() == "" {
		x.FAny8 = x.xxx_protoc_plugin_default_mustNewAny(&anypb.Any{}, false)
	}
	if x.FAny9.GetTypeUrl() == "" {
		x.FAny9 = x.xxx_protoc_plugin_default_mustNewAny(&MessageCommon1{}, false)
	}
}

// xxx_protoc_plugin_default_mustNewAny used to create instance of type any
func (*TypeOptional1) xxx_protoc_plugin_default_mustNewAny(src proto.Message, skipEval bool) *anypb.Any {
	if !skipEval {
		if dt, ok := interface{}(src).(interface{ SetDefault() }); ok {
			dt.SetDefault()
		}
	}
	v, err := anypb.New(src)
	if err != nil {
		panic(err)
	}
	return v
}

// Set default value for message TypeOptional2 that in file tests/proto/cases/types/type_optional.proto
func (x *TypeOptional2) SetDefault() {
	if x == nil {
		return
	}
	if x.FString1 == nil {
		v := string("ts1")
		x.FString1 = &v
	}
	if x.FString2 == nil {
		v := string("")
		x.FString2 = &v
	}
	if x.FString3 == nil {
		v := string("\"\"")
		x.FString3 = &v
	}
	if x.FString4 == nil {
		v := string("\"ts4\"")
		x.FString4 = &v
	}
	if x.FString5 == nil {
		v := string("\"ts5\"")
		x.FString5 = &v
	}
	if x.FString6 == nil {
		v := string("\"ts\"6\"")
		x.FString6 = &v
	}
	if x.FString7 == nil {
		v := string("\"ts\"7\"")
		x.FString7 = &v
	}
	if x.FString8 == nil {
		v := string("[ts8]")
		x.FString8 = &v
	}
	if x.FString9 == nil {
		v := string("{ts9}")
		x.FString9 = &v
	}
	if x.FInt32 == nil {
		v := int32(1)
		x.FInt32 = &v
	}
	if x.FInt64 == nil {
		v := int64(2)
		x.FInt64 = &v
	}
	if x.FUint32 == nil {
		v := uint32(3)
		x.FUint32 = &v
	}
	if x.FUint64 == nil {
		v := uint64(4)
		x.FUint64 = &v
	}
	if x.FSint32 == nil {
		v := int32(5)
		x.FSint32 = &v
	}
	if x.FSint64 == nil {
		v := int64(6)
		x.FSint64 = &v
	}
	if x.FSfixed32 == nil {
		v := int32(7)
		x.FSfixed32 = &v
	}
	if x.FSfixed64 == nil {
		v := int64(8)
		x.FSfixed64 = &v
	}
	if x.FFixed32 == nil {
		v := uint32(9)
		x.FFixed32 = &v
	}
	if x.FFixed64 == nil {
		v := uint64(10)
		x.FFixed64 = &v
	}
	if x.FFloat == nil {
		v := float32(11.109999656677246)
		x.FFloat = &v
	}
	if x.FDouble == nil {
		v := float64(12.12)
		x.FDouble = &v
	}
	if x.FBool1 == nil {
		v := bool(true)
		x.FBool1 = &v
	}
	if x.FBool2 == nil {
		v := bool(false)
		x.FBool2 = &v
	}
	if x.FBytes1 == nil {
		x.FBytes1 = []byte{}
	}
	if x.FBytes2 == nil {
		x.FBytes2 = []byte{97, 98, 99}
	}
	if x.FEnum1 == nil {
		v := EnumOptional1(2)
		x.FEnum1 = &v
	}
	if x.FEnum2 == nil {
		v := EnumOptional1(10)
		x.FEnum2 = &v
	}
	if x.FEnum3 == nil {
		v := pbexternal.Month1(1)
		x.FEnum3 = &v
	}
	if x.FEnum4 == nil {
		v := pbexternal.Month2(7)
		x.FEnum4 = &v
	}
	if x.FEnum5 == nil {
		v := pbexternal.EnumWeek1_Week(3)
		x.FEnum5 = &v
	}
	if x.FEnum6 == nil {
		v := pbexternal.EnumWeek2_Embed1_Week(13)
		x.FEnum6 = &v
	}
	if x.FEnum7 == nil {
		v := EnumCommon1(9)
		x.FEnum7 = &v
	}
	if x.FMessage11 == nil {
		x.FMessage11 = &MessageOptional1{}
	}
	if x.FMessage11 != nil {
		x.FMessage11.SetDefault()
	}
	if x.FMessage12 == nil {
		x.FMessage12 = &MessageOptional1_Embed1{}
	}
	if x.FMessage13 == nil {
		x.FMessage13 = &MessageOptional1_Embed1_Embed2{}
	}
	if x.FMessage13 != nil {
		x.FMessage13.SetDefault()
	}
	if x.FMessage14 == nil {
		x.FMessage14 = &pbexternal.External1{}
	}
	if x.FMessage15 == nil {
		x.FMessage15 = &pbexternal.External2_Embed1{}
	}
	if x.FMessage15 != nil {
		x.FMessage15.SetDefault()
	}
	if x.FMessage16 == nil {
		x.FMessage16 = &MessageCommon1{}
	}
	if x.FMessage17 == nil {
		x.FMessage17 = &MessageCommon1_Embed1{}
	}
	if x.FMessage17 != nil {
		x.FMessage17.SetDefault()
	}
	if x.FMessage18 == nil {
		x.FMessage18 = &MessageCommon1_Embed1_Embed2{}
	}
	if x.FMessage21 != nil {
		x.FMessage21.SetDefault()
	}
	if x.FMessage23 != nil {
		x.FMessage23.SetDefault()
	}
	if x.FMessage25 != nil {
		x.FMessage25.SetDefault()
	}
	if x.FMessage27 != nil {
		x.FMessage27.SetDefault()
	}
	if x.FDuration1 == nil {
		x.FDuration1 = &durationpb.Duration{Seconds: 100, Nanos: 200}
	}
	if x.FDuration2 == nil {
		x.FDuration2 = &durationpb.Duration{Seconds: 0, Nanos: 0}
	}
	if x.FTimestamp1 == nil {
		x.FTimestamp1 = &timestamppb.Timestamp{Seconds: 200, Nanos: 300}
	}
	if x.FTimestamp2 == nil {
		x.FTimestamp2 = &timestamppb.Timestamp{Seconds: 0, Nanos: 0}
	}
	if x.FAny1 == nil {
		x.FAny1 = x.xxx_protoc_plugin_default_mustNewAny(&MessageOptional1{}, false)
	}
	if x.FAny2.GetTypeUrl() == "" {
		x.FAny2 = x.xxx_protoc_plugin_default_mustNewAny(&MessageOptional1{}, true)
	}
	if x.FAny3 == nil {
		x.FAny3 = x.xxx_protoc_plugin_default_mustNewAny(&MessageOptional1_Embed1{}, true)
	}
	if x.FAny4 == nil {
		x.FAny4 = x.xxx_protoc_plugin_default_mustNewAny(&MessageOptional1_Embed1_Embed2{}, false)
	}
	if x.FAny5 == nil {
		x.FAny5 = x.xxx_protoc_plugin_default_mustNewAny(&pbexternal.External1{}, true)
	}
	if x.FAny6 == nil {
		x.FAny6 = x.xxx_protoc_plugin_default_mustNewAny(&pbexternal.External2_Embed1{}, false)
	}
	if x.FAny7 == nil {
		x.FAny7 = x.xxx_protoc_plugin_default_mustNewAny(&timestamppb.Timestamp{}, false)
	}
	if x.FAny8 == nil {
		x.FAny8 = x.xxx_protoc_plugin_default_mustNewAny(&anypb.Any{}, false)
	}
	if x.FAny9 == nil {
		x.FAny9 = x.xxx_protoc_plugin_default_mustNewAny(&MessageCommon1{}, false)
	}
}

// xxx_protoc_plugin_default_mustNewAny used to create instance of type any
func (*TypeOptional2) xxx_protoc_plugin_default_mustNewAny(src proto.Message, skipEval bool) *anypb.Any {
	if !skipEval {
		if dt, ok := interface{}(src).(interface{ SetDefault() }); ok {
			dt.SetDefault()
		}
	}
	v, err := anypb.New(src)
	if err != nil {
		panic(err)
	}
	return v
}
