// Code generated by protoc-gen-godefault. DO NOT EDIT.
// versions:
// 		protoc-gen-godefault 0.0.1
// source: tests/proto/cases/types/type_repeated.proto

package pbtypes

import (
	_ "github.com/yu31/protoc-plugin-default/xgo/pb/pbdefault"
	pbexternal "github.com/yu31/protoc-plugin-default/xgo/tests/pb/pbexternal"
	proto "google.golang.org/protobuf/proto"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// Set default value for message MessageRepeated1 that in file tests/proto/cases/types/type_repeated.proto
func (x *MessageRepeated1) SetDefault() {
	if x == nil {
		return
	}
	if x.FString1 == "" {
		x.FString1 = "a"
	}
	if x.FString2 == "" {
		x.FString2 = "b"
	}
	if x.FString3 == "" {
		x.FString3 = "c"
	}
}

// Set default value for message Embed1 that in file tests/proto/cases/types/type_repeated.proto
func (x *MessageRepeated1_Embed1) SetDefault() {
	if x == nil {
		return
	}
	if x.FString1 == "" {
		x.FString1 = "x"
	}
	if x.FString2 == "" {
		x.FString2 = "y"
	}
	if x.FString3 == "" {
		x.FString3 = "z"
	}
}

// Set default value for message Embed2 that in file tests/proto/cases/types/type_repeated.proto
func (x *MessageRepeated1_Embed1_Embed2) SetDefault() {
	if x == nil {
		return
	}
	if x.FString1 == "" {
		x.FString1 = "1"
	}
	if x.FString2 == "" {
		x.FString2 = "2"
	}
	if x.FString3 == "" {
		x.FString3 = "3"
	}
}

// Set default value for message TypeRepeated1 that in file tests/proto/cases/types/type_repeated.proto
func (x *TypeRepeated1) SetDefault() {
	if x == nil {
		return
	}
	if len(x.FString1) == 0 {
		x.FString1 = []string{
			"ts1",
			"",
			"\"\"",
			"\"ts4\"",
			"\"ts5\"",
			"\"ts\"6\"",
			"\"ts\"7\"",
			"[ts8]",
			"{ts9}",
			"",
			"",
		}
	}
	if len(x.FInt32) == 0 {
		x.FInt32 = []int32{
			11,
			12,
			13,
			0,
			0,
		}
	}
	if len(x.FInt64) == 0 {
		x.FInt64 = []int64{
			21,
			22,
			23,
			0,
			0,
		}
	}
	if len(x.FUint32) == 0 {
		x.FUint32 = []uint32{
			31,
			32,
			33,
			0,
			0,
		}
	}
	if len(x.FUint64) == 0 {
		x.FUint64 = []uint64{
			41,
			42,
			43,
			0,
			0,
		}
	}
	if len(x.FSint32) == 0 {
		x.FSint32 = []int32{
			51,
			52,
			53,
			0,
			0,
		}
	}
	if len(x.FSint64) == 0 {
		x.FSint64 = []int64{
			61,
			62,
			63,
			0,
			0,
		}
	}
	if len(x.FSfixed32) == 0 {
		x.FSfixed32 = []int32{
			71,
			72,
			73,
			0,
			0,
		}
	}
	if len(x.FSfixed64) == 0 {
		x.FSfixed64 = []int64{
			81,
			82,
			83,
			0,
			0,
		}
	}
	if len(x.FFixed32) == 0 {
		x.FFixed32 = []uint32{
			91,
			92,
			93,
			0,
			0,
		}
	}
	if len(x.FFixed64) == 0 {
		x.FFixed64 = []uint64{
			101,
			102,
			103,
			0,
			0,
		}
	}
	if len(x.FFloat) == 0 {
		x.FFloat = []float32{
			111.11100006103516,
			112.11199951171875,
			113.11299896240234,
			0,
			0,
		}
	}
	if len(x.FDouble) == 0 {
		x.FDouble = []float64{
			121.121,
			122.122,
			123.123,
			0,
			0,
		}
	}
	if len(x.FBool1) == 0 {
		x.FBool1 = []bool{
			true,
			false,
			true,
			false,
			false,
		}
	}
	if len(x.FBytes1) == 0 {
		x.FBytes1 = [][]byte{
			[]byte{97, 98, 99},
			[]byte{},
			[]byte{49, 50, 51},
			[]byte{},
			[]byte{},
		}
	}
	if len(x.FEnum1) == 0 {
		x.FEnum1 = []EnumRepeated1{
			1,
			3,
			5,
			0,
			0,
		}
	}
	if len(x.FEnum2) == 0 {
		x.FEnum2 = []EnumRepeated1{
			2,
			4,
			6,
			0,
			0,
		}
	}
	if len(x.FEnum3) == 0 {
		x.FEnum3 = []pbexternal.Month1{
			1,
			3,
			5,
			0,
			0,
		}
	}
	if len(x.FEnum4) == 0 {
		x.FEnum4 = []pbexternal.Month2{
			2,
			4,
			6,
			0,
			0,
		}
	}
	if len(x.FEnum5) == 0 {
		x.FEnum5 = []pbexternal.EnumWeek1_Week{
			1,
			3,
			5,
			0,
			0,
		}
	}
	if len(x.FEnum6) == 0 {
		x.FEnum6 = []pbexternal.EnumWeek2_Embed1_Week{
			2,
			4,
			6,
			0,
			0,
		}
	}
	if len(x.FEnum7) == 0 {
		x.FEnum7 = []EnumCommon1{
			2,
			4,
			6,
			0,
			0,
		}
	}
	if len(x.FDuration1) == 0 {
		x.FDuration1 = []*durationpb.Duration{
			&durationpb.Duration{Seconds: 100, Nanos: 200},
			&durationpb.Duration{Seconds: 0, Nanos: 0},
			&durationpb.Duration{Seconds: 102, Nanos: 202},
			&durationpb.Duration{Seconds: 0, Nanos: 0},
			nil,
			nil,
		}
	}
	if len(x.FTimestamp1) == 0 {
		x.FTimestamp1 = []*timestamppb.Timestamp{
			&timestamppb.Timestamp{Seconds: 200, Nanos: 300},
			&timestamppb.Timestamp{Seconds: 0, Nanos: 0},
			&timestamppb.Timestamp{Seconds: 202, Nanos: 302},
			&timestamppb.Timestamp{Seconds: 0, Nanos: 0},
			nil,
			nil,
		}
	}
	if len(x.FMessage1) == 0 {
		x.FMessage1 = []*MessageRepeated1{
			&MessageRepeated1{},
			nil,
			&MessageRepeated1{},
			nil,
			nil,
			nil,
		}
	}
	for _, ri := range x.FMessage1 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	if len(x.FMessage2) == 0 {
		x.FMessage2 = []*MessageRepeated1_Embed1{
			&MessageRepeated1_Embed1{},
			nil,
			&MessageRepeated1_Embed1{},
			nil,
			nil,
			nil,
		}
	}
	if len(x.FMessage3) == 0 {
		x.FMessage3 = []*MessageRepeated1_Embed1_Embed2{
			&MessageRepeated1_Embed1_Embed2{},
			nil,
			&MessageRepeated1_Embed1_Embed2{},
			nil,
			nil,
			nil,
		}
	}
	for _, ri := range x.FMessage3 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	if len(x.FMessage4) == 0 {
		x.FMessage4 = []*pbexternal.External1{
			&pbexternal.External1{},
			nil,
			&pbexternal.External1{},
			nil,
			nil,
			nil,
		}
	}
	if len(x.FMessage5) == 0 {
		x.FMessage5 = []*pbexternal.External2_Embed1{
			&pbexternal.External2_Embed1{},
			nil,
			&pbexternal.External2_Embed1{},
			nil,
			nil,
			nil,
		}
	}
	for _, ri := range x.FMessage5 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	if len(x.FMessage6) == 0 {
		x.FMessage6 = []*MessageCommon1{
			&MessageCommon1{},
			nil,
			&MessageCommon1{},
			nil,
			nil,
			nil,
		}
	}
	for _, ri := range x.FMessage6 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	if len(x.FAny1) == 0 {
		x.FAny1 = []*anypb.Any{
			x.xxx_protoc_plugin_default_mustNewAny(&MessageRepeated1{}, false),
			x.xxx_protoc_plugin_default_mustNewAny(&MessageRepeated1_Embed1{}, false),
			x.xxx_protoc_plugin_default_mustNewAny(&MessageRepeated1_Embed1_Embed2{}, false),
			x.xxx_protoc_plugin_default_mustNewAny(&pbexternal.External1{}, false),
			x.xxx_protoc_plugin_default_mustNewAny(&pbexternal.External2_Embed1{}, false),
			x.xxx_protoc_plugin_default_mustNewAny(&timestamppb.Timestamp{}, false),
			x.xxx_protoc_plugin_default_mustNewAny(&anypb.Any{}, false),
			x.xxx_protoc_plugin_default_mustNewAny(&MessageCommon1{}, false),
			nil,
			nil,
			nil,
		}
	}
}

// xxx_protoc_plugin_default_mustNewAny used to create instance of type any
func (*TypeRepeated1) xxx_protoc_plugin_default_mustNewAny(src proto.Message, skipEval bool) *anypb.Any {
	if !skipEval {
		if dt, ok := interface{}(src).(interface{ SetDefault() }); ok {
			dt.SetDefault()
		}
	}
	v, err := anypb.New(src)
	if err != nil {
		panic(err)
	}
	return v
}

// Set default value for message TypeRepeated2 that in file tests/proto/cases/types/type_repeated.proto
func (x *TypeRepeated2) SetDefault() {
	if x == nil {
		return
	}
	if x.FString1 == nil {
		x.FString1 = []string{
			"ts1",
			"",
			"\"\"",
			"\"ts4\"",
			"\"ts5\"",
			"\"ts\"6\"",
			"\"ts\"7\"",
			"[ts8]",
			"{ts9}",
			"",
			"",
		}
	}
	if x.FInt32 == nil {
		x.FInt32 = []int32{
			11,
			12,
			13,
			0,
			0,
		}
	}
	if x.FInt64 == nil {
		x.FInt64 = []int64{
			21,
			22,
			23,
			0,
			0,
		}
	}
	if x.FUint32 == nil {
		x.FUint32 = []uint32{
			31,
			32,
			33,
			0,
			0,
		}
	}
	if x.FUint64 == nil {
		x.FUint64 = []uint64{
			41,
			42,
			43,
			0,
			0,
		}
	}
	if x.FSint32 == nil {
		x.FSint32 = []int32{
			51,
			52,
			53,
			0,
			0,
		}
	}
	if x.FSint64 == nil {
		x.FSint64 = []int64{
			61,
			62,
			63,
			0,
			0,
		}
	}
	if x.FSfixed32 == nil {
		x.FSfixed32 = []int32{
			71,
			72,
			73,
			0,
			0,
		}
	}
	if x.FSfixed64 == nil {
		x.FSfixed64 = []int64{
			81,
			82,
			83,
			0,
			0,
		}
	}
	if x.FFixed32 == nil {
		x.FFixed32 = []uint32{
			91,
			92,
			93,
			0,
			0,
		}
	}
	if x.FFixed64 == nil {
		x.FFixed64 = []uint64{
			101,
			102,
			103,
			0,
			0,
		}
	}
	if x.FFloat == nil {
		x.FFloat = []float32{
			111.11100006103516,
			112.11199951171875,
			113.11299896240234,
			0,
			0,
		}
	}
	if x.FDouble == nil {
		x.FDouble = []float64{
			121.121,
			122.122,
			123.123,
			0,
			0,
		}
	}
	if x.FBool1 == nil {
		x.FBool1 = []bool{
			true,
			false,
			true,
			false,
			false,
		}
	}
	if x.FBytes1 == nil {
		x.FBytes1 = [][]byte{
			[]byte{97, 98, 99},
			[]byte{},
			[]byte{49, 50, 51},
			[]byte{},
			[]byte{},
		}
	}
	if x.FEnum1 == nil {
		x.FEnum1 = []EnumRepeated1{
			1,
			3,
			5,
			0,
			0,
		}
	}
	if x.FEnum2 == nil {
		x.FEnum2 = []EnumRepeated1{
			2,
			4,
			6,
			0,
			0,
		}
	}
	if x.FEnum3 == nil {
		x.FEnum3 = []pbexternal.Month1{
			1,
			3,
			5,
			0,
			0,
		}
	}
	if x.FEnum4 == nil {
		x.FEnum4 = []pbexternal.Month2{
			2,
			4,
			6,
			0,
			0,
		}
	}
	if x.FEnum5 == nil {
		x.FEnum5 = []pbexternal.EnumWeek1_Week{
			1,
			3,
			5,
			0,
			0,
		}
	}
	if x.FEnum6 == nil {
		x.FEnum6 = []pbexternal.EnumWeek2_Embed1_Week{
			2,
			4,
			6,
			0,
			0,
		}
	}
	if x.FEnum7 == nil {
		x.FEnum7 = []EnumCommon1{
			2,
			4,
			6,
			0,
			0,
		}
	}
	if x.FDuration1 == nil {
		x.FDuration1 = []*durationpb.Duration{
			&durationpb.Duration{Seconds: 100, Nanos: 200},
			&durationpb.Duration{Seconds: 0, Nanos: 0},
			&durationpb.Duration{Seconds: 102, Nanos: 202},
			&durationpb.Duration{Seconds: 0, Nanos: 0},
			nil,
			nil,
		}
	}
	if x.FTimestamp1 == nil {
		x.FTimestamp1 = []*timestamppb.Timestamp{
			&timestamppb.Timestamp{Seconds: 200, Nanos: 300},
			&timestamppb.Timestamp{Seconds: 0, Nanos: 0},
			&timestamppb.Timestamp{Seconds: 202, Nanos: 302},
			&timestamppb.Timestamp{Seconds: 0, Nanos: 0},
			nil,
			nil,
		}
	}
	if x.FMessage1 == nil {
		x.FMessage1 = []*MessageRepeated1{
			&MessageRepeated1{},
			nil,
			&MessageRepeated1{},
			nil,
			nil,
			nil,
		}
	}
	for _, ri := range x.FMessage1 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	if x.FMessage2 == nil {
		x.FMessage2 = []*MessageRepeated1_Embed1{
			&MessageRepeated1_Embed1{},
			nil,
			&MessageRepeated1_Embed1{},
			nil,
			nil,
			nil,
		}
	}
	if x.FMessage3 == nil {
		x.FMessage3 = []*MessageRepeated1_Embed1_Embed2{
			&MessageRepeated1_Embed1_Embed2{},
			nil,
			&MessageRepeated1_Embed1_Embed2{},
			nil,
			nil,
			nil,
		}
	}
	for _, ri := range x.FMessage3 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	if x.FMessage4 == nil {
		x.FMessage4 = []*pbexternal.External1{
			&pbexternal.External1{},
			nil,
			&pbexternal.External1{},
			nil,
			nil,
			nil,
		}
	}
	if x.FMessage5 == nil {
		x.FMessage5 = []*pbexternal.External2_Embed1{
			&pbexternal.External2_Embed1{},
			nil,
			&pbexternal.External2_Embed1{},
			nil,
			nil,
			nil,
		}
	}
	for _, ri := range x.FMessage5 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	if x.FMessage6 == nil {
		x.FMessage6 = []*MessageCommon1{
			&MessageCommon1{},
			nil,
			&MessageCommon1{},
			nil,
			nil,
			nil,
		}
	}
	for _, ri := range x.FMessage6 {
		if ri != nil {
			ri.SetDefault()
		}
	}
	if x.FAny1 == nil {
		x.FAny1 = []*anypb.Any{
			x.xxx_protoc_plugin_default_mustNewAny(&MessageRepeated1{}, false),
			x.xxx_protoc_plugin_default_mustNewAny(&MessageRepeated1_Embed1{}, false),
			x.xxx_protoc_plugin_default_mustNewAny(&MessageRepeated1_Embed1_Embed2{}, false),
			x.xxx_protoc_plugin_default_mustNewAny(&pbexternal.External1{}, false),
			x.xxx_protoc_plugin_default_mustNewAny(&pbexternal.External2_Embed1{}, false),
			x.xxx_protoc_plugin_default_mustNewAny(&timestamppb.Timestamp{}, false),
			x.xxx_protoc_plugin_default_mustNewAny(&anypb.Any{}, false),
			x.xxx_protoc_plugin_default_mustNewAny(&MessageCommon1{}, false),
			nil,
			nil,
			nil,
		}
	}
}

// xxx_protoc_plugin_default_mustNewAny used to create instance of type any
func (*TypeRepeated2) xxx_protoc_plugin_default_mustNewAny(src proto.Message, skipEval bool) *anypb.Any {
	if !skipEval {
		if dt, ok := interface{}(src).(interface{ SetDefault() }); ok {
			dt.SetDefault()
		}
	}
	v, err := anypb.New(src)
	if err != nil {
		panic(err)
	}
	return v
}
