// Code generated by protoc-gen-godefault. DO NOT EDIT.
// versions:
// 		protoc-gen-godefault 0.0.1
// source: tests/proto/cases/boundary/cycle_reference.proto

package pbcycle

import (
	_ "github.com/yu31/protoc-plugin-default/xgo/pb/pbdefault"
)

// Set default value for message CycleMessageA that in file tests/proto/cases/boundary/cycle_reference.proto
func (x *CycleMessageA) SetDefault() {
	if x == nil {
		return
	}
	if x.T1 == "" {
		x.T1 = "123"
	}
	if x.MsgB == nil {
		x.MsgB = &CycleMessageB{}
	}
	if x.MsgB != nil {
		x.MsgB.SetDefault()
	}
}

// Set default value for message CycleMessageB that in file tests/proto/cases/boundary/cycle_reference.proto
func (x *CycleMessageB) SetDefault() {
	if x == nil {
		return
	}
	if x.T1 == "" {
		x.T1 = "456"
	}
	if x.MsgC == nil {
		x.MsgC = &CycleMessageC{}
	}
	if x.MsgC != nil {
		x.MsgC.SetDefault()
	}
}

// Set default value for message CycleMessageC that in file tests/proto/cases/boundary/cycle_reference.proto
func (x *CycleMessageC) SetDefault() {
	if x == nil {
		return
	}
	if x.T1 == "" {
		x.T1 = "789"
	}
	if x.MsgA == nil {
		x.MsgA = &CycleMessageA{}
	}
	if x.MsgA != nil {
		x.MsgA.SetDefault()
	}
}
