// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: defaults.proto

package io.github.yu31.protoc.pb.pbdefaults;

public interface AnyTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:defaults.AnyType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * proto file 的加载路径. 例如: "google/protobuf/timestamp.proto".
   * 如果指定的 message 在当前文件中. 则可以使用 "." 代替.
   * </pre>
   *
   * <code>string import_path = 11;</code>
   * @return The importPath.
   */
  java.lang.String getImportPath();
  /**
   * <pre>
   * proto file 的加载路径. 例如: "google/protobuf/timestamp.proto".
   * 如果指定的 message 在当前文件中. 则可以使用 "." 代替.
   * </pre>
   *
   * <code>string import_path = 11;</code>
   * @return The bytes for importPath.
   */
  com.google.protobuf.ByteString
      getImportPathBytes();

  /**
   * <pre>
   * message name. 注意: 大小写要与 proto file 中定义的一样.
   * 如果是内嵌的 message, 则写成 "Message.EmbedMessage"
   * </pre>
   *
   * <code>string msg_name = 12;</code>
   * @return The msgName.
   */
  java.lang.String getMsgName();
  /**
   * <pre>
   * message name. 注意: 大小写要与 proto file 中定义的一样.
   * 如果是内嵌的 message, 则写成 "Message.EmbedMessage"
   * </pre>
   *
   * <code>string msg_name = 12;</code>
   * @return The bytes for msgName.
   */
  com.google.protobuf.ByteString
      getMsgNameBytes();

  /**
   * <pre>
   * 对于 message 类型的字段, 包括在 repeated 和 map 中, 默认情况下会自动调用 'SetDefaults' 方法.
   * 将 'skip' 设置为 true 可以阻止这个行为.
   * </pre>
   *
   * <code>optional bool skip_eval = 13;</code>
   * @return Whether the skipEval field is set.
   */
  boolean hasSkipEval();
  /**
   * <pre>
   * 对于 message 类型的字段, 包括在 repeated 和 map 中, 默认情况下会自动调用 'SetDefaults' 方法.
   * 将 'skip' 设置为 true 可以阻止这个行为.
   * </pre>
   *
   * <code>optional bool skip_eval = 13;</code>
   * @return The skipEval.
   */
  boolean getSkipEval();
}
