// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: defaults.proto

package io.github.yu31.protoc.pb.pbdefaults;

/**
 * Protobuf type {@code defaults.AnyTags}
 */
public final class AnyTags extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:defaults.AnyTags)
    AnyTagsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AnyTags.newBuilder() to construct.
  private AnyTags(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AnyTags() {
    importPath_ = "";
    msgName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AnyTags();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AnyTags(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            importPath_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            msgName_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_AnyTags_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_AnyTags_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.yu31.protoc.pb.pbdefaults.AnyTags.class, io.github.yu31.protoc.pb.pbdefaults.AnyTags.Builder.class);
  }

  public static final int IMPORT_PATH_FIELD_NUMBER = 11;
  private volatile java.lang.Object importPath_;
  /**
   * <pre>
   * proto file 的加载路径. 例如: "google/protobuf/timestamp.proto".
   * 如果指定的 message 在当前文件中. 则可以使用 "." 代替.
   * </pre>
   *
   * <code>string import_path = 11;</code>
   * @return The importPath.
   */
  @java.lang.Override
  public java.lang.String getImportPath() {
    java.lang.Object ref = importPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      importPath_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * proto file 的加载路径. 例如: "google/protobuf/timestamp.proto".
   * 如果指定的 message 在当前文件中. 则可以使用 "." 代替.
   * </pre>
   *
   * <code>string import_path = 11;</code>
   * @return The bytes for importPath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImportPathBytes() {
    java.lang.Object ref = importPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      importPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSG_NAME_FIELD_NUMBER = 12;
  private volatile java.lang.Object msgName_;
  /**
   * <pre>
   * message name. 注意: 大小写要与 proto file 中定义的一样.
   * 如果是内嵌的 message, 则写成 "Message.EmbedMessage"
   * </pre>
   *
   * <code>string msg_name = 12;</code>
   * @return The msgName.
   */
  @java.lang.Override
  public java.lang.String getMsgName() {
    java.lang.Object ref = msgName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * message name. 注意: 大小写要与 proto file 中定义的一样.
   * 如果是内嵌的 message, 则写成 "Message.EmbedMessage"
   * </pre>
   *
   * <code>string msg_name = 12;</code>
   * @return The bytes for msgName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgNameBytes() {
    java.lang.Object ref = msgName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(importPath_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, importPath_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, msgName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(importPath_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, importPath_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, msgName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.yu31.protoc.pb.pbdefaults.AnyTags)) {
      return super.equals(obj);
    }
    io.github.yu31.protoc.pb.pbdefaults.AnyTags other = (io.github.yu31.protoc.pb.pbdefaults.AnyTags) obj;

    if (!getImportPath()
        .equals(other.getImportPath())) return false;
    if (!getMsgName()
        .equals(other.getMsgName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IMPORT_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getImportPath().hashCode();
    hash = (37 * hash) + MSG_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getMsgName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.yu31.protoc.pb.pbdefaults.AnyTags parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.AnyTags parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.AnyTags parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.AnyTags parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.AnyTags parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.AnyTags parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.AnyTags parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.AnyTags parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.AnyTags parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.AnyTags parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.AnyTags parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.AnyTags parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.yu31.protoc.pb.pbdefaults.AnyTags prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code defaults.AnyTags}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:defaults.AnyTags)
      io.github.yu31.protoc.pb.pbdefaults.AnyTagsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_AnyTags_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_AnyTags_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.yu31.protoc.pb.pbdefaults.AnyTags.class, io.github.yu31.protoc.pb.pbdefaults.AnyTags.Builder.class);
    }

    // Construct using io.github.yu31.protoc.pb.pbdefaults.AnyTags.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      importPath_ = "";

      msgName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_AnyTags_descriptor;
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefaults.AnyTags getDefaultInstanceForType() {
      return io.github.yu31.protoc.pb.pbdefaults.AnyTags.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefaults.AnyTags build() {
      io.github.yu31.protoc.pb.pbdefaults.AnyTags result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefaults.AnyTags buildPartial() {
      io.github.yu31.protoc.pb.pbdefaults.AnyTags result = new io.github.yu31.protoc.pb.pbdefaults.AnyTags(this);
      result.importPath_ = importPath_;
      result.msgName_ = msgName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.yu31.protoc.pb.pbdefaults.AnyTags) {
        return mergeFrom((io.github.yu31.protoc.pb.pbdefaults.AnyTags)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.yu31.protoc.pb.pbdefaults.AnyTags other) {
      if (other == io.github.yu31.protoc.pb.pbdefaults.AnyTags.getDefaultInstance()) return this;
      if (!other.getImportPath().isEmpty()) {
        importPath_ = other.importPath_;
        onChanged();
      }
      if (!other.getMsgName().isEmpty()) {
        msgName_ = other.msgName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.github.yu31.protoc.pb.pbdefaults.AnyTags parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.github.yu31.protoc.pb.pbdefaults.AnyTags) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object importPath_ = "";
    /**
     * <pre>
     * proto file 的加载路径. 例如: "google/protobuf/timestamp.proto".
     * 如果指定的 message 在当前文件中. 则可以使用 "." 代替.
     * </pre>
     *
     * <code>string import_path = 11;</code>
     * @return The importPath.
     */
    public java.lang.String getImportPath() {
      java.lang.Object ref = importPath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        importPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * proto file 的加载路径. 例如: "google/protobuf/timestamp.proto".
     * 如果指定的 message 在当前文件中. 则可以使用 "." 代替.
     * </pre>
     *
     * <code>string import_path = 11;</code>
     * @return The bytes for importPath.
     */
    public com.google.protobuf.ByteString
        getImportPathBytes() {
      java.lang.Object ref = importPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        importPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * proto file 的加载路径. 例如: "google/protobuf/timestamp.proto".
     * 如果指定的 message 在当前文件中. 则可以使用 "." 代替.
     * </pre>
     *
     * <code>string import_path = 11;</code>
     * @param value The importPath to set.
     * @return This builder for chaining.
     */
    public Builder setImportPath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      importPath_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * proto file 的加载路径. 例如: "google/protobuf/timestamp.proto".
     * 如果指定的 message 在当前文件中. 则可以使用 "." 代替.
     * </pre>
     *
     * <code>string import_path = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearImportPath() {
      
      importPath_ = getDefaultInstance().getImportPath();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * proto file 的加载路径. 例如: "google/protobuf/timestamp.proto".
     * 如果指定的 message 在当前文件中. 则可以使用 "." 代替.
     * </pre>
     *
     * <code>string import_path = 11;</code>
     * @param value The bytes for importPath to set.
     * @return This builder for chaining.
     */
    public Builder setImportPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      importPath_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object msgName_ = "";
    /**
     * <pre>
     * message name. 注意: 大小写要与 proto file 中定义的一样.
     * 如果是内嵌的 message, 则写成 "Message.EmbedMessage"
     * </pre>
     *
     * <code>string msg_name = 12;</code>
     * @return The msgName.
     */
    public java.lang.String getMsgName() {
      java.lang.Object ref = msgName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * message name. 注意: 大小写要与 proto file 中定义的一样.
     * 如果是内嵌的 message, 则写成 "Message.EmbedMessage"
     * </pre>
     *
     * <code>string msg_name = 12;</code>
     * @return The bytes for msgName.
     */
    public com.google.protobuf.ByteString
        getMsgNameBytes() {
      java.lang.Object ref = msgName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * message name. 注意: 大小写要与 proto file 中定义的一样.
     * 如果是内嵌的 message, 则写成 "Message.EmbedMessage"
     * </pre>
     *
     * <code>string msg_name = 12;</code>
     * @param value The msgName to set.
     * @return This builder for chaining.
     */
    public Builder setMsgName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msgName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * message name. 注意: 大小写要与 proto file 中定义的一样.
     * 如果是内嵌的 message, 则写成 "Message.EmbedMessage"
     * </pre>
     *
     * <code>string msg_name = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgName() {
      
      msgName_ = getDefaultInstance().getMsgName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * message name. 注意: 大小写要与 proto file 中定义的一样.
     * 如果是内嵌的 message, 则写成 "Message.EmbedMessage"
     * </pre>
     *
     * <code>string msg_name = 12;</code>
     * @param value The bytes for msgName to set.
     * @return This builder for chaining.
     */
    public Builder setMsgNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msgName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:defaults.AnyTags)
  }

  // @@protoc_insertion_point(class_scope:defaults.AnyTags)
  private static final io.github.yu31.protoc.pb.pbdefaults.AnyTags DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.yu31.protoc.pb.pbdefaults.AnyTags();
  }

  public static io.github.yu31.protoc.pb.pbdefaults.AnyTags getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnyTags>
      PARSER = new com.google.protobuf.AbstractParser<AnyTags>() {
    @java.lang.Override
    public AnyTags parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AnyTags(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AnyTags> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnyTags> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.yu31.protoc.pb.pbdefaults.AnyTags getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

