// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: defaults.proto

package io.github.yu31.protoc.pb.pbdefaults;

public interface FieldOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:defaults.FieldOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * PlainOptions declares the tags applied to the plain field.
   * </pre>
   *
   * <code>.defaults.PlainOptions plain = 1;</code>
   * @return Whether the plain field is set.
   */
  boolean hasPlain();
  /**
   * <pre>
   * PlainOptions declares the tags applied to the plain field.
   * </pre>
   *
   * <code>.defaults.PlainOptions plain = 1;</code>
   * @return The plain.
   */
  io.github.yu31.protoc.pb.pbdefaults.PlainOptions getPlain();
  /**
   * <pre>
   * PlainOptions declares the tags applied to the plain field.
   * </pre>
   *
   * <code>.defaults.PlainOptions plain = 1;</code>
   */
  io.github.yu31.protoc.pb.pbdefaults.PlainOptionsOrBuilder getPlainOrBuilder();

  /**
   * <pre>
   * RepeatedOptions declares the tags applied to the repeated filed.
   * </pre>
   *
   * <code>.defaults.RepeatedOptions repeated = 2;</code>
   * @return Whether the repeated field is set.
   */
  boolean hasRepeated();
  /**
   * <pre>
   * RepeatedOptions declares the tags applied to the repeated filed.
   * </pre>
   *
   * <code>.defaults.RepeatedOptions repeated = 2;</code>
   * @return The repeated.
   */
  io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions getRepeated();
  /**
   * <pre>
   * RepeatedOptions declares the tags applied to the repeated filed.
   * </pre>
   *
   * <code>.defaults.RepeatedOptions repeated = 2;</code>
   */
  io.github.yu31.protoc.pb.pbdefaults.RepeatedOptionsOrBuilder getRepeatedOrBuilder();

  /**
   * <pre>
   * MapTags declares the tags applied to the map filed.
   * </pre>
   *
   * <code>.defaults.MapOptions map = 3;</code>
   * @return Whether the map field is set.
   */
  boolean hasMap();
  /**
   * <pre>
   * MapTags declares the tags applied to the map filed.
   * </pre>
   *
   * <code>.defaults.MapOptions map = 3;</code>
   * @return The map.
   */
  io.github.yu31.protoc.pb.pbdefaults.MapOptions getMap();
  /**
   * <pre>
   * MapTags declares the tags applied to the map filed.
   * </pre>
   *
   * <code>.defaults.MapOptions map = 3;</code>
   */
  io.github.yu31.protoc.pb.pbdefaults.MapOptionsOrBuilder getMapOrBuilder();

  public io.github.yu31.protoc.pb.pbdefaults.FieldOptions.KindCase getKindCase();
}
