// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: defaults.proto

package io.github.yu31.protoc.pb.pbdefaults;

/**
 * <pre>
 * MapOptions 用户为 map 类型的字段设置默认值.
 * 只有当字段为值为 nil 的时候, 默认值才会被设置.
 * </pre>
 *
 * Protobuf type {@code defaults.MapTags}
 */
public final class MapTags extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:defaults.MapTags)
    MapTagsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MapTags.newBuilder() to construct.
  private MapTags(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MapTags() {
    kv_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MapTags();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MapTags(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 90: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              kv_ = new java.util.ArrayList<io.github.yu31.protoc.pb.pbdefaults.MapTags.KV>();
              mutable_bitField0_ |= 0x00000001;
            }
            kv_.add(
                input.readMessage(io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        kv_ = java.util.Collections.unmodifiableList(kv_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_MapTags_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_MapTags_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.yu31.protoc.pb.pbdefaults.MapTags.class, io.github.yu31.protoc.pb.pbdefaults.MapTags.Builder.class);
  }

  public interface KVOrBuilder extends
      // @@protoc_insertion_point(interface_extends:defaults.MapTags.KV)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.defaults.FieldType key = 11;</code>
     * @return Whether the key field is set.
     */
    boolean hasKey();
    /**
     * <code>.defaults.FieldType key = 11;</code>
     * @return The key.
     */
    io.github.yu31.protoc.pb.pbdefaults.FieldType getKey();
    /**
     * <code>.defaults.FieldType key = 11;</code>
     */
    io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder getKeyOrBuilder();

    /**
     * <code>.defaults.FieldType value = 12;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>.defaults.FieldType value = 12;</code>
     * @return The value.
     */
    io.github.yu31.protoc.pb.pbdefaults.FieldType getValue();
    /**
     * <code>.defaults.FieldType value = 12;</code>
     */
    io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder getValueOrBuilder();
  }
  /**
   * Protobuf type {@code defaults.MapTags.KV}
   */
  public static final class KV extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:defaults.MapTags.KV)
      KVOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KV.newBuilder() to construct.
    private KV(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KV() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new KV();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KV(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 90: {
              io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder subBuilder = null;
              if (key_ != null) {
                subBuilder = key_.toBuilder();
              }
              key_ = input.readMessage(io.github.yu31.protoc.pb.pbdefaults.FieldType.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(key_);
                key_ = subBuilder.buildPartial();
              }

              break;
            }
            case 98: {
              io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder subBuilder = null;
              if (value_ != null) {
                subBuilder = value_.toBuilder();
              }
              value_ = input.readMessage(io.github.yu31.protoc.pb.pbdefaults.FieldType.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(value_);
                value_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_MapTags_KV_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_MapTags_KV_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.class, io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 11;
    private io.github.yu31.protoc.pb.pbdefaults.FieldType key_;
    /**
     * <code>.defaults.FieldType key = 11;</code>
     * @return Whether the key field is set.
     */
    @java.lang.Override
    public boolean hasKey() {
      return key_ != null;
    }
    /**
     * <code>.defaults.FieldType key = 11;</code>
     * @return The key.
     */
    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefaults.FieldType getKey() {
      return key_ == null ? io.github.yu31.protoc.pb.pbdefaults.FieldType.getDefaultInstance() : key_;
    }
    /**
     * <code>.defaults.FieldType key = 11;</code>
     */
    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder getKeyOrBuilder() {
      return getKey();
    }

    public static final int VALUE_FIELD_NUMBER = 12;
    private io.github.yu31.protoc.pb.pbdefaults.FieldType value_;
    /**
     * <code>.defaults.FieldType value = 12;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return value_ != null;
    }
    /**
     * <code>.defaults.FieldType value = 12;</code>
     * @return The value.
     */
    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefaults.FieldType getValue() {
      return value_ == null ? io.github.yu31.protoc.pb.pbdefaults.FieldType.getDefaultInstance() : value_;
    }
    /**
     * <code>.defaults.FieldType value = 12;</code>
     */
    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder getValueOrBuilder() {
      return getValue();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (key_ != null) {
        output.writeMessage(11, getKey());
      }
      if (value_ != null) {
        output.writeMessage(12, getValue());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (key_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, getKey());
      }
      if (value_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, getValue());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.yu31.protoc.pb.pbdefaults.MapTags.KV)) {
        return super.equals(obj);
      }
      io.github.yu31.protoc.pb.pbdefaults.MapTags.KV other = (io.github.yu31.protoc.pb.pbdefaults.MapTags.KV) obj;

      if (hasKey() != other.hasKey()) return false;
      if (hasKey()) {
        if (!getKey()
            .equals(other.getKey())) return false;
      }
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.yu31.protoc.pb.pbdefaults.MapTags.KV parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.yu31.protoc.pb.pbdefaults.MapTags.KV parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.yu31.protoc.pb.pbdefaults.MapTags.KV parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.yu31.protoc.pb.pbdefaults.MapTags.KV parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.yu31.protoc.pb.pbdefaults.MapTags.KV parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.yu31.protoc.pb.pbdefaults.MapTags.KV parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.yu31.protoc.pb.pbdefaults.MapTags.KV parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.yu31.protoc.pb.pbdefaults.MapTags.KV parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.yu31.protoc.pb.pbdefaults.MapTags.KV parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.yu31.protoc.pb.pbdefaults.MapTags.KV parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.yu31.protoc.pb.pbdefaults.MapTags.KV parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.yu31.protoc.pb.pbdefaults.MapTags.KV parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.yu31.protoc.pb.pbdefaults.MapTags.KV prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code defaults.MapTags.KV}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:defaults.MapTags.KV)
        io.github.yu31.protoc.pb.pbdefaults.MapTags.KVOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_MapTags_KV_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_MapTags_KV_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.class, io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.Builder.class);
      }

      // Construct using io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (keyBuilder_ == null) {
          key_ = null;
        } else {
          key_ = null;
          keyBuilder_ = null;
        }
        if (valueBuilder_ == null) {
          value_ = null;
        } else {
          value_ = null;
          valueBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_MapTags_KV_descriptor;
      }

      @java.lang.Override
      public io.github.yu31.protoc.pb.pbdefaults.MapTags.KV getDefaultInstanceForType() {
        return io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.yu31.protoc.pb.pbdefaults.MapTags.KV build() {
        io.github.yu31.protoc.pb.pbdefaults.MapTags.KV result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.yu31.protoc.pb.pbdefaults.MapTags.KV buildPartial() {
        io.github.yu31.protoc.pb.pbdefaults.MapTags.KV result = new io.github.yu31.protoc.pb.pbdefaults.MapTags.KV(this);
        if (keyBuilder_ == null) {
          result.key_ = key_;
        } else {
          result.key_ = keyBuilder_.build();
        }
        if (valueBuilder_ == null) {
          result.value_ = value_;
        } else {
          result.value_ = valueBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.yu31.protoc.pb.pbdefaults.MapTags.KV) {
          return mergeFrom((io.github.yu31.protoc.pb.pbdefaults.MapTags.KV)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.yu31.protoc.pb.pbdefaults.MapTags.KV other) {
        if (other == io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.getDefaultInstance()) return this;
        if (other.hasKey()) {
          mergeKey(other.getKey());
        }
        if (other.hasValue()) {
          mergeValue(other.getValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.yu31.protoc.pb.pbdefaults.MapTags.KV parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.yu31.protoc.pb.pbdefaults.MapTags.KV) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private io.github.yu31.protoc.pb.pbdefaults.FieldType key_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.yu31.protoc.pb.pbdefaults.FieldType, io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder, io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder> keyBuilder_;
      /**
       * <code>.defaults.FieldType key = 11;</code>
       * @return Whether the key field is set.
       */
      public boolean hasKey() {
        return keyBuilder_ != null || key_ != null;
      }
      /**
       * <code>.defaults.FieldType key = 11;</code>
       * @return The key.
       */
      public io.github.yu31.protoc.pb.pbdefaults.FieldType getKey() {
        if (keyBuilder_ == null) {
          return key_ == null ? io.github.yu31.protoc.pb.pbdefaults.FieldType.getDefaultInstance() : key_;
        } else {
          return keyBuilder_.getMessage();
        }
      }
      /**
       * <code>.defaults.FieldType key = 11;</code>
       */
      public Builder setKey(io.github.yu31.protoc.pb.pbdefaults.FieldType value) {
        if (keyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          key_ = value;
          onChanged();
        } else {
          keyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.defaults.FieldType key = 11;</code>
       */
      public Builder setKey(
          io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder builderForValue) {
        if (keyBuilder_ == null) {
          key_ = builderForValue.build();
          onChanged();
        } else {
          keyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.defaults.FieldType key = 11;</code>
       */
      public Builder mergeKey(io.github.yu31.protoc.pb.pbdefaults.FieldType value) {
        if (keyBuilder_ == null) {
          if (key_ != null) {
            key_ =
              io.github.yu31.protoc.pb.pbdefaults.FieldType.newBuilder(key_).mergeFrom(value).buildPartial();
          } else {
            key_ = value;
          }
          onChanged();
        } else {
          keyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.defaults.FieldType key = 11;</code>
       */
      public Builder clearKey() {
        if (keyBuilder_ == null) {
          key_ = null;
          onChanged();
        } else {
          key_ = null;
          keyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.defaults.FieldType key = 11;</code>
       */
      public io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder getKeyBuilder() {
        
        onChanged();
        return getKeyFieldBuilder().getBuilder();
      }
      /**
       * <code>.defaults.FieldType key = 11;</code>
       */
      public io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder getKeyOrBuilder() {
        if (keyBuilder_ != null) {
          return keyBuilder_.getMessageOrBuilder();
        } else {
          return key_ == null ?
              io.github.yu31.protoc.pb.pbdefaults.FieldType.getDefaultInstance() : key_;
        }
      }
      /**
       * <code>.defaults.FieldType key = 11;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.yu31.protoc.pb.pbdefaults.FieldType, io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder, io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder> 
          getKeyFieldBuilder() {
        if (keyBuilder_ == null) {
          keyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.github.yu31.protoc.pb.pbdefaults.FieldType, io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder, io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder>(
                  getKey(),
                  getParentForChildren(),
                  isClean());
          key_ = null;
        }
        return keyBuilder_;
      }

      private io.github.yu31.protoc.pb.pbdefaults.FieldType value_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.yu31.protoc.pb.pbdefaults.FieldType, io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder, io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder> valueBuilder_;
      /**
       * <code>.defaults.FieldType value = 12;</code>
       * @return Whether the value field is set.
       */
      public boolean hasValue() {
        return valueBuilder_ != null || value_ != null;
      }
      /**
       * <code>.defaults.FieldType value = 12;</code>
       * @return The value.
       */
      public io.github.yu31.protoc.pb.pbdefaults.FieldType getValue() {
        if (valueBuilder_ == null) {
          return value_ == null ? io.github.yu31.protoc.pb.pbdefaults.FieldType.getDefaultInstance() : value_;
        } else {
          return valueBuilder_.getMessage();
        }
      }
      /**
       * <code>.defaults.FieldType value = 12;</code>
       */
      public Builder setValue(io.github.yu31.protoc.pb.pbdefaults.FieldType value) {
        if (valueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          valueBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.defaults.FieldType value = 12;</code>
       */
      public Builder setValue(
          io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder builderForValue) {
        if (valueBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          valueBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.defaults.FieldType value = 12;</code>
       */
      public Builder mergeValue(io.github.yu31.protoc.pb.pbdefaults.FieldType value) {
        if (valueBuilder_ == null) {
          if (value_ != null) {
            value_ =
              io.github.yu31.protoc.pb.pbdefaults.FieldType.newBuilder(value_).mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          valueBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.defaults.FieldType value = 12;</code>
       */
      public Builder clearValue() {
        if (valueBuilder_ == null) {
          value_ = null;
          onChanged();
        } else {
          value_ = null;
          valueBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.defaults.FieldType value = 12;</code>
       */
      public io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder getValueBuilder() {
        
        onChanged();
        return getValueFieldBuilder().getBuilder();
      }
      /**
       * <code>.defaults.FieldType value = 12;</code>
       */
      public io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder getValueOrBuilder() {
        if (valueBuilder_ != null) {
          return valueBuilder_.getMessageOrBuilder();
        } else {
          return value_ == null ?
              io.github.yu31.protoc.pb.pbdefaults.FieldType.getDefaultInstance() : value_;
        }
      }
      /**
       * <code>.defaults.FieldType value = 12;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.yu31.protoc.pb.pbdefaults.FieldType, io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder, io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder> 
          getValueFieldBuilder() {
        if (valueBuilder_ == null) {
          valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.github.yu31.protoc.pb.pbdefaults.FieldType, io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder, io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder>(
                  getValue(),
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        return valueBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:defaults.MapTags.KV)
    }

    // @@protoc_insertion_point(class_scope:defaults.MapTags.KV)
    private static final io.github.yu31.protoc.pb.pbdefaults.MapTags.KV DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.yu31.protoc.pb.pbdefaults.MapTags.KV();
    }

    public static io.github.yu31.protoc.pb.pbdefaults.MapTags.KV getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KV>
        PARSER = new com.google.protobuf.AbstractParser<KV>() {
      @java.lang.Override
      public KV parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KV(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KV> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KV> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefaults.MapTags.KV getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int KV_FIELD_NUMBER = 11;
  private java.util.List<io.github.yu31.protoc.pb.pbdefaults.MapTags.KV> kv_;
  /**
   * <code>repeated .defaults.MapTags.KV kv = 11;</code>
   */
  @java.lang.Override
  public java.util.List<io.github.yu31.protoc.pb.pbdefaults.MapTags.KV> getKvList() {
    return kv_;
  }
  /**
   * <code>repeated .defaults.MapTags.KV kv = 11;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.github.yu31.protoc.pb.pbdefaults.MapTags.KVOrBuilder> 
      getKvOrBuilderList() {
    return kv_;
  }
  /**
   * <code>repeated .defaults.MapTags.KV kv = 11;</code>
   */
  @java.lang.Override
  public int getKvCount() {
    return kv_.size();
  }
  /**
   * <code>repeated .defaults.MapTags.KV kv = 11;</code>
   */
  @java.lang.Override
  public io.github.yu31.protoc.pb.pbdefaults.MapTags.KV getKv(int index) {
    return kv_.get(index);
  }
  /**
   * <code>repeated .defaults.MapTags.KV kv = 11;</code>
   */
  @java.lang.Override
  public io.github.yu31.protoc.pb.pbdefaults.MapTags.KVOrBuilder getKvOrBuilder(
      int index) {
    return kv_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < kv_.size(); i++) {
      output.writeMessage(11, kv_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < kv_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, kv_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.yu31.protoc.pb.pbdefaults.MapTags)) {
      return super.equals(obj);
    }
    io.github.yu31.protoc.pb.pbdefaults.MapTags other = (io.github.yu31.protoc.pb.pbdefaults.MapTags) obj;

    if (!getKvList()
        .equals(other.getKvList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getKvCount() > 0) {
      hash = (37 * hash) + KV_FIELD_NUMBER;
      hash = (53 * hash) + getKvList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.yu31.protoc.pb.pbdefaults.MapTags parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MapTags parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MapTags parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MapTags parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MapTags parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MapTags parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MapTags parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MapTags parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MapTags parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MapTags parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MapTags parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MapTags parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.yu31.protoc.pb.pbdefaults.MapTags prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * MapOptions 用户为 map 类型的字段设置默认值.
   * 只有当字段为值为 nil 的时候, 默认值才会被设置.
   * </pre>
   *
   * Protobuf type {@code defaults.MapTags}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:defaults.MapTags)
      io.github.yu31.protoc.pb.pbdefaults.MapTagsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_MapTags_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_MapTags_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.yu31.protoc.pb.pbdefaults.MapTags.class, io.github.yu31.protoc.pb.pbdefaults.MapTags.Builder.class);
    }

    // Construct using io.github.yu31.protoc.pb.pbdefaults.MapTags.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getKvFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (kvBuilder_ == null) {
        kv_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        kvBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_MapTags_descriptor;
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefaults.MapTags getDefaultInstanceForType() {
      return io.github.yu31.protoc.pb.pbdefaults.MapTags.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefaults.MapTags build() {
      io.github.yu31.protoc.pb.pbdefaults.MapTags result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefaults.MapTags buildPartial() {
      io.github.yu31.protoc.pb.pbdefaults.MapTags result = new io.github.yu31.protoc.pb.pbdefaults.MapTags(this);
      int from_bitField0_ = bitField0_;
      if (kvBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          kv_ = java.util.Collections.unmodifiableList(kv_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.kv_ = kv_;
      } else {
        result.kv_ = kvBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.yu31.protoc.pb.pbdefaults.MapTags) {
        return mergeFrom((io.github.yu31.protoc.pb.pbdefaults.MapTags)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.yu31.protoc.pb.pbdefaults.MapTags other) {
      if (other == io.github.yu31.protoc.pb.pbdefaults.MapTags.getDefaultInstance()) return this;
      if (kvBuilder_ == null) {
        if (!other.kv_.isEmpty()) {
          if (kv_.isEmpty()) {
            kv_ = other.kv_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureKvIsMutable();
            kv_.addAll(other.kv_);
          }
          onChanged();
        }
      } else {
        if (!other.kv_.isEmpty()) {
          if (kvBuilder_.isEmpty()) {
            kvBuilder_.dispose();
            kvBuilder_ = null;
            kv_ = other.kv_;
            bitField0_ = (bitField0_ & ~0x00000001);
            kvBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getKvFieldBuilder() : null;
          } else {
            kvBuilder_.addAllMessages(other.kv_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.github.yu31.protoc.pb.pbdefaults.MapTags parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.github.yu31.protoc.pb.pbdefaults.MapTags) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.github.yu31.protoc.pb.pbdefaults.MapTags.KV> kv_ =
      java.util.Collections.emptyList();
    private void ensureKvIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        kv_ = new java.util.ArrayList<io.github.yu31.protoc.pb.pbdefaults.MapTags.KV>(kv_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.github.yu31.protoc.pb.pbdefaults.MapTags.KV, io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.Builder, io.github.yu31.protoc.pb.pbdefaults.MapTags.KVOrBuilder> kvBuilder_;

    /**
     * <code>repeated .defaults.MapTags.KV kv = 11;</code>
     */
    public java.util.List<io.github.yu31.protoc.pb.pbdefaults.MapTags.KV> getKvList() {
      if (kvBuilder_ == null) {
        return java.util.Collections.unmodifiableList(kv_);
      } else {
        return kvBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .defaults.MapTags.KV kv = 11;</code>
     */
    public int getKvCount() {
      if (kvBuilder_ == null) {
        return kv_.size();
      } else {
        return kvBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .defaults.MapTags.KV kv = 11;</code>
     */
    public io.github.yu31.protoc.pb.pbdefaults.MapTags.KV getKv(int index) {
      if (kvBuilder_ == null) {
        return kv_.get(index);
      } else {
        return kvBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .defaults.MapTags.KV kv = 11;</code>
     */
    public Builder setKv(
        int index, io.github.yu31.protoc.pb.pbdefaults.MapTags.KV value) {
      if (kvBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKvIsMutable();
        kv_.set(index, value);
        onChanged();
      } else {
        kvBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .defaults.MapTags.KV kv = 11;</code>
     */
    public Builder setKv(
        int index, io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.Builder builderForValue) {
      if (kvBuilder_ == null) {
        ensureKvIsMutable();
        kv_.set(index, builderForValue.build());
        onChanged();
      } else {
        kvBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .defaults.MapTags.KV kv = 11;</code>
     */
    public Builder addKv(io.github.yu31.protoc.pb.pbdefaults.MapTags.KV value) {
      if (kvBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKvIsMutable();
        kv_.add(value);
        onChanged();
      } else {
        kvBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .defaults.MapTags.KV kv = 11;</code>
     */
    public Builder addKv(
        int index, io.github.yu31.protoc.pb.pbdefaults.MapTags.KV value) {
      if (kvBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKvIsMutable();
        kv_.add(index, value);
        onChanged();
      } else {
        kvBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .defaults.MapTags.KV kv = 11;</code>
     */
    public Builder addKv(
        io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.Builder builderForValue) {
      if (kvBuilder_ == null) {
        ensureKvIsMutable();
        kv_.add(builderForValue.build());
        onChanged();
      } else {
        kvBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .defaults.MapTags.KV kv = 11;</code>
     */
    public Builder addKv(
        int index, io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.Builder builderForValue) {
      if (kvBuilder_ == null) {
        ensureKvIsMutable();
        kv_.add(index, builderForValue.build());
        onChanged();
      } else {
        kvBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .defaults.MapTags.KV kv = 11;</code>
     */
    public Builder addAllKv(
        java.lang.Iterable<? extends io.github.yu31.protoc.pb.pbdefaults.MapTags.KV> values) {
      if (kvBuilder_ == null) {
        ensureKvIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, kv_);
        onChanged();
      } else {
        kvBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .defaults.MapTags.KV kv = 11;</code>
     */
    public Builder clearKv() {
      if (kvBuilder_ == null) {
        kv_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        kvBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .defaults.MapTags.KV kv = 11;</code>
     */
    public Builder removeKv(int index) {
      if (kvBuilder_ == null) {
        ensureKvIsMutable();
        kv_.remove(index);
        onChanged();
      } else {
        kvBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .defaults.MapTags.KV kv = 11;</code>
     */
    public io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.Builder getKvBuilder(
        int index) {
      return getKvFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .defaults.MapTags.KV kv = 11;</code>
     */
    public io.github.yu31.protoc.pb.pbdefaults.MapTags.KVOrBuilder getKvOrBuilder(
        int index) {
      if (kvBuilder_ == null) {
        return kv_.get(index);  } else {
        return kvBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .defaults.MapTags.KV kv = 11;</code>
     */
    public java.util.List<? extends io.github.yu31.protoc.pb.pbdefaults.MapTags.KVOrBuilder> 
         getKvOrBuilderList() {
      if (kvBuilder_ != null) {
        return kvBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(kv_);
      }
    }
    /**
     * <code>repeated .defaults.MapTags.KV kv = 11;</code>
     */
    public io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.Builder addKvBuilder() {
      return getKvFieldBuilder().addBuilder(
          io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.getDefaultInstance());
    }
    /**
     * <code>repeated .defaults.MapTags.KV kv = 11;</code>
     */
    public io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.Builder addKvBuilder(
        int index) {
      return getKvFieldBuilder().addBuilder(
          index, io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.getDefaultInstance());
    }
    /**
     * <code>repeated .defaults.MapTags.KV kv = 11;</code>
     */
    public java.util.List<io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.Builder> 
         getKvBuilderList() {
      return getKvFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.github.yu31.protoc.pb.pbdefaults.MapTags.KV, io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.Builder, io.github.yu31.protoc.pb.pbdefaults.MapTags.KVOrBuilder> 
        getKvFieldBuilder() {
      if (kvBuilder_ == null) {
        kvBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.github.yu31.protoc.pb.pbdefaults.MapTags.KV, io.github.yu31.protoc.pb.pbdefaults.MapTags.KV.Builder, io.github.yu31.protoc.pb.pbdefaults.MapTags.KVOrBuilder>(
                kv_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        kv_ = null;
      }
      return kvBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:defaults.MapTags)
  }

  // @@protoc_insertion_point(class_scope:defaults.MapTags)
  private static final io.github.yu31.protoc.pb.pbdefaults.MapTags DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.yu31.protoc.pb.pbdefaults.MapTags();
  }

  public static io.github.yu31.protoc.pb.pbdefaults.MapTags getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MapTags>
      PARSER = new com.google.protobuf.AbstractParser<MapTags>() {
    @java.lang.Override
    public MapTags parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MapTags(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MapTags> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MapTags> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.yu31.protoc.pb.pbdefaults.MapTags getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

