// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: defaults.proto

package io.github.yu31.protoc.pb.pbdefaults;

public interface MapTagsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:defaults.MapTags)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .defaults.MapTags.KV kv = 11;</code>
   */
  java.util.List<io.github.yu31.protoc.pb.pbdefaults.MapTags.KV> 
      getKvList();
  /**
   * <code>repeated .defaults.MapTags.KV kv = 11;</code>
   */
  io.github.yu31.protoc.pb.pbdefaults.MapTags.KV getKv(int index);
  /**
   * <code>repeated .defaults.MapTags.KV kv = 11;</code>
   */
  int getKvCount();
  /**
   * <code>repeated .defaults.MapTags.KV kv = 11;</code>
   */
  java.util.List<? extends io.github.yu31.protoc.pb.pbdefaults.MapTags.KVOrBuilder> 
      getKvOrBuilderList();
  /**
   * <code>repeated .defaults.MapTags.KV kv = 11;</code>
   */
  io.github.yu31.protoc.pb.pbdefaults.MapTags.KVOrBuilder getKvOrBuilder(
      int index);
}
