// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: defaults.proto

package io.github.yu31.protoc.pb.pbdefaults;

public interface MessageOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:defaults.MessageOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Init initialize the `message` to empty value if it is a nil pointer.
   * 当 message 为 null 时, 字段的默认值才会被设置.
   * Only effective for language Go.
   * </pre>
   *
   * <code>optional bool init = 1;</code>
   * @return Whether the init field is set.
   */
  boolean hasInit();
  /**
   * <pre>
   * Init initialize the `message` to empty value if it is a nil pointer.
   * 当 message 为 null 时, 字段的默认值才会被设置.
   * Only effective for language Go.
   * </pre>
   *
   * <code>optional bool init = 1;</code>
   * @return The init.
   */
  boolean getInit();
}
