// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: defaults.proto

package io.github.yu31.protoc.pb.pbdefaults;

/**
 * Protobuf type {@code defaults.MessageTags}
 */
public final class MessageTags extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:defaults.MessageTags)
    MessageTagsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageTags.newBuilder() to construct.
  private MessageTags(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageTags() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageTags();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MessageTags(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 88: {
            bitField0_ |= 0x00000001;
            init_ = input.readBool();
            break;
          }
          case 96: {
            bitField0_ |= 0x00000002;
            skipEval_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_MessageTags_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_MessageTags_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.yu31.protoc.pb.pbdefaults.MessageTags.class, io.github.yu31.protoc.pb.pbdefaults.MessageTags.Builder.class);
  }

  private int bitField0_;
  public static final int INIT_FIELD_NUMBER = 11;
  private boolean init_;
  /**
   * <pre>
   * init 为 true 时表示如果字段的值为 nil, 则将其初始化为空值.
   * </pre>
   *
   * <code>optional bool init = 11;</code>
   * @return Whether the init field is set.
   */
  @java.lang.Override
  public boolean hasInit() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * init 为 true 时表示如果字段的值为 nil, 则将其初始化为空值.
   * </pre>
   *
   * <code>optional bool init = 11;</code>
   * @return The init.
   */
  @java.lang.Override
  public boolean getInit() {
    return init_;
  }

  public static final int SKIP_EVAL_FIELD_NUMBER = 12;
  private boolean skipEval_;
  /**
   * <pre>
   * 对于 message 类型的字段, 包括在 repeated 和 map 中, 默认情况下会自动调用 'SetDefaults' 方法.
   * 将 'skip_eval' 设置为 true 可以阻止这个行为.
   * </pre>
   *
   * <code>optional bool skip_eval = 12;</code>
   * @return Whether the skipEval field is set.
   */
  @java.lang.Override
  public boolean hasSkipEval() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 对于 message 类型的字段, 包括在 repeated 和 map 中, 默认情况下会自动调用 'SetDefaults' 方法.
   * 将 'skip_eval' 设置为 true 可以阻止这个行为.
   * </pre>
   *
   * <code>optional bool skip_eval = 12;</code>
   * @return The skipEval.
   */
  @java.lang.Override
  public boolean getSkipEval() {
    return skipEval_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(11, init_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBool(12, skipEval_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, init_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(12, skipEval_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.yu31.protoc.pb.pbdefaults.MessageTags)) {
      return super.equals(obj);
    }
    io.github.yu31.protoc.pb.pbdefaults.MessageTags other = (io.github.yu31.protoc.pb.pbdefaults.MessageTags) obj;

    if (hasInit() != other.hasInit()) return false;
    if (hasInit()) {
      if (getInit()
          != other.getInit()) return false;
    }
    if (hasSkipEval() != other.hasSkipEval()) return false;
    if (hasSkipEval()) {
      if (getSkipEval()
          != other.getSkipEval()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasInit()) {
      hash = (37 * hash) + INIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getInit());
    }
    if (hasSkipEval()) {
      hash = (37 * hash) + SKIP_EVAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSkipEval());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.yu31.protoc.pb.pbdefaults.MessageTags parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MessageTags parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MessageTags parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MessageTags parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MessageTags parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MessageTags parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MessageTags parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MessageTags parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MessageTags parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MessageTags parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MessageTags parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.MessageTags parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.yu31.protoc.pb.pbdefaults.MessageTags prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code defaults.MessageTags}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:defaults.MessageTags)
      io.github.yu31.protoc.pb.pbdefaults.MessageTagsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_MessageTags_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_MessageTags_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.yu31.protoc.pb.pbdefaults.MessageTags.class, io.github.yu31.protoc.pb.pbdefaults.MessageTags.Builder.class);
    }

    // Construct using io.github.yu31.protoc.pb.pbdefaults.MessageTags.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      init_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      skipEval_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_MessageTags_descriptor;
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefaults.MessageTags getDefaultInstanceForType() {
      return io.github.yu31.protoc.pb.pbdefaults.MessageTags.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefaults.MessageTags build() {
      io.github.yu31.protoc.pb.pbdefaults.MessageTags result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefaults.MessageTags buildPartial() {
      io.github.yu31.protoc.pb.pbdefaults.MessageTags result = new io.github.yu31.protoc.pb.pbdefaults.MessageTags(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.init_ = init_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.skipEval_ = skipEval_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.yu31.protoc.pb.pbdefaults.MessageTags) {
        return mergeFrom((io.github.yu31.protoc.pb.pbdefaults.MessageTags)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.yu31.protoc.pb.pbdefaults.MessageTags other) {
      if (other == io.github.yu31.protoc.pb.pbdefaults.MessageTags.getDefaultInstance()) return this;
      if (other.hasInit()) {
        setInit(other.getInit());
      }
      if (other.hasSkipEval()) {
        setSkipEval(other.getSkipEval());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.github.yu31.protoc.pb.pbdefaults.MessageTags parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.github.yu31.protoc.pb.pbdefaults.MessageTags) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean init_ ;
    /**
     * <pre>
     * init 为 true 时表示如果字段的值为 nil, 则将其初始化为空值.
     * </pre>
     *
     * <code>optional bool init = 11;</code>
     * @return Whether the init field is set.
     */
    @java.lang.Override
    public boolean hasInit() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * init 为 true 时表示如果字段的值为 nil, 则将其初始化为空值.
     * </pre>
     *
     * <code>optional bool init = 11;</code>
     * @return The init.
     */
    @java.lang.Override
    public boolean getInit() {
      return init_;
    }
    /**
     * <pre>
     * init 为 true 时表示如果字段的值为 nil, 则将其初始化为空值.
     * </pre>
     *
     * <code>optional bool init = 11;</code>
     * @param value The init to set.
     * @return This builder for chaining.
     */
    public Builder setInit(boolean value) {
      bitField0_ |= 0x00000001;
      init_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * init 为 true 时表示如果字段的值为 nil, 则将其初始化为空值.
     * </pre>
     *
     * <code>optional bool init = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearInit() {
      bitField0_ = (bitField0_ & ~0x00000001);
      init_ = false;
      onChanged();
      return this;
    }

    private boolean skipEval_ ;
    /**
     * <pre>
     * 对于 message 类型的字段, 包括在 repeated 和 map 中, 默认情况下会自动调用 'SetDefaults' 方法.
     * 将 'skip_eval' 设置为 true 可以阻止这个行为.
     * </pre>
     *
     * <code>optional bool skip_eval = 12;</code>
     * @return Whether the skipEval field is set.
     */
    @java.lang.Override
    public boolean hasSkipEval() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 对于 message 类型的字段, 包括在 repeated 和 map 中, 默认情况下会自动调用 'SetDefaults' 方法.
     * 将 'skip_eval' 设置为 true 可以阻止这个行为.
     * </pre>
     *
     * <code>optional bool skip_eval = 12;</code>
     * @return The skipEval.
     */
    @java.lang.Override
    public boolean getSkipEval() {
      return skipEval_;
    }
    /**
     * <pre>
     * 对于 message 类型的字段, 包括在 repeated 和 map 中, 默认情况下会自动调用 'SetDefaults' 方法.
     * 将 'skip_eval' 设置为 true 可以阻止这个行为.
     * </pre>
     *
     * <code>optional bool skip_eval = 12;</code>
     * @param value The skipEval to set.
     * @return This builder for chaining.
     */
    public Builder setSkipEval(boolean value) {
      bitField0_ |= 0x00000002;
      skipEval_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 对于 message 类型的字段, 包括在 repeated 和 map 中, 默认情况下会自动调用 'SetDefaults' 方法.
     * 将 'skip_eval' 设置为 true 可以阻止这个行为.
     * </pre>
     *
     * <code>optional bool skip_eval = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkipEval() {
      bitField0_ = (bitField0_ & ~0x00000002);
      skipEval_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:defaults.MessageTags)
  }

  // @@protoc_insertion_point(class_scope:defaults.MessageTags)
  private static final io.github.yu31.protoc.pb.pbdefaults.MessageTags DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.yu31.protoc.pb.pbdefaults.MessageTags();
  }

  public static io.github.yu31.protoc.pb.pbdefaults.MessageTags getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageTags>
      PARSER = new com.google.protobuf.AbstractParser<MessageTags>() {
    @java.lang.Override
    public MessageTags parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MessageTags(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageTags> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageTags> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.yu31.protoc.pb.pbdefaults.MessageTags getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

