// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: defaults.proto

package io.github.yu31.protoc.pb.pbdefaults;

public interface OneOfOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:defaults.OneOfOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of filed in `oneof` part.
   * </pre>
   *
   * <code>optional string field = 1;</code>
   * @return Whether the field field is set.
   */
  boolean hasField();
  /**
   * <pre>
   * The name of filed in `oneof` part.
   * </pre>
   *
   * <code>optional string field = 1;</code>
   * @return The field.
   */
  java.lang.String getField();
  /**
   * <pre>
   * The name of filed in `oneof` part.
   * </pre>
   *
   * <code>optional string field = 1;</code>
   * @return The bytes for field.
   */
  com.google.protobuf.ByteString
      getFieldBytes();
}
