// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: defaults.proto

package io.github.yu31.protoc.pb.pbdefaults;

public interface PlainTagsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:defaults.PlainTags)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.defaults.FieldType value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>.defaults.FieldType value = 2;</code>
   * @return The value.
   */
  io.github.yu31.protoc.pb.pbdefaults.FieldType getValue();
  /**
   * <code>.defaults.FieldType value = 2;</code>
   */
  io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder getValueOrBuilder();
}
