// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: defaults.proto

package io.github.yu31.protoc.pb.pbdefaults;

public interface RepeatedTagsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:defaults.RepeatedTags)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * int set default value for the data type of `int32`, `int64`, `sint32`, `sint64`, `sfixed32`, `sfixed64`.
   * </pre>
   *
   * <code>repeated int32 int32 = 11;</code>
   * @return A list containing the int32.
   */
  java.util.List<java.lang.Integer> getInt32List();
  /**
   * <pre>
   * int set default value for the data type of `int32`, `int64`, `sint32`, `sint64`, `sfixed32`, `sfixed64`.
   * </pre>
   *
   * <code>repeated int32 int32 = 11;</code>
   * @return The count of int32.
   */
  int getInt32Count();
  /**
   * <pre>
   * int set default value for the data type of `int32`, `int64`, `sint32`, `sint64`, `sfixed32`, `sfixed64`.
   * </pre>
   *
   * <code>repeated int32 int32 = 11;</code>
   * @param index The index of the element to return.
   * @return The int32 at the given index.
   */
  int getInt32(int index);

  /**
   * <code>repeated int64 int64 = 12;</code>
   * @return A list containing the int64.
   */
  java.util.List<java.lang.Long> getInt64List();
  /**
   * <code>repeated int64 int64 = 12;</code>
   * @return The count of int64.
   */
  int getInt64Count();
  /**
   * <code>repeated int64 int64 = 12;</code>
   * @param index The index of the element to return.
   * @return The int64 at the given index.
   */
  long getInt64(int index);

  /**
   * <code>repeated sint32 sint32 = 13;</code>
   * @return A list containing the sint32.
   */
  java.util.List<java.lang.Integer> getSint32List();
  /**
   * <code>repeated sint32 sint32 = 13;</code>
   * @return The count of sint32.
   */
  int getSint32Count();
  /**
   * <code>repeated sint32 sint32 = 13;</code>
   * @param index The index of the element to return.
   * @return The sint32 at the given index.
   */
  int getSint32(int index);

  /**
   * <code>repeated sint64 sint64 = 14;</code>
   * @return A list containing the sint64.
   */
  java.util.List<java.lang.Long> getSint64List();
  /**
   * <code>repeated sint64 sint64 = 14;</code>
   * @return The count of sint64.
   */
  int getSint64Count();
  /**
   * <code>repeated sint64 sint64 = 14;</code>
   * @param index The index of the element to return.
   * @return The sint64 at the given index.
   */
  long getSint64(int index);

  /**
   * <code>repeated sfixed32 sfixed32 = 15;</code>
   * @return A list containing the sfixed32.
   */
  java.util.List<java.lang.Integer> getSfixed32List();
  /**
   * <code>repeated sfixed32 sfixed32 = 15;</code>
   * @return The count of sfixed32.
   */
  int getSfixed32Count();
  /**
   * <code>repeated sfixed32 sfixed32 = 15;</code>
   * @param index The index of the element to return.
   * @return The sfixed32 at the given index.
   */
  int getSfixed32(int index);

  /**
   * <code>repeated sfixed64 sfixed64 = 16;</code>
   * @return A list containing the sfixed64.
   */
  java.util.List<java.lang.Long> getSfixed64List();
  /**
   * <code>repeated sfixed64 sfixed64 = 16;</code>
   * @return The count of sfixed64.
   */
  int getSfixed64Count();
  /**
   * <code>repeated sfixed64 sfixed64 = 16;</code>
   * @param index The index of the element to return.
   * @return The sfixed64 at the given index.
   */
  long getSfixed64(int index);

  /**
   * <pre>
   * uint64 set default value for the data type of `uint32`, `uint64`, `fixed32`, `fixed64`.
   * </pre>
   *
   * <code>repeated uint32 uint32 = 17;</code>
   * @return A list containing the uint32.
   */
  java.util.List<java.lang.Integer> getUint32List();
  /**
   * <pre>
   * uint64 set default value for the data type of `uint32`, `uint64`, `fixed32`, `fixed64`.
   * </pre>
   *
   * <code>repeated uint32 uint32 = 17;</code>
   * @return The count of uint32.
   */
  int getUint32Count();
  /**
   * <pre>
   * uint64 set default value for the data type of `uint32`, `uint64`, `fixed32`, `fixed64`.
   * </pre>
   *
   * <code>repeated uint32 uint32 = 17;</code>
   * @param index The index of the element to return.
   * @return The uint32 at the given index.
   */
  int getUint32(int index);

  /**
   * <code>repeated uint64 uint64 = 18;</code>
   * @return A list containing the uint64.
   */
  java.util.List<java.lang.Long> getUint64List();
  /**
   * <code>repeated uint64 uint64 = 18;</code>
   * @return The count of uint64.
   */
  int getUint64Count();
  /**
   * <code>repeated uint64 uint64 = 18;</code>
   * @param index The index of the element to return.
   * @return The uint64 at the given index.
   */
  long getUint64(int index);

  /**
   * <code>repeated fixed32 fixed32 = 19;</code>
   * @return A list containing the fixed32.
   */
  java.util.List<java.lang.Integer> getFixed32List();
  /**
   * <code>repeated fixed32 fixed32 = 19;</code>
   * @return The count of fixed32.
   */
  int getFixed32Count();
  /**
   * <code>repeated fixed32 fixed32 = 19;</code>
   * @param index The index of the element to return.
   * @return The fixed32 at the given index.
   */
  int getFixed32(int index);

  /**
   * <code>repeated fixed64 fixed64 = 20;</code>
   * @return A list containing the fixed64.
   */
  java.util.List<java.lang.Long> getFixed64List();
  /**
   * <code>repeated fixed64 fixed64 = 20;</code>
   * @return The count of fixed64.
   */
  int getFixed64Count();
  /**
   * <code>repeated fixed64 fixed64 = 20;</code>
   * @param index The index of the element to return.
   * @return The fixed64 at the given index.
   */
  long getFixed64(int index);

  /**
   * <pre>
   * float set default value for the data type of `float` and `double`.
   * </pre>
   *
   * <code>repeated float float = 21;</code>
   * @return A list containing the float.
   */
  java.util.List<java.lang.Float> getFloatList();
  /**
   * <pre>
   * float set default value for the data type of `float` and `double`.
   * </pre>
   *
   * <code>repeated float float = 21;</code>
   * @return The count of float.
   */
  int getFloatCount();
  /**
   * <pre>
   * float set default value for the data type of `float` and `double`.
   * </pre>
   *
   * <code>repeated float float = 21;</code>
   * @param index The index of the element to return.
   * @return The float at the given index.
   */
  float getFloat(int index);

  /**
   * <code>repeated double double = 22;</code>
   * @return A list containing the double.
   */
  java.util.List<java.lang.Double> getDoubleList();
  /**
   * <code>repeated double double = 22;</code>
   * @return The count of double.
   */
  int getDoubleCount();
  /**
   * <code>repeated double double = 22;</code>
   * @param index The index of the element to return.
   * @return The double at the given index.
   */
  double getDouble(int index);

  /**
   * <pre>
   * bool set default value for the data type of `bool`.
   * </pre>
   *
   * <code>repeated bool bool = 23;</code>
   * @return A list containing the bool.
   */
  java.util.List<java.lang.Boolean> getBoolList();
  /**
   * <pre>
   * bool set default value for the data type of `bool`.
   * </pre>
   *
   * <code>repeated bool bool = 23;</code>
   * @return The count of bool.
   */
  int getBoolCount();
  /**
   * <pre>
   * bool set default value for the data type of `bool`.
   * </pre>
   *
   * <code>repeated bool bool = 23;</code>
   * @param index The index of the element to return.
   * @return The bool at the given index.
   */
  boolean getBool(int index);

  /**
   * <pre>
   * enum set default value for the data type of `enum`.
   * </pre>
   *
   * <code>repeated int32 enum = 24;</code>
   * @return A list containing the enum.
   */
  java.util.List<java.lang.Integer> getEnumList();
  /**
   * <pre>
   * enum set default value for the data type of `enum`.
   * </pre>
   *
   * <code>repeated int32 enum = 24;</code>
   * @return The count of enum.
   */
  int getEnumCount();
  /**
   * <pre>
   * enum set default value for the data type of `enum`.
   * </pre>
   *
   * <code>repeated int32 enum = 24;</code>
   * @param index The index of the element to return.
   * @return The enum at the given index.
   */
  int getEnum(int index);

  /**
   * <pre>
   * string set default value for the data type of `string`.
   * </pre>
   *
   * <code>repeated string string = 25;</code>
   * @return A list containing the string.
   */
  java.util.List<java.lang.String>
      getStringList();
  /**
   * <pre>
   * string set default value for the data type of `string`.
   * </pre>
   *
   * <code>repeated string string = 25;</code>
   * @return The count of string.
   */
  int getStringCount();
  /**
   * <pre>
   * string set default value for the data type of `string`.
   * </pre>
   *
   * <code>repeated string string = 25;</code>
   * @param index The index of the element to return.
   * @return The string at the given index.
   */
  java.lang.String getString(int index);
  /**
   * <pre>
   * string set default value for the data type of `string`.
   * </pre>
   *
   * <code>repeated string string = 25;</code>
   * @param index The index of the value to return.
   * @return The bytes of the string at the given index.
   */
  com.google.protobuf.ByteString
      getStringBytes(int index);

  /**
   * <pre>
   * bytes set default value for the data type of `bytes`.
   * </pre>
   *
   * <code>repeated bytes bytes = 26;</code>
   * @return A list containing the bytes.
   */
  java.util.List<com.google.protobuf.ByteString> getBytesList();
  /**
   * <pre>
   * bytes set default value for the data type of `bytes`.
   * </pre>
   *
   * <code>repeated bytes bytes = 26;</code>
   * @return The count of bytes.
   */
  int getBytesCount();
  /**
   * <pre>
   * bytes set default value for the data type of `bytes`.
   * </pre>
   *
   * <code>repeated bytes bytes = 26;</code>
   * @param index The index of the element to return.
   * @return The bytes at the given index.
   */
  com.google.protobuf.ByteString getBytes(int index);

  /**
   * <pre>
   * message set default value for the data type of `message`.
   * </pre>
   *
   * <code>repeated .defaults.MessageType message = 27;</code>
   */
  java.util.List<io.github.yu31.protoc.pb.pbdefaults.MessageType> 
      getMessageList();
  /**
   * <pre>
   * message set default value for the data type of `message`.
   * </pre>
   *
   * <code>repeated .defaults.MessageType message = 27;</code>
   */
  io.github.yu31.protoc.pb.pbdefaults.MessageType getMessage(int index);
  /**
   * <pre>
   * message set default value for the data type of `message`.
   * </pre>
   *
   * <code>repeated .defaults.MessageType message = 27;</code>
   */
  int getMessageCount();
  /**
   * <pre>
   * message set default value for the data type of `message`.
   * </pre>
   *
   * <code>repeated .defaults.MessageType message = 27;</code>
   */
  java.util.List<? extends io.github.yu31.protoc.pb.pbdefaults.MessageTypeOrBuilder> 
      getMessageOrBuilderList();
  /**
   * <pre>
   * message set default value for the data type of `message`.
   * </pre>
   *
   * <code>repeated .defaults.MessageType message = 27;</code>
   */
  io.github.yu31.protoc.pb.pbdefaults.MessageTypeOrBuilder getMessageOrBuilder(
      int index);

  /**
   * <pre>
   * any set default value for the data type of `google.protobuf.Any`.
   * </pre>
   *
   * <code>repeated .defaults.AnyType any = 31;</code>
   */
  java.util.List<io.github.yu31.protoc.pb.pbdefaults.AnyType> 
      getAnyList();
  /**
   * <pre>
   * any set default value for the data type of `google.protobuf.Any`.
   * </pre>
   *
   * <code>repeated .defaults.AnyType any = 31;</code>
   */
  io.github.yu31.protoc.pb.pbdefaults.AnyType getAny(int index);
  /**
   * <pre>
   * any set default value for the data type of `google.protobuf.Any`.
   * </pre>
   *
   * <code>repeated .defaults.AnyType any = 31;</code>
   */
  int getAnyCount();
  /**
   * <pre>
   * any set default value for the data type of `google.protobuf.Any`.
   * </pre>
   *
   * <code>repeated .defaults.AnyType any = 31;</code>
   */
  java.util.List<? extends io.github.yu31.protoc.pb.pbdefaults.AnyTypeOrBuilder> 
      getAnyOrBuilderList();
  /**
   * <pre>
   * any set default value for the data type of `google.protobuf.Any`.
   * </pre>
   *
   * <code>repeated .defaults.AnyType any = 31;</code>
   */
  io.github.yu31.protoc.pb.pbdefaults.AnyTypeOrBuilder getAnyOrBuilder(
      int index);

  /**
   * <pre>
   * duration set default value for the data type of `google.protobuf.Duration`.
   * </pre>
   *
   * <code>repeated .google.protobuf.Duration duration = 32;</code>
   */
  java.util.List<com.google.protobuf.Duration> 
      getDurationList();
  /**
   * <pre>
   * duration set default value for the data type of `google.protobuf.Duration`.
   * </pre>
   *
   * <code>repeated .google.protobuf.Duration duration = 32;</code>
   */
  com.google.protobuf.Duration getDuration(int index);
  /**
   * <pre>
   * duration set default value for the data type of `google.protobuf.Duration`.
   * </pre>
   *
   * <code>repeated .google.protobuf.Duration duration = 32;</code>
   */
  int getDurationCount();
  /**
   * <pre>
   * duration set default value for the data type of `google.protobuf.Duration`.
   * </pre>
   *
   * <code>repeated .google.protobuf.Duration duration = 32;</code>
   */
  java.util.List<? extends com.google.protobuf.DurationOrBuilder> 
      getDurationOrBuilderList();
  /**
   * <pre>
   * duration set default value for the data type of `google.protobuf.Duration`.
   * </pre>
   *
   * <code>repeated .google.protobuf.Duration duration = 32;</code>
   */
  com.google.protobuf.DurationOrBuilder getDurationOrBuilder(
      int index);

  /**
   * <pre>
   * timestamp set default value for the data type of `google.protobuf.Timestamp`.
   * </pre>
   *
   * <code>repeated .google.protobuf.Timestamp timestamp = 33;</code>
   */
  java.util.List<com.google.protobuf.Timestamp> 
      getTimestampList();
  /**
   * <pre>
   * timestamp set default value for the data type of `google.protobuf.Timestamp`.
   * </pre>
   *
   * <code>repeated .google.protobuf.Timestamp timestamp = 33;</code>
   */
  com.google.protobuf.Timestamp getTimestamp(int index);
  /**
   * <pre>
   * timestamp set default value for the data type of `google.protobuf.Timestamp`.
   * </pre>
   *
   * <code>repeated .google.protobuf.Timestamp timestamp = 33;</code>
   */
  int getTimestampCount();
  /**
   * <pre>
   * timestamp set default value for the data type of `google.protobuf.Timestamp`.
   * </pre>
   *
   * <code>repeated .google.protobuf.Timestamp timestamp = 33;</code>
   */
  java.util.List<? extends com.google.protobuf.TimestampOrBuilder> 
      getTimestampOrBuilderList();
  /**
   * <pre>
   * timestamp set default value for the data type of `google.protobuf.Timestamp`.
   * </pre>
   *
   * <code>repeated .google.protobuf.Timestamp timestamp = 33;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder(
      int index);
}
