// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: defaults.proto

package io.github.yu31.protoc.pb.pbdefaults;

/**
 * <pre>
 * RepeatedOptions declares the options applied to the repeated filed.
 * </pre>
 *
 * Protobuf type {@code defaults.RepeatedOptions}
 */
public final class RepeatedOptions extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:defaults.RepeatedOptions)
    RepeatedOptionsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RepeatedOptions.newBuilder() to construct.
  private RepeatedOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RepeatedOptions() {
    items_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RepeatedOptions();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RepeatedOptions(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              items_ = new java.util.ArrayList<io.github.yu31.protoc.pb.pbdefaults.FieldType>();
              mutable_bitField0_ |= 0x00000001;
            }
            items_.add(
                input.readMessage(io.github.yu31.protoc.pb.pbdefaults.FieldType.parser(), extensionRegistry));
            break;
          }
          case 16: {
            bitField0_ |= 0x00000001;
            ignoreEmpty_ = input.readBool();
            break;
          }
          case 88: {
            bitField0_ |= 0x00000002;
            skipEval_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        items_ = java.util.Collections.unmodifiableList(items_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_RepeatedOptions_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_RepeatedOptions_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions.class, io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions.Builder.class);
  }

  private int bitField0_;
  public static final int ITEMS_FIELD_NUMBER = 1;
  private java.util.List<io.github.yu31.protoc.pb.pbdefaults.FieldType> items_;
  /**
   * <pre>
   * items declares the default value for field.
   * </pre>
   *
   * <code>repeated .defaults.FieldType items = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.github.yu31.protoc.pb.pbdefaults.FieldType> getItemsList() {
    return items_;
  }
  /**
   * <pre>
   * items declares the default value for field.
   * </pre>
   *
   * <code>repeated .defaults.FieldType items = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <pre>
   * items declares the default value for field.
   * </pre>
   *
   * <code>repeated .defaults.FieldType items = 1;</code>
   */
  @java.lang.Override
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <pre>
   * items declares the default value for field.
   * </pre>
   *
   * <code>repeated .defaults.FieldType items = 1;</code>
   */
  @java.lang.Override
  public io.github.yu31.protoc.pb.pbdefaults.FieldType getItems(int index) {
    return items_.get(index);
  }
  /**
   * <pre>
   * items declares the default value for field.
   * </pre>
   *
   * <code>repeated .defaults.FieldType items = 1;</code>
   */
  @java.lang.Override
  public io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  public static final int IGNORE_EMPTY_FIELD_NUMBER = 2;
  private boolean ignoreEmpty_;
  /**
   * <pre>
   * By default, The default value will be applied if the length of field is zero.
   * If `ignore_empty` is true, Only apply the default value if the field is a nil pointer.
   * Only effective for language Go.
   * </pre>
   *
   * <code>optional bool ignore_empty = 2;</code>
   * @return Whether the ignoreEmpty field is set.
   */
  @java.lang.Override
  public boolean hasIgnoreEmpty() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * By default, The default value will be applied if the length of field is zero.
   * If `ignore_empty` is true, Only apply the default value if the field is a nil pointer.
   * Only effective for language Go.
   * </pre>
   *
   * <code>optional bool ignore_empty = 2;</code>
   * @return The ignoreEmpty.
   */
  @java.lang.Override
  public boolean getIgnoreEmpty() {
    return ignoreEmpty_;
  }

  public static final int SKIP_EVAL_FIELD_NUMBER = 11;
  private boolean skipEval_;
  /**
   * <pre>
   * By default, We will try to eval call the method of defaults for type of repeated items are message and any.
   * If `skip_eval` is true, the method of defaults will not be called.
   * Only effective for language Go.
   * </pre>
   *
   * <code>optional bool skip_eval = 11;</code>
   * @return Whether the skipEval field is set.
   */
  @java.lang.Override
  public boolean hasSkipEval() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * By default, We will try to eval call the method of defaults for type of repeated items are message and any.
   * If `skip_eval` is true, the method of defaults will not be called.
   * Only effective for language Go.
   * </pre>
   *
   * <code>optional bool skip_eval = 11;</code>
   * @return The skipEval.
   */
  @java.lang.Override
  public boolean getSkipEval() {
    return skipEval_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(1, items_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(2, ignoreEmpty_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBool(11, skipEval_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, items_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, ignoreEmpty_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, skipEval_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions)) {
      return super.equals(obj);
    }
    io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions other = (io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions) obj;

    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (hasIgnoreEmpty() != other.hasIgnoreEmpty()) return false;
    if (hasIgnoreEmpty()) {
      if (getIgnoreEmpty()
          != other.getIgnoreEmpty()) return false;
    }
    if (hasSkipEval() != other.hasSkipEval()) return false;
    if (hasSkipEval()) {
      if (getSkipEval()
          != other.getSkipEval()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    if (hasIgnoreEmpty()) {
      hash = (37 * hash) + IGNORE_EMPTY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIgnoreEmpty());
    }
    if (hasSkipEval()) {
      hash = (37 * hash) + SKIP_EVAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSkipEval());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * RepeatedOptions declares the options applied to the repeated filed.
   * </pre>
   *
   * Protobuf type {@code defaults.RepeatedOptions}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:defaults.RepeatedOptions)
      io.github.yu31.protoc.pb.pbdefaults.RepeatedOptionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_RepeatedOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_RepeatedOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions.class, io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions.Builder.class);
    }

    // Construct using io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getItemsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        itemsBuilder_.clear();
      }
      ignoreEmpty_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      skipEval_ = false;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.yu31.protoc.pb.pbdefaults.PBDefaults.internal_static_defaults_RepeatedOptions_descriptor;
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions getDefaultInstanceForType() {
      return io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions build() {
      io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions buildPartial() {
      io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions result = new io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ignoreEmpty_ = ignoreEmpty_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.skipEval_ = skipEval_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions) {
        return mergeFrom((io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions other) {
      if (other == io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions.getDefaultInstance()) return this;
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      if (other.hasIgnoreEmpty()) {
        setIgnoreEmpty(other.getIgnoreEmpty());
      }
      if (other.hasSkipEval()) {
        setSkipEval(other.getSkipEval());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.github.yu31.protoc.pb.pbdefaults.FieldType> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        items_ = new java.util.ArrayList<io.github.yu31.protoc.pb.pbdefaults.FieldType>(items_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.github.yu31.protoc.pb.pbdefaults.FieldType, io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder, io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder> itemsBuilder_;

    /**
     * <pre>
     * items declares the default value for field.
     * </pre>
     *
     * <code>repeated .defaults.FieldType items = 1;</code>
     */
    public java.util.List<io.github.yu31.protoc.pb.pbdefaults.FieldType> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * items declares the default value for field.
     * </pre>
     *
     * <code>repeated .defaults.FieldType items = 1;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * items declares the default value for field.
     * </pre>
     *
     * <code>repeated .defaults.FieldType items = 1;</code>
     */
    public io.github.yu31.protoc.pb.pbdefaults.FieldType getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * items declares the default value for field.
     * </pre>
     *
     * <code>repeated .defaults.FieldType items = 1;</code>
     */
    public Builder setItems(
        int index, io.github.yu31.protoc.pb.pbdefaults.FieldType value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * items declares the default value for field.
     * </pre>
     *
     * <code>repeated .defaults.FieldType items = 1;</code>
     */
    public Builder setItems(
        int index, io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * items declares the default value for field.
     * </pre>
     *
     * <code>repeated .defaults.FieldType items = 1;</code>
     */
    public Builder addItems(io.github.yu31.protoc.pb.pbdefaults.FieldType value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * items declares the default value for field.
     * </pre>
     *
     * <code>repeated .defaults.FieldType items = 1;</code>
     */
    public Builder addItems(
        int index, io.github.yu31.protoc.pb.pbdefaults.FieldType value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * items declares the default value for field.
     * </pre>
     *
     * <code>repeated .defaults.FieldType items = 1;</code>
     */
    public Builder addItems(
        io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * items declares the default value for field.
     * </pre>
     *
     * <code>repeated .defaults.FieldType items = 1;</code>
     */
    public Builder addItems(
        int index, io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * items declares the default value for field.
     * </pre>
     *
     * <code>repeated .defaults.FieldType items = 1;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends io.github.yu31.protoc.pb.pbdefaults.FieldType> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * items declares the default value for field.
     * </pre>
     *
     * <code>repeated .defaults.FieldType items = 1;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * items declares the default value for field.
     * </pre>
     *
     * <code>repeated .defaults.FieldType items = 1;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * items declares the default value for field.
     * </pre>
     *
     * <code>repeated .defaults.FieldType items = 1;</code>
     */
    public io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * items declares the default value for field.
     * </pre>
     *
     * <code>repeated .defaults.FieldType items = 1;</code>
     */
    public io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * items declares the default value for field.
     * </pre>
     *
     * <code>repeated .defaults.FieldType items = 1;</code>
     */
    public java.util.List<? extends io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <pre>
     * items declares the default value for field.
     * </pre>
     *
     * <code>repeated .defaults.FieldType items = 1;</code>
     */
    public io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          io.github.yu31.protoc.pb.pbdefaults.FieldType.getDefaultInstance());
    }
    /**
     * <pre>
     * items declares the default value for field.
     * </pre>
     *
     * <code>repeated .defaults.FieldType items = 1;</code>
     */
    public io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, io.github.yu31.protoc.pb.pbdefaults.FieldType.getDefaultInstance());
    }
    /**
     * <pre>
     * items declares the default value for field.
     * </pre>
     *
     * <code>repeated .defaults.FieldType items = 1;</code>
     */
    public java.util.List<io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.github.yu31.protoc.pb.pbdefaults.FieldType, io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder, io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.github.yu31.protoc.pb.pbdefaults.FieldType, io.github.yu31.protoc.pb.pbdefaults.FieldType.Builder, io.github.yu31.protoc.pb.pbdefaults.FieldTypeOrBuilder>(
                items_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    private boolean ignoreEmpty_ ;
    /**
     * <pre>
     * By default, The default value will be applied if the length of field is zero.
     * If `ignore_empty` is true, Only apply the default value if the field is a nil pointer.
     * Only effective for language Go.
     * </pre>
     *
     * <code>optional bool ignore_empty = 2;</code>
     * @return Whether the ignoreEmpty field is set.
     */
    @java.lang.Override
    public boolean hasIgnoreEmpty() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * By default, The default value will be applied if the length of field is zero.
     * If `ignore_empty` is true, Only apply the default value if the field is a nil pointer.
     * Only effective for language Go.
     * </pre>
     *
     * <code>optional bool ignore_empty = 2;</code>
     * @return The ignoreEmpty.
     */
    @java.lang.Override
    public boolean getIgnoreEmpty() {
      return ignoreEmpty_;
    }
    /**
     * <pre>
     * By default, The default value will be applied if the length of field is zero.
     * If `ignore_empty` is true, Only apply the default value if the field is a nil pointer.
     * Only effective for language Go.
     * </pre>
     *
     * <code>optional bool ignore_empty = 2;</code>
     * @param value The ignoreEmpty to set.
     * @return This builder for chaining.
     */
    public Builder setIgnoreEmpty(boolean value) {
      bitField0_ |= 0x00000002;
      ignoreEmpty_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * By default, The default value will be applied if the length of field is zero.
     * If `ignore_empty` is true, Only apply the default value if the field is a nil pointer.
     * Only effective for language Go.
     * </pre>
     *
     * <code>optional bool ignore_empty = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIgnoreEmpty() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ignoreEmpty_ = false;
      onChanged();
      return this;
    }

    private boolean skipEval_ ;
    /**
     * <pre>
     * By default, We will try to eval call the method of defaults for type of repeated items are message and any.
     * If `skip_eval` is true, the method of defaults will not be called.
     * Only effective for language Go.
     * </pre>
     *
     * <code>optional bool skip_eval = 11;</code>
     * @return Whether the skipEval field is set.
     */
    @java.lang.Override
    public boolean hasSkipEval() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * By default, We will try to eval call the method of defaults for type of repeated items are message and any.
     * If `skip_eval` is true, the method of defaults will not be called.
     * Only effective for language Go.
     * </pre>
     *
     * <code>optional bool skip_eval = 11;</code>
     * @return The skipEval.
     */
    @java.lang.Override
    public boolean getSkipEval() {
      return skipEval_;
    }
    /**
     * <pre>
     * By default, We will try to eval call the method of defaults for type of repeated items are message and any.
     * If `skip_eval` is true, the method of defaults will not be called.
     * Only effective for language Go.
     * </pre>
     *
     * <code>optional bool skip_eval = 11;</code>
     * @param value The skipEval to set.
     * @return This builder for chaining.
     */
    public Builder setSkipEval(boolean value) {
      bitField0_ |= 0x00000004;
      skipEval_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * By default, We will try to eval call the method of defaults for type of repeated items are message and any.
     * If `skip_eval` is true, the method of defaults will not be called.
     * Only effective for language Go.
     * </pre>
     *
     * <code>optional bool skip_eval = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkipEval() {
      bitField0_ = (bitField0_ & ~0x00000004);
      skipEval_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:defaults.RepeatedOptions)
  }

  // @@protoc_insertion_point(class_scope:defaults.RepeatedOptions)
  private static final io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions();
  }

  public static io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RepeatedOptions>
      PARSER = new com.google.protobuf.AbstractParser<RepeatedOptions>() {
    @java.lang.Override
    public RepeatedOptions parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RepeatedOptions(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RepeatedOptions> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RepeatedOptions> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.yu31.protoc.pb.pbdefaults.RepeatedOptions getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

