// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: defaults.proto

package io.github.yu31.protoc.pb.pbdefaults;

public interface TypeBytesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:defaults.TypeBytes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes value = 1;</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();

  /**
   * <pre>
   * 默认情况下, 如果字段的长度为 0 则将其设置为默认值, 如果希望只有字段为空指针时才设置默认值, 可以将 'ignore_empty' 设置为 true.
   * </pre>
   *
   * <code>optional bool ignore_empty = 11;</code>
   * @return Whether the ignoreEmpty field is set.
   */
  boolean hasIgnoreEmpty();
  /**
   * <pre>
   * 默认情况下, 如果字段的长度为 0 则将其设置为默认值, 如果希望只有字段为空指针时才设置默认值, 可以将 'ignore_empty' 设置为 true.
   * </pre>
   *
   * <code>optional bool ignore_empty = 11;</code>
   * @return The ignoreEmpty.
   */
  boolean getIgnoreEmpty();
}
